Cache Safe api requests for 1 minute
decent-dao/fractal-interface pull request #1028
Opened 2023-02-23 22:14 UTC by herbig

## Description

Uses the new caching hook to cache all the Safe API requests locally for 1 minute.

2023-02-24 02:49 UTC, Da-Colon requested changes
Looks like it is loading everything into local storage correctly.

I am seeing some weird behavior when I refresh the page.
[ ] The Info sections at the top get stuck in a loading state
[ ] The Proposals seem to flicker twice before settling.

[ ] App crashes when you go to Treasury page
![image](https://user-images.githubusercontent.com/38386583/221079838-f800c5cd-652c-4e80-a896-b43e2cb0f4fe.png)

2023-02-24 03:24 UTC, herbig commented
> [ ] App crashes when you go to Treasury page

hmm, yikes, I'll take a look

2023-02-24 17:13 UTC, herbig commented
I'm putting this off until after Eth Denver, as this is a bit janky and needs a lot more testing before we're confident to throw this in.

2023-02-24 17:29 UTC, Da-Colon commented on src/providers/Fractal/hooks/useGnosisApiServices.ts
> +            return axios.get(buildGnosisApiUrl(safeBaseURL, `/safes/${address}/transfers/`));
There was an `GET` endpoint that wasn't available via their SDK at the time, I can't remember if this was the one. but yeah  should look into if it can get swapped out

2023-02-25 05:48 UTC, herbig commented
I may bring this back in some other form, but this is pretty janky and doesn't solve the issue of multiple network requests anyway, so closing this.

2023-02-25 05:48 UTC, closed without merging