Update/parent token allocation
decent-dao/fractal-interface pull request #1048
Opened 2023-03-01 00:05 UTC by Da-Colon

## Description
Adds Parent Token Claiming

- Adds Parent Token UI Component to Create SubDAO workflow
- Updates DaoBuilder and UsulBuilder to build and deploy claim contract
- Add UI to DAO Dashboard to claim tokens

## Notes

## Issue / Notion doc (if applicable)

## Testing
- Create a Parent Token DAO
- Create a SubDAO Proposal and allocate an amount to parent Allocation
- After Proposal Passes, visit new DAO

## Screenshots (if applicable)
![localhost_3000_(Desktop) (41)](https://user-images.githubusercontent.com/38386583/222010865-ba31dd26-9417-41a0-8386-a5eb3c0b4a0f.png)

2023-03-08 13:24 UTC, herbig commented on src/pages/DaoDashboard/TokenClaim.tsx
> +    const claimableString = utils.formatUnits(userClaimable, governanceToken.decimals);
we have `numberFormats.formatCoin` which will do this, handle trailing zeros, and the symbol

2023-03-08 13:29 UTC, herbig commented on src/components/DaoCreator/UsulParentTokenAllocation.tsx
> +  return <div></div>;
this looks like it was stubbed but never finished or used!

2023-03-08 13:35 UTC, herbig commented on src/models/DaoTxBuilder.ts
> +    // token claim deployment tx is pushed at the end to ensure approval is executed first
can't the `tokenClaimTx` claim block above just be at the end as well?

2023-03-08 13:40 UTC, herbig commented on src/pages/DaoDashboard/TokenClaim.tsx
> +      successMessage: t('successTokenClaim', {
we have other pending / failed / success messages in `transaction.json`, not sure it's the best system, but would probably be good to stick to it for now

2023-03-08 13:42 UTC, herbig commented on src/pages/DaoDashboard/TokenClaim.tsx
> +  const claimableString = utils.formatUnits(userClaimable, governanceToken.decimals);
this could be defined above `claimToken` and used in the success message as well

2023-03-08 15:07 UTC, herbig requested changes
- [x] ` {{parentName}}` in the helper text should be filled with the parent's name, or change to just "claimable by all parent token holders"
- [x] The error logic seems a bit off.  It seems like I can't have claimable tokens without at least one address allocated above, I don't think that should be the case.
- [ ] The Advanced component is a lot different from the designs, but honestly I'm not sure what the logic for the original designs should be.. We should discuss with @xraystyle1980 and make sure we're not losing something with this simpler input field.
- [x] The claim component on the DAO homepage has an info i icon, rather than the ! icon

2023-03-08 17:06 UTC, Da-Colon commented on src/components/DaoCreator/formComponents/UsulTokenAllocations.tsx
> +                                (errors.govToken?.parentAllocationAmount as any)
yessir since this is a required value. It will show "This value is required" on load or if the field is empty.  since validation is ran on mount. currently we weren't showing 'required' errors. We could switch this up, would just need to create some logic to diasable the button on each screen on intial by whether things were touched* and then create error string for each of these.

2023-03-08 17:10 UTC, Da-Colon commented on src/components/DaoCreator/UsulParentTokenAllocation.tsx
> +  return <div></div>;
Ah @herbig, I'll answer here as you asked same question. Yeah I was going to extract out at the beginning and stubbed it, got left in. I'll remove.

2023-03-08 17:12 UTC, Da-Colon commented on src/models/UsulTxBuilder.ts
> -      '5af43d82803e903d91602b57fd5bf3';
@sethhrbek might be able to explain it better. but this is how the signature must be structured based on the code from contract.

2023-03-08 17:26 UTC, sethhrbek commented on src/models/UsulTxBuilder.ts
> -      '5af43d82803e903d91602b57fd5bf3';
yeah these are the strings that are in gnosis' module proxy factory -- the strings differ slightly between the gnosis module in the npm package and the latest contracts they have on their github. 

When we deploy the newest contract changes, we should also deploy the module proxy factory on goerli (and update the proxy master copy address) to ensure 100% these strings match the ones in gnosis mainnet module proxy factory

2023-03-08 18:42 UTC, herbig commented
> > The Advanced component is a lot different from the designs, but honestly I'm not sure what the logic for the original designs should be.. We should discuss with @xraystyle1980 and make sure we're not losing something with this simpler input field.
> 
> ![image](https://user-images.githubusercontent.com/38386583/223781311-ca7800d1-d776-4db8-b014-3e19ca2aa9a8.png)
> 
> O I must be blind did not see this block here when I did this? is this new? this can be a future PR

yeah, we can do that in a followup for sure

🤷 maybe it was added later on?  @xraystyle1980 ?

2023-03-09 21:10 UTC, Da-Colon commented on src/models/DaoTxBuilder.ts
> +    // token claim deployment tx is pushed at the end to ensure approval is executed first
ah no sir, this transaction must happen after the internal txs which is pushed in on line 113. So that approval can take place.

2023-03-09 21:15 UTC, Da-Colon commented on src/pages/DaoDashboard/TokenClaim.tsx
> +  const claimableString = utils.formatUnits(userClaimable, governanceToken.decimals);
? governanceToken.decimals prevents it from being used above here

2023-03-10 16:02 UTC, herbig commented on src/pages/DaoDashboard/TokenClaim.tsx
> +            {t('alertTokenClaim', {
`formatCoin` takes the coin symbol as a parameter, and if it's not provided, formats it as ETH, so I think this will show e.g. "1000 ETH SYMBOL"

`alertTokenClaim` only needs to be  `"You have {{amount}} tokens to claim!"`, without the symbol, and the symbol you provide to `formatCoin`

2023-03-13 01:37 UTC, herbig approved these changes

2023-03-13 14:39 UTC, tbwebb22 approved these changes
Tested a few different combos of allocation amounts, worked perfectly for me, nice work

2023-03-14 05:19 UTC, merged