Add remove owners
decent-dao/fractal-interface pull request #1126
Opened 2023-04-13 22:02 UTC by tbwebb22

## Description
This PR:
1) Adds a "Manage Signers" option on the "Manage DAO" menu option
2) Adds a page listing the current safe signers, and buttons for adding and removing signers
3) Adds modals for both adding and removing signers, which allows a user to create a proposal to do either action

![image](https://user-images.githubusercontent.com/84364476/231892261-738b8b69-8df7-4d4a-88a4-d3da3aff9b94.png)
![image](https://user-images.githubusercontent.com/84364476/231892305-8163ee50-c980-4bd7-84a7-cb152be751d2.png)
![image](https://user-images.githubusercontent.com/84364476/231892443-e09d7760-208a-4d90-a452-8db2490f8e16.png)
![image](https://user-images.githubusercontent.com/84364476/231892486-eebba4ce-5c5d-4f76-9bd8-f48086f556d0.png)

## Notes

## Issue / Notion doc (if applicable)

## Testing
1) Create a proposal to add a signer, execute the proposal and verify that the signer was added to the safe
2) Create a proposal to remove a signer, execute the proposal and verify that the signer was removed from the safe

## Screenshots (if applicable)

2023-04-14 13:03 UTC, herbig requested changes
Hey @tbwebb22 the add/remove part works great!  Here's some UI feedback

Main page
- [x] let's remove the "daoName Signers" title, we don't have a title like this on any other screen (I'll let Matt know)
- [x] Signers / DAO details should be full width and move to a single column in a smaller window, in the same way the Treasury page works
- [ ] Only the first signer row has proper bottom margin for some reason
- [x] the horizontal lines are darker than designs, should be the same as Treasury
- [ ] addresses with an ENS should display those instead
- [ ] DAO details should wrap vertically to its content
- [ ] if the wallet is not connected OR the wallet is not a current signer, don't show the add / remove buttons

Modal
- [ ] we should not allow adding a signer that's already there, since that transaction will fail
- [ ] the modal uses Send Assets pending / success messages
- [ ] we should default the Update required signers to what it currently is
- [ ] the "Access" warning should have blue background, identical to the one in Create Proposal
- [ ] Add Signers seemed to work, but the new address never appears in the list

2023-04-18 16:25 UTC, herbig commented
> 

@sethhrbek good call on cursors, especially for the X icon, that's not on any of our modals.

For the tooltip, that's a known issue, which we have a ticket for to investigate.  For some reason tooltips aren't appearing in modals in Chakra

2023-04-18 18:48 UTC, tbwebb22 commented on src/constants/routes.ts
> +  },
Cool, updated this route to `manage-signers`

2023-04-19 13:43 UTC, tbwebb22 commented
> 



> <img alt="image" width="545" src="https://user-images.githubusercontent.com/43755993/232806482-9851aac6-b8be-4dfb-b328-474204aa1e48.png">
> 
> Minor stuff on the modal ---
> 
> 1. If you click "Add signer" to open the modal, then take any action except pasting an address, you will get the `Ethereum wallet address or ENS only` validation error (including when you try to close the modal). Maybe the validation error only shows if user enters something into the input and it is invalid?
> 2. A few elements on the modal could have `cursor: pointer` to show cursor as a hand to indicate its clickable:
>    a. Close modal
>    b. Signer # dropdown
> 3. There is a tooltip icon (with the question mark), but it doesn't show anything on click or hover

Yep, these have been addressed (with the exception of #3, which sounds like we are handling in a separate PR

2023-04-19 13:45 UTC, tbwebb22 commented
> 
@sethhrbek Regarding the data refresh for updating signers - talked with @Da-Colon about this yesterday, sounds like a global issue that he wants to handle in a separate PR - the Gnosis Safe data needs to be refreshed any time after a proposal is executed, which should resolve this instance.

2023-04-19 14:20 UTC, herbig commented on src/components/pages/ManageSigners/AddSignerModal.tsx
> +                >{`out of ${signers.length + 1} signers required`}</Text>
ah shoot I didn't catch that, yeah we should add any strings to the translation files @tbwebb22

2023-04-19 14:49 UTC, Da-Colon requested changes
loooks good, ➕ to @sethhrbek translation comments and a question about a Modal prop

2023-04-19 14:49 UTC, Da-Colon commented on src/hooks/schemas/common/useValidationAddress.tsx
> +      message: 'Signer is already a signer',
This message is user facing and a new translation can be added and used here.

2023-04-19 15:02 UTC, tbwebb22 commented on src/components/pages/ManageSigners/DaoDetails.tsx
> +            {t('signersInfo1', { ns: 'common' })}
Good call, updated this

2023-04-19 15:13 UTC, herbig commented on src/components/ui/modals/ModalBase.tsx
> +      size="lg"
yeah, @tbwebb22 and I discussed it and decided to keep all modals the same size, so this will increase the size of the others as well

2023-04-19 15:16 UTC, herbig commented on src/components/ui/modals/ModalBase.tsx
> +      size="lg"
Here's a comparison of the Send Assets before / after

<img width="1315" alt="Screenshot 2023-04-19 at 11 15 51 AM" src="https://user-images.githubusercontent.com/384559/233121720-b64125be-e3e9-45d2-ab3b-ae4703fdb689.png">
<img width="1350" alt="Screenshot 2023-04-19 at 11 16 00 AM" src="https://user-images.githubusercontent.com/384559/233121742-8d7e5cda-d74f-4b0f-9671-34a7c4e80f66.png">

2023-04-19 17:23 UTC, herbig approved these changes

2023-04-19 17:58 UTC, tbwebb22 commented on src/components/pages/ManageSigners/AddSignerModal.tsx
> +                >{`out of ${signers.length + 1} signers required`}</Text>
Good call, updated this

2023-04-19 18:04 UTC, tbwebb22 commented on src/hooks/schemas/common/useValidationAddress.tsx
> +      message: 'Signer is already a signer',
Updated this

2023-04-19 18:05 UTC, tbwebb22 commented on src/components/pages/ManageSigners/hooks/useAddSigner.ts
> +        new ethers.utils.Interface([funcSignature]).encodeFunctionData('addOwnerWithThreshold', [
Yes, updated this

2023-04-19 18:40 UTC, Da-Colon approved these changes

2023-04-19 18:43 UTC, merged