Feature |  Import Existing Token
decent-dao/fractal-interface pull request #1142
Opened 2023-04-21 04:46 UTC by Da-Colon

## Title: Feature: Import Existing Token

## Description
This PR adds the ability to import an existing ERC20 token and wrap it for use as a Governance token in a DAO. It covers the first part of deploying a new DAO with this new feature and updates the UI during the token configuration step.

## Main changes
- Modified `AzoriusTxBuilder.ts` to handle the import and wrapping of existing ERC20 tokens.
- Updated `AzoriusTokenDetails.tsx` to include new UI elements for the token configuration step.

## Additional Notes
- Fixed an issue with Toasts not properly closing and a missing translation.
- This PR also covers checking for tokens that are already presumed to be ERC20 Votes tokens.

## Testing
1. Create a new Token DAO using the following methods:
   - As normal
   - With existing VotesToken
   - With existing ERC20 token
2. Ensure that the DAO deploys correctly and shows up as a Token Voting DAO. Note that there is no other way to ensure proper deployment until the other end of this feature is worked on.

## Screenshots (if applicable)
![localhost_3000_create](https://user-images.githubusercontent.com/38386583/233542977-c9a9867d-e816-4368-87bf-469b31683a73.png)

2023-04-21 04:53 UTC, Da-Colon commented on src/components/DaoCreator/formComponents/AzoriusTokenDetails.tsx
> +  ]);
handles the logic to update the tokenName/tokenSymbol. for display purposes

2023-04-21 04:53 UTC, Da-Colon commented on src/components/DaoCreator/formComponents/AzoriusTokenDetails.tsx
> +              />
These `onClick` makes sure to empty the fields when radio is switched

2023-04-21 04:53 UTC, Da-Colon commented on src/components/DaoCreator/formComponents/AzoriusTokenDetails.tsx
> +              </LabelWrapper>
The error message flickers very briefly, I've tried to see if its the useEffect or the test itself but no luck. I'm not sure the cause.

2023-04-21 04:53 UTC, Da-Colon commented on src/hooks/DAO/loaders/useFractalNode.ts
> +  const { t } = useTranslation('dashboard');
Noticed this was missing the library

2023-04-21 14:28 UTC, Da-Colon commented on src/components/DaoCreator/hooks/usePrepareFormData.ts
> +  );
checks if `delegate` function exists. linking*

2023-04-26 00:06 UTC, herbig requested changes
Hey @Da-Colon this works flawlessly! I was able to use Wrapped Ether to govern my DAO ha.

A few things to discuss / fix:

- [x] We should use the same margin between "Select Token" and the component that we use between "Token Metadata" and its component below it
- [ ] Can we instead have the Existing Token address input and blue text appear / disappear depending on if it's selected?
- [x] does the blue color make it look like a hyperlink? not sure if we should change it, just wondering
- [ ] we should decide on a tooltip max width and apply it throughout the app (anything works, just the full line is too long)
- [ ] This is a weird bug, but the click space to change back to the first "New Token" option is basically the whole dark box except for the Existing Token radio option.  Try selecting the second option then clicking the blue text

2023-04-26 15:14 UTC, tbwebb22 commented
When selecting a token, when I input an existing token that does have the ERC20Votes functionality, it still seems that a new wrapped token is being deployed for the DAO. In this case, we wouldn't want to re-deploy a token, and just let the existing VotesToken be used, right?

![image](https://user-images.githubusercontent.com/84364476/234621426-ef2e770d-f983-43d4-b647-66faef7e97c1.png)

2023-04-26 15:23 UTC, herbig commented
> When selecting a token, when I input an existing token that does have the ERC20Votes functionality, it still seems that a new wrapped token is being deployed for the DAO. In this case, we wouldn't want to re-deploy a token, and just let the existing VotesToken be used, right?
> 
> ![image](https://user-images.githubusercontent.com/84364476/234621426-ef2e770d-f983-43d4-b647-66faef7e97c1.png)

Oh true good point,

It's not actually being deployed as wrapped, but the logic should be:

No blue text until the address if legit

Then blue text appears based on whether it's being wrapped or not

2023-04-26 18:06 UTC, tbwebb22 approved these changes
Fix for my comment was implemented on 1144, so LGTM now

2023-04-26 21:07 UTC, herbig commented on src/components/DaoCreator/formComponents/AzoriusTokenDetails.tsx
> +              </LabelWrapper>
strange, yeah I think we could use an app-wide audit of error handling at some point

2023-04-28 15:44 UTC, merged