Signers custom nonce
decent-dao/fractal-interface pull request #1143
Opened 2023-04-24 18:05 UTC by tbwebb22

## Description
This PR adds custom nonce inputs for both the add signers and remove signers modals.

## Notes

## Issue / Notion doc (if applicable)

## Testing

## Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/84364476/234079413-3bee3606-9ad3-4065-8224-5d57f9f2afa7.png)
![image](https://user-images.githubusercontent.com/84364476/234079471-72b67024-2f27-43d4-b692-bb7d3e2e61fb.png)

2023-04-25 15:20 UTC, tbwebb22 commented on src/components/pages/ManageSigners/AddSignerModal.tsx
> +  }, [defaultNonce, nonce]);
Ah yeah I really botched that useEffect, pushed up the fix for both modals.

2023-04-25 22:03 UTC, Da-Colon approved these changes
Nice looks good to go

2023-04-25 22:23 UTC, herbig commented on src/components/pages/ManageSigners/AddSignerModal.tsx
> +    setNonce(defaultNonce);
is there a difference to just doing `setNonce(defaultNonce);` here?

2023-04-25 22:24 UTC, herbig commented on src/components/pages/ManageSigners/AddSignerModal.tsx
> +    setNonce(defaultNonce);
without the if statement I mean, it seems like if it's `!defaultNonce` then it's undefined

2023-04-25 22:41 UTC, herbig commented on src/components/pages/ManageSigners/AddSignerModal.tsx
> +              onChange={newNonce => setNonce(newNonce ? newNonce : undefined)}
same here, `newNonce` is `number | undefined`, so this can just be simplified to `newNonce => setNonce(newNonce)`

2023-04-25 22:42 UTC, herbig commented on src/components/pages/ManageSigners/RemoveSignerModal.tsx
> +  }, [defaultNonce]);
same comment as above here, and for setting the new one below!

2023-04-25 22:42 UTC, herbig approved these changes
sweet looks good, some simplifications that could be done I think but they don't impact function!

2023-04-26 00:20 UTC, herbig requested changes
Shoot, one other change, @tbwebb22 could these input fields be shortened and the whole thing right aligned

<img width="591" alt="Screenshot 2023-04-25 at 8 18 57 PM" src="https://user-images.githubusercontent.com/384559/234435407-71f569d3-123d-4e5d-9fbb-a8ffb3359eb9.png">

2023-04-26 00:21 UTC, herbig commented
> Shoot, one other change, @tbwebb22 could these input fields be shortened and the whole thing right aligned
> 
> <img alt="Screenshot 2023-04-25 at 8 18 57 PM" width="591" src="https://user-images.githubusercontent.com/384559/234435407-71f569d3-123d-4e5d-9fbb-a8ffb3359eb9.png">

actually scratch that, it's an issue in Send Assets as well, I'm going to look at if I can fix that ha

2023-04-26 00:21 UTC, herbig approved these changes

2023-04-26 13:13 UTC, merged