Refactor azorius contracts
decent-dao/fractal-interface pull request #1152
Opened 2023-05-03 02:23 UTC by Da-Colon

## Description
Hold on to your butts. Azorius Refactor incoming. Combined effort from the entire engineering team. Refactors and updates to newly released `fractal-contracts`

## Notes
- new block timestamp methods `getTimeStamp` and `getEstimatedNumberOfBlocks` to help with converting minutes to blocks per updates to using blocks instead of timestamps in the contracts

## Issue / Notion doc (if applicable)
Closes #952

## Testing
Regression testing! Test anything and everything but if you forget here is a short list:

### Parent DAOs
- create Multisig Parent DAO
- create Azorius Parent DAO
- Delegate Modal 
- Create Azorius Parent (TokenWrapped) DAO
- Wrap Token Modal
- Unwrap Token Modal
- Create Proposal (Multisig Parent)
- Create Proposal (Azorius Parent)
- Create Proposal (Azorius Parent (TokenWrapped))
- Send Assets Modal

### Child DAOs
- view Heirarchy
- create Multisig with Multisig Parent DAO 
- create Multisig with Azorius Parent DAO
- Create Multisig with Azorius Parent (TokenWrapped) DAO
- create Azorius with Azorius Parent DAO
- create Azorius with Multisig Parent DAO
- Create Azorius with Azorius Parent (TokenWrapped) DAO
- Create Azorius (TokenWrapped) with Azorius Parent (TokenWrapped) DAO
- Delegate Modal 
- Create Proposal (Multisig Child)
- Create Proposal (Azorius Child)
- Create Proposal (Azorius Child (TokenWrapped))
- Freeze DAO (Multisig Child)
- Freeze DAO (Azorius Child)
- Freeze DAO (Azorius Child (TokenWrapped))
- Send Assets Modal

## Screenshots (if applicable)

2023-05-03 19:35 UTC, tbwebb22 reviewed
When creating a child token DAO, I'm seeing an execution period field twice, once on the 'Compose Governance' page, and once on the 'Parent Governance' page

2023-05-03 19:43 UTC, herbig requested changes
Hey @Da-Colon I've tested everything except for Freeze and the Azorius proposal lifecycle, here's the major stuff:

- [ ] DAO name doesn't always appear after deploying a new DAO without a refresh (this is definitely preexisting, and explains why our tests are often failing)
- [ ] helperFreezeVotesThreshold doesn't show in both multisig / Azorius subDAO creation (from a multisig parent, Azorius parent works)
- [x] Create proposal doesn't work on a multisig DAO, button enables but clicking it doesn't open Metamask, notification briefly pops up. It works fine on Token voting however.
- [ ] Azorius new proposals don't ever appear in the proposals list (can't test executing them currently)

Once we have proposals list for Azorius displaying I'll go ahead and test proposal states as well.

And is there an easy way to find a subDAO without the DAO hierarchy?

2023-05-04 03:25 UTC, Da-Colon commented on src/hooks/safe/useSafeContracts.ts
>        votesERC20WrapperMasterCopy,
done and done

2023-05-04 03:27 UTC, Da-Colon commented on src/hooks/DAO/useDeployDAO.ts
> +    (daoData: GnosisDAO | AzoriusGovernanceDAO, successCallback: (daoAddress: string) => void) => {
GnosisDAO -> SafeMultisigDAO. I started to do a full search for gnosis. but might need a little more of a delicate search (seperate PR).

2023-05-04 03:30 UTC, Da-Colon commented on src/types/transaction.ts
> +export interface MetaData {
There is actually another type called `ProposalMetaData`. it has similar but different properties. Can probably do a type clean up later

2023-05-05 18:42 UTC, herbig commented on src/models/FreezeGuardTxBuilder.ts
> +            this.parentTokenAddress ?? this.parentAddress, // ParentGnosisSafe or Votes Token
@tbwebb22 does this look good for freeze votes (multisig / azorius) setUp functions?

2023-05-06 13:01 UTC, tbwebb22 commented on src/models/FreezeGuardTxBuilder.ts
> +            this.parentTokenAddress ?? this.parentAddress, // ParentGnosisSafe or Votes Token
Yeah I think everything here looks good. Had to think a bit about that last address param line, but it should work. If the parent DAO does have a token, then we will be deploying the ERC20FreezeVoting and passing to it the token address. If the parent DAO doesn't have a token, then we will be deploying the MultisigFreezeVoting and passing the parent DAO address.

2023-05-09 11:00 UTC, Da-Colon commented
boom, fixed the create proposal by using `useAsyncRetry` to poll `getProposalVotes` until the tx has been mined. 

Based on the fix for `useAsyncRetry` This may have been related to the tests failing as well?

2023-05-09 13:13 UTC, herbig commented on src/components/pages/DaoDashboard/Activities/ActivityFreeze.tsx
> +  freezeVotingContract: freezeVotingContract,
yeah, weird, this is probably a result of doing a rename in VS code, I didn't intend to add that here

2023-05-09 13:15 UTC, herbig commented on src/components/Proposals/ProposalsList.tsx
> +    type === StrategyType.AZORIUS ? true : safe?.owners.includes(user.address || '');
yeah agreed, we have strategy types in Azorius, and these are governance modules

2023-05-09 13:31 UTC, herbig commented on src/types/createDAO.ts
> +  MULTISIG_GOVERNANCE = 'gnosis',
@mudrila it doesn't look like these enum values are necessary for anything, they're not string translation keys, so we should be able to just remove them right?

2023-05-09 13:31 UTC, herbig commented on src/types/createDAO.ts
> +  AZORIUS_GOVERNANCE = 'govToken',
https://github.com/decent-dao/fractal-interface/pull/1152#discussion_r1188604957

2023-05-10 00:01 UTC, merged