Snapshot integration
decent-dao/fractal-interface pull request #1166
Opened 2023-05-15 19:48 UTC by tbwebb22

## Description

## Notes

## Issue / Notion doc (if applicable)

## Testing

## Screenshots (if applicable)

2023-05-17 16:50 UTC, herbig requested changes
Hey @tbwebb22 a couple bugs, I wasn't able to fully test this before getting 500 errors on everything. I don't get the same errors on dev for the DAO I created, so I assume something is up because of the SnapShot changes.

- [x] let's change the hit from fractaldao.eth to decent-dao.eth for now. Hopefully we can scoop that up when it expires, but until we own it I don't want to give the impression that it's our address
- [x] ENS validation seems a bit weird, but I can't pinpoint how. It seems easy to get an invalid address, e.g. asdf.eth worked for me, but asdff.eth didn't
- [x] the SnapShot button / icon should be much smaller and right aligned, as in the designs
- [x] the SnapShot button in DAO homepage links to https://demo.snapshot.org, not the SnapShot space
- [ ] I keep getting "500 Internal Server Error" on pages e.g. https://deploy-preview-1166--fractal-framework-interface-dev.netlify.app/daos/0x059Cb714b9dF7110b40116F5Ec6Cc4DCa8dD8219
- [ ] I set the above DAO to use Aave's SnapShot, but didn't see any of their proposals, before getting the permanent 500 error.

2023-05-17 18:20 UTC, tbwebb22 commented
@herbig Regarding the ENS name validation, it looks to me like asdf.eth is a registered ENS name, while asdff.eth is not. So the behavior you're describing seems right to me.

2023-05-17 18:26 UTC, herbig commented
> @herbig Regarding the ENS name validation, it looks to me like asdf.eth is a registered ENS name, while asdff.eth is not. So the behavior you're describing seems right to me.

Oh shoot, yeah.

2023-05-23 19:37 UTC, herbig commented on src/components/Activity/ActivityCard.tsx
> +                alt="snapshot icon"
we haven't been great about having alt text in the app, but if we do add it we should move this to the translation json files.  Also fine to just remove this for now..

2023-05-23 19:42 UTC, herbig commented on src/components/DaoCreator/formComponents/EstablishEssentials.tsx
> +            id="searchEssentials-snapshotURL"
we have an id for the DAO name, but I'm not really sure why, don't think we need this here

2023-05-23 19:46 UTC, herbig commented on src/components/Proposals/index.tsx
> +  FractalProposalState.CLOSED,
@tbwebb22 should `PENDING` be in these as well?

2023-05-23 19:54 UTC, herbig commented on src/hooks/schemas/common/useValidationAddress.tsx
> +  if (!!ensName && ensName.trim() && ensName.endsWith('.eth') && ensName.length >= 7) {
emojis count as 2 characters I think, so I'm pretty sure `🚀🚀.eth` would pass this.  We might need something to handle emoji counting

2023-05-23 19:58 UTC, herbig commented on src/hooks/schemas/common/useValidationAddress.tsx
> +  if (!!ensName && ensName.trim() && ensName.endsWith('.eth') && ensName.length >= 7) {
maybe ` _.toArray('😁').length` here instead

2023-05-23 20:02 UTC, herbig commented on src/hooks/schemas/common/useValidationAddress.tsx
> +export async function validateENSName({ ensName }: { ensName: string }) {
minor thing but I don't think this needs to be async

2023-05-23 20:04 UTC, herbig commented on src/i18n/locales/en/daoCreate.json
> +    "snapshot": "SnapShot",
the designs had `SnapShot`, but we should lowercase the `shot` for all these strings since that's the proper styling

2023-05-23 20:04 UTC, herbig commented on src/i18n/locales/en/proposal.json
> +    "statePendingTip": "The snapshot proposal voting has not begun yet",
but uppercase Snap for these two usages

2023-05-23 20:15 UTC, herbig requested changes
Looks gooood, a few minor things to check out and we're good to go

2023-05-24 13:31 UTC, tbwebb22 commented on src/components/DaoCreator/formComponents/EstablishEssentials.tsx
> +            id="searchEssentials-snapshotURL"
Cool, removed this

2023-05-24 13:33 UTC, tbwebb22 commented on src/components/Proposals/index.tsx
> +  FractalProposalState.CLOSED,
Ah yes, just added

2023-05-24 13:38 UTC, tbwebb22 commented on src/hooks/schemas/common/useValidationAddress.tsx
> +  if (!!ensName && ensName.trim() && ensName.endsWith('.eth') && ensName.length >= 7) {
Cool, just pushed up fix for this

2023-05-24 13:40 UTC, tbwebb22 commented on src/hooks/schemas/common/useValidationAddress.tsx
> +export async function validateENSName({ ensName }: { ensName: string }) {
Ah good catch, pushed this up

2023-05-24 13:43 UTC, tbwebb22 commented on src/i18n/locales/en/proposal.json
> +    "statePendingTip": "The snapshot proposal voting has not begun yet",
done

2023-05-24 14:41 UTC, herbig approved these changes
⚡️⚡️⚡️

2023-05-24 14:47 UTC, merged