Show token prices
decent-dao/fractal-interface pull request #1382
Opened 2024-02-28 00:06 UTC by mudrila

## Description

This PR implements fetching coin prices from CoinGecko.
The implementation is as dumb as you could only imagine. Probably we could save some requests to putting returned value of `useFormatCoins` into global context - but that might lead us into unnecessary implementation over-engineering (given the fact that we could be migrating to the Safe API Kit once they'll release pricing service anyway).

## Notes

## Issue
Closes #1362 

## Testing
1. Visit some mainnet DAO with bunch of assets
2. Verify that prices for token and total USD is calculated properly

## Screenshots (if applicable)

2024-02-28 14:54 UTC, Da-Colon commented
Not quite working. Went to Decent DAO on mainnet and it is showing only $9,708.66

2024-02-28 15:34 UTC, adamgall commented
Seeing that this implementation contained a CoinGecko API key surprised me, frankly.

I suppose it's been a minute (~2 years) since I last implemented a CoinGecko powered pricing mechanism in a frontend app. Back then, the API was _keyless_ -- totally open without any need for an API key, and rate limiting was simply enforced via IP address. Even still, those limits were quite generous. I believe they allowed something like up to 30 requests per minute. As long as I wrote some smart code to minimize API requests, there was no way any one user was going to hit those limits unless they refreshed the page over and over and over.

I see that this isn't the case any longer, and I wonder if this implementation as it currently stands will work for us.

Here are the problems I see:

- Open API full deprecation
  - According to the [official CoinGecko Reddit account](https://www.reddit.com/r/coingecko/comments/16bc259/comment/kok615p/?utm_source=share&utm_medium=web2x&context=3), the open keyless API should be fully deprecated _as of right now_.
  - In practice this isn't the case as far as I can tell. See: https://api.coingecko.com/api/v3/simple/price?ids=ethereum&vs_currencies=usd
  - There are still IP-based rate limits with this open API. Hit refresh a few times on that above API call and you'll hit it pretty quickly. It's certainly not the "30 per minute" that it used to be.
  - I think it'd be foolish to rely on this open API (without needing a key) being available indefinitely.

- Free API key limits
  - They have a free API tier, which includes a key that [rate limits at 30 calls per minute](https://docs.coingecko.com/v3.0.1/reference/common-errors-rate-limit#rate-limit).
  - This sounds good initially, but important to note that the limits are enforced _at the API key, not the IP address_. So if we bundle this API key in the app, and all Fractal users are relying on this same API key, there's no way in heck this will work for us.

- Paid tier
  - So now we're looking at [CoinGecko's paid tiers](https://www.coingecko.com/en/api/pricing). The cheapest tier still has a rate limit of 500 calls per minute, and I don't think that would hold up either during periods of a couple of DAOs with a couple of proposals active at the same time.
  - If there are a few dozen users hitting the site at the same time, I could quickly see those per-minute rates being hit, because each site load is going to hit a handful of endpoints.
  - Even still, it's just a bad pattern to include this API key in the frontend codebase. Anyone can sniff it and start using it. CoinGecko doesn't allow URL Referral enforcements either.
  - CoinGecko strongly recommends we store this key on a backend server, and proxy requests through it. ([See the Notes section on this page](https://docs.coingecko.com/reference/authentication)).

So where does that leave us? I'm not sure.

- Are there any other open pricing APIs we could use?
- If not
  - Do we simply start paying for a high-volume CoinGecko API tier, stick that API key in our frontend bundle, and hope for the best?
  - Or do we build a backend service (probably a Netlify function cause why not that seems easy enough) to proxy calls through, and importantly _build some persistence into that service_ so we don't need to hammer CoinGecko's API.

2024-03-05 00:20 UTC, adamgall requested changes

2024-03-05 00:29 UTC, adamgall commented on netlify/functions/tokensPrices.mts
Ok I learned what `.mts` is 👍 
https://docs.netlify.com/functions/get-started/?fn-language=ts#create-function-file

2024-03-06 20:57 UTC, adamgall requested changes
What's the easiest way for me to test this code out locally?

2024-03-06 20:57 UTC, adamgall commented on netlify/functions/tokenPrices.mts
> +          store.getWithMetadata(tokenAddress, {
Why `getWithMetadata`, and not simply `get`?

2024-03-06 20:57 UTC, adamgall commented on netlify/functions/tokenPrices.mts
> +  const tokens = tokensString.split(',');
We should do some validation that these addresses are valid (using ethers.js or viem `isAddress` is fine), before calling into our store and/or calling out to CoinGecko.

2024-03-06 21:09 UTC, adamgall commented on netlify/functions/tokenPrices.mts
> +          store.getWithMetadata(tokenAddress, {
Oh I get it, the expiration value is stored in `metadata`.

2024-03-07 06:22 UTC, adamgall commented
I've just pushed up a pretty major refactor. Some things to note:

- Need two new local environment variables:
  - `TOKEN_PRICE_VALID_CACHE_MINUTES="5" # or however long you want`
  - `TOKEN_PRICE_INVALID_CACHE_MINUTES="10" # or however long you want`
- Heavily optimized to not bombard CoinGecko
  - Caches valid prices in blob storage (see `TOKEN_PRICE_VALID_CACHE_MINUTES`)
  - Don't throw error when query param is not a valid address, just skip it.
  - Don't send "ethereum" string as a token to CG token API endpoint.
  - Return ethereum and token price in response immediately if all data can be found in cache.
  - Add entries to blob store (with long expiration, see `TOKEN_PRICE_INVALID_CACHE_MINUTES`) for token addresses that CoinGecko doesn't track, or doesn't have USD price for, to avoid constantly asking about these tokens
  - Netlify function will always return response consisting of requested token addresses, even if all of the prices are "0" (in worst case)
- Frontend Treasury page use some more optimizing for when CoinGecko fails / hits rate limits. The backend currently works well and as expected (by returning cached data, even if it might be stale), but frontend throws an error toast. I think maybe it shouldn't throw an error toast.

2024-03-07 09:02 UTC, tomstuart123 approved these changes

2024-03-07 13:28 UTC, adamgall requested changes
One more thing I just thought of -- we should namespace these blob keys to include the network.

2024-03-07 15:58 UTC, adamgall requested changes

2024-03-07 15:58 UTC, adamgall commented on netlify/functions/tokenPrices.mts
> +  const store = getStore(`${networkParam}-token-prices`);
I don't think we should be introducing multiple stores here. Please just keep one single `token-prices` store.

Each KV pair should have that chainspacing on it: `${networkId}/${tokenAddress}`

2024-03-07 18:09 UTC, adamgall requested changes

2024-03-07 18:09 UTC, adamgall commented on src/providers/App/hooks/usePriceAPI.ts
> +            toast.warning(t('tokenPriceFetchingError'));
Let's not show a toast error _if we receive a response from the API_.

We _should_ show a toast error _if the API service itself is down_. Would that happen down between lines 45-46?

2024-03-07 19:58 UTC, adamgall reviewed
Just one thing that seems off to me.

2024-03-07 19:58 UTC, adamgall commented on netlify/functions/tokenPrices.mts
> +    .filter(tokenPrice => tokenPrice.metadata.fetched > config.now + config.cacheTime)
To get expired addresses, wouldn't we want it to be "fetched + cache < now"?

2024-03-07 20:19 UTC, adamgall requested changes
I'm testing this locally, and it's not working. I have a value of "5" (minutes) set in my env var, but putting in a console.log right before the fetch to coingecko shows that it's making that request every time the frontend calls the API (every ~20 seconds).

2024-03-07 20:19 UTC, adamgall commented on netlify/functions/tokenPrices.mts
> +    .filter(tokenPrice => tokenPrice.metadata.fetched + config.cacheTime < config.now)
Perhaps we should be converting this `cacheTime` from "minutes" to "seconds" heh

2024-03-07 20:27 UTC, adamgall commented on netlify/functions/tokenPrices.mts
> +    .filter(tokenPrice => tokenPrice.metadata.fetched + config.cacheTime < config.now)
`config.now` gives seconds (https://github.com/decent-dao/fractal-interface/pull/1382/files#diff-284b3930e569c4259e85b685d36c139226ef2a210eaeb25f614b752fd1b2e910R197)

The env var is called `TOKEN_PRICE_CACHE_INTERVAL_MINUTES`, which specifies that it should be `MINUTES`. Minutes are a lot easier to reason about that milliseconds, when setting configs in an env var.

I think the cleaner solution is to convert the value to seconds when setting the config property here: https://github.com/decent-dao/fractal-interface/pull/1382/files#diff-284b3930e569c4259e85b685d36c139226ef2a210eaeb25f614b752fd1b2e910R198
```ts
const cacheTime = parseInt(process.env.TOKEN_PRICE_CACHE_INTERVAL_MINUTES) * 60
```

2024-03-07 20:45 UTC, adamgall commented on netlify/functions/tokenPrices.mts
> +    .filter(tokenPrice => tokenPrice.metadata.fetched + config.cacheTime < config.now)
@mudrila i just pushed up the fix, no worries

2024-03-07 20:47 UTC, adamgall approved these changes
Let's go!

2024-03-07 21:14 UTC, merged