[ENCHANCEMENT] Request Relief 02
decent-dao/fractal-interface pull request #1383
Opened 2024-02-28 03:32 UTC by Da-Colon

## Description
This took me longer than I expected. The original goal of this PR was to clean up some of the redundancy in the master copy lookup and caching. While doing this I uncovered a loading issue. I'll go through a code review and talk about the specific changes as I only have an assumption on why my changes caused this issue to pop up.

### Issue Arises
So after create `useMasterCopy` and updating all the places that use the same pattern. I started noticing that the original decrease was erased and requests increased. After several console logs through out the loading places that were loading either out of sequence or now causing re-renders that were not being revealed before as the previous RPC request held these things up.

### The Fix
Two Major Points:

- `useUpdateTimer` in `useProposals`
When loading a Azorius DAO (pre-fix) it would for a moment load as a Multisig DAO, which caused me to notice that the setMethodInterval was firing in the background. This was also happening after switching from viewing one to another via links (Hierarchy Page and parent-safe link).

- `useGovernanceContracts`
This is where the main fix was located. So this is where the assuming comes in. I assume because of the app now loading faster some of the band-aids like this complicated loadkey is no longer needed here. removing this and cleaning up the logic a big (will explain below) continues the improvements of the loading of the app.

## Notes

## Issue

## Testing

## Screenshots (if applicable)

2024-02-28 03:44 UTC, Da-Colon commented on app/layout.tsx
> -
Left over from the Providers move refactor. This was being init twice.

2024-02-28 03:44 UTC, Da-Colon commented on src/components/ui/menus/ManageDAO/ManageDAOMenu.tsx
Swap out for `useMasterCopy` implementation

2024-02-28 03:44 UTC, Da-Colon commented on src/hooks/DAO/loaders/useFractalGuardContracts.ts
Swap out for `useMasterCopy` implementation

2024-02-28 03:44 UTC, Da-Colon commented on src/hooks/DAO/loaders/useFractalModules.ts
Swap out for `useMasterCopy` implementation

2024-02-28 03:44 UTC, Da-Colon commented on src/hooks/DAO/loaders/useGovernanceContracts.ts
> -      setLastChainId(chainId);
Wasn't really sure what setLastChainId was doing here. I cleaned up this state and seems to be working as expected

2024-02-28 03:44 UTC, Da-Colon commented on src/hooks/DAO/loaders/useGovernanceContracts.ts
> +      currentValidAddress.current = daoAddress;
Moving this value outside of being set inside of the `loadGovernanceContracts()` callback all seem to help the multiple loads

2024-02-28 15:44 UTC, adamgall commented on src/hooks/DAO/loaders/useGovernanceContracts.ts
> -      setLastChainId(chainId);
Was this perhaps being used to invalidate state when chains are switched?

2024-02-28 18:41 UTC, Da-Colon commented on src/hooks/DAO/loaders/useGovernanceContracts.ts
> -      setLastChainId(chainId);
maybe but when chain is changed the entire DAO is unloaded anyway and the "This DAO doesn't exist on [Network]" with a reload button shows up

2024-02-28 20:41 UTC, adamgall commented on src/hooks/DAO/loaders/useGovernanceContracts.ts
> -      setLastChainId(chainId);
Word, that makes sense.

2024-02-29 19:17 UTC, adamgall commented
My testing:

- Attempting to load Azorius DAO
  - No wallet connected
    - [x] via Search
    - [x] via Reload
    - [ ] via Hierarchy Page
  - Frame wallet connected via Browser Wallet
    - [x] via Search
    - [x] via Reload
    - [ ] via Hierarchy Page
  - Safe connected via WalletConnect
    - [x] via Search
    - [x] via Reload
    - [ ] via Hierarchy Page
- Attempting to load Multisig DAO
  - No wallet connected
    - [x] via Search
    - [x] via Reload
    - [ ] via Hierarchy Page
  - Frame wallet connected via Browser Wallet
    - [x] via Search
    - [x] via Reload
    - [ ] via Hierarchy Page
  - Safe connected via WalletConnect
    - [x] via Search
    - [x] via Reload
    - [ ] via Hierarchy Page

@Da-Colon @tomstuart123 do you have any sepolia daos offhand that have some hierarchy set up that I can use for testing?

2024-02-29 19:44 UTC, adamgall requested changes
I'm seeing some strange behavior when clicking in and out of the parent/child DAOs. Some state is hanging around between Safes. Sometimes the Child (Multisig) presents itself as Token Voting. Sometimes the Parent shows as having the Execution time of the Child. Talking with David now, he's on it 💪

2024-03-01 00:27 UTC, Da-Colon commented
@adamgall looks like we are good to go for another round of testing. Sorry for this misfire. The 'reload' screen issue that pops up every once in a while seems to be a problem with some state somewhere in `VoteContext`. Gonna see if I can locate it. 

This same component seems to show up alot with the 429 errors too so gonna take a closer look.

2024-03-01 17:01 UTC, merged