Replace NextJS with `Vite`
decent-dao/fractal-interface pull request #1431
Opened 2024-03-11 17:02 UTC by Da-Colon

- remove next config and types
- Add vite and react-router-dom
- Add vite config
- Create index.html (update with metadata from next/head)
- Create main.tsx (entry point)
- Add CSS imports, providers to entry point
- Create router.tsx to handle page router
- Add DAOController and Layout element to Router
- Add Pages to Router (A few index -> default component name file changes)
- Replace next's Script with custom hook
- Replace next Link Component with React Router Link
- Replace process.env -> import.meta with update ENV names
- Replace next/image component with Chakra Image component
- Replace next/router push instances with `useNavigate`
- Replace package.json next scripts with vite runner

## Testing
Note: Deployed preview will not work.

I deployed this branch manually on netlify. Here is the link: https://test-vite-fractalframework.netlify.app/

2024-03-11 17:14 UTC, Da-Colon reviewed
Test everything workflow you can think of. Should only notice the app being smoother everywhere. report any weirdness and I'll look into it.

2024-03-11 17:14 UTC, Da-Colon commented on src/router.tsx
This was surprisingly pretty straight forward to create. Just takes the 'index' of each page folder formally the `page.tsx` and place as the element.

2024-03-11 17:14 UTC, Da-Colon commented on .env
Don't forget to update local env files as well from `NEXT_PUBLIC_` -> `VITE_APP_`

2024-03-11 17:14 UTC, Da-Colon commented on src/hooks/utils/useETHLizardsScript.tsx
I cannot test this since Goerli is no longer supported. Should we just remove?

2024-03-11 17:14 UTC, Da-Colon commented on vite.config.ts
So far in my testing, all I've had to update here is the plugin for nodepolyfils. This was fixing a 'process is not defined' and 'global is not defined' errors when setting up

2024-03-11 17:41 UTC, Da-Colon commented on src/components/pages/DaoSettings/components/Metadata/index.tsx
> +import { useNavigate } from 'react-router-dom';
o weird, My IDE should do it on save. but i'll run the link:fix locally

2024-03-11 17:42 UTC, Da-Colon commented on src/pages/daos/[daoAddress]/proposal-templates/new/index.tsx
> +  let [searchParams] = useSearchParams();
docs shows let? https://reactrouter.com/en/main/hooks/use-search-params.

2024-03-11 17:51 UTC, Da-Colon commented on src/components/pages/DaoSettings/components/Metadata/index.tsx
> +import { useNavigate } from 'react-router-dom';
Ah it was broken as it was still using a next dependency good catch

2024-03-11 18:05 UTC, Da-Colon commented
@mudrila All your comments have been address, sir. (+some)

2024-03-11 18:35 UTC, adamgall requested changes
Can we use the new `VITE_APP_NAME` env var in all the places in the codebase that we were originally using the `APP_NAME` constant defined in `src/constants/common.ts`? And then, remove that constant from `common.ts`?

2024-03-11 18:35 UTC, adamgall commented on src/vite-env.d.ts
At first I was like "we're missing entries for `TOKEN_PRICE_CACHE_INTERVAL_MINUTES` and `COINGECKO_API_KEY`, but actually those are probably not in here on purpose?? Does the netlify function live outside of Next/Vite?

2024-03-11 18:35 UTC, adamgall commented on index.html
> +      content={APP_NAME}
Can we use `VITE_APP_NAME` here?

2024-03-11 18:35 UTC, adamgall commented on index.html
> +      content={APP_NAME}
Can we use `VITE_APP_NAME` here?

2024-03-11 18:35 UTC, adamgall commented on index.html
> +      content={APP_NAME}
Can we use `VITE_APP_NAME` here?

2024-03-11 18:35 UTC, adamgall commented on src/pages/DAOController.tsx
>  import { APP_NAME } from '../constants/common';
Can we remove this import?

2024-03-11 18:35 UTC, adamgall commented on src/pages/DAOController.tsx
>        <title>{node?.daoName ? `${node.daoName} | ${APP_NAME}` : APP_NAME}</title>
Can we use `VITE_APP_NAME` here?

2024-03-11 18:35 UTC, adamgall commented on src/providers/NetworkConfig/rainbow-kit.config.ts
>  const defaultWallets = [injectedWallet({ chains }), coinbaseWallet({ appName: APP_NAME, chains })];
Can we use `VITE_APP_NAME` here?

2024-03-11 18:44 UTC, adamgall requested changes
The deployed site doesn't load if you refresh the page on any non-root URL.

This is known and expected.

There's a simple fix for Netlify hosting, which allows us to keep the `BrowserRouter` and not need to switch to a `HashRouter`.

See this commit from the `fractal-interface-2` repo: https://github.com/decent-dao/fractal-interface-2/commit/6bc770221a739d91e5b7ea052f48b4e7d8cf819a

2024-03-11 18:47 UTC, Da-Colon commented on src/vite-env.d.ts
thats correct, they live outside of it

2024-03-11 18:47 UTC, Da-Colon commented on index.html
> +      content={APP_NAME}
Good call on it

2024-03-11 18:58 UTC, Da-Colon commented
@adamgall added your updates. I also updated the link to deployed test site (updated PR description too). https://test-vite-fractalframework.netlify.app/

2024-03-11 20:43 UTC, adamgall commented on global.d.ts
Do we still need this, considering https://github.com/decent-dao/fractal-interface/pull/1431#discussion_r1520138239

2024-03-11 20:45 UTC, Da-Colon commented on global.d.ts
good call...deleted

2024-03-11 20:52 UTC, adamgall requested changes

2024-03-11 20:52 UTC, adamgall commented on .gitignore
Could probably delete the `next` specific stuff out of here. Also, please move that `./dist` line up into the `# production` section of this file (and you don't need the `.` in `./dist`)

2024-03-11 20:54 UTC, adamgall requested changes

2024-03-11 20:54 UTC, adamgall commented on package.json
> +    "lint": "eslint . --ext .ts,.tsx --fix",
Please create a separate script for this. Right now there's a Github Action that runs this command, and we don't want that runner to be making any changes to the repo. It should just be succeeding or failing based on whether this script exits with a error or not.

2024-03-11 21:09 UTC, adamgall commented on index.html
> +      content="Are you outgrowing your Multisig? Fractal extends Safe treasuries into on-chain hierarchies of permissions, token flows, and governance."
Blah, I think that either this should be in an env var, or we just hardcode "Fractal" back into the places where we are using VITE_APP_NAME.

Why have some of this metadata hardcoded and others controlled by environment?

But whatever, it's fine for now.

2024-03-11 21:11 UTC, adamgall commented on vite.config.mts
> +    port: 3000,
@Da-Colon just wondering, does it actually matter to force this to run on 3000? THIS AIN'T A NEXT APP ANY LONGER BOYYEEEEEE

2024-03-11 21:12 UTC, Da-Colon commented on vite.config.mts
> +    port: 3000,
lol fair. more for me and my history autocomplete :D

2024-03-11 21:21 UTC, adamgall commented on src/metadata/lizzardsDAO/index.ts
Does this whole file and associated other lizard-specific files get removed too? I'm not sure where we stand on that....

2024-03-11 21:24 UTC, adamgall requested changes

2024-03-11 21:24 UTC, adamgall commented on src/pages/daos/[daoAddress]/proposal-templates/new/index.tsx
> +  let [searchParams] = useSearchParams();
Yeah but, please make it a `const` cause we're not changing it.

2024-03-11 21:26 UTC, Da-Colon commented on src/metadata/lizzardsDAO/index.ts
@mudrila @tomstuart123 ^^^^

2024-03-11 21:26 UTC, adamgall approved these changes

2024-03-11 21:27 UTC, Da-Colon commented on vite.config.mts
> +    port: 3000,
I don't really have a preference. btw we can definately just go with the defaults of vite.

2024-03-11 21:27 UTC, adamgall commented on src/metadata/lizzardsDAO/index.ts
The export from this file isn't being consumed anywhere, so from a codebase perspective, it's safe to delete this file. I wonder if we should hold on to it for future use though...

2024-03-11 21:29 UTC, adamgall commented on vite.config.mts
> +    port: 3000,
My preference is that we just go with the vite default

2024-03-12 21:03 UTC, adamgall approved these changes

2024-03-12 21:57 UTC, adamgall commented
@Da-Colon can you explain the difference between `chakra`'s `<Link>` component and `react-router-dom`'s `<Link>` component? There seems to be extensive use of both in the codebase, and I'm not sure what the distinction is between them. 

This commit has me scratching my head... why change the `href` to `to` on _these_ `chakra <Link>`'s and not _others_?

2024-03-12 22:12 UTC, Da-Colon commented
> @Da-Colon can you explain the difference between `chakra`'s `<Link>` component and `react-router-dom`'s `<Link>` component? There seems to be extensive use of both in the codebase, and I'm not sure what the distinction is between them.
> 
> This commit has me scratching my head... why change the `href` to `to` on _these_ `chakra <Link>`'s and not _others_?

@adamgall 

Chakra-UI's Link basically is a stylable `<a>` element
React-Router's Link adds React Router's functionality to the `<a>` element. https://reactrouter.com/en/main/components/link

![image](https://github.com/decent-dao/fractal-interface/assets/38386583/5abc836d-032a-4533-ae37-a00a41cc4ba3)

Switching to `to` property for these allowed it to pick up that we are just navigating to a different page rather than reloading the document

---

As far as the various uses. Looking through how I've updated it.

React-Router's `Link` is used when the navigation is internal

Chakra-UI's `Link` is used when navigation is external or needs to be styled.

In the case of needing to be styled and internal. Chakra's `as` property is used. This allows Chakra's styling ability to be used along side React-Router's properties (why you saw these switch to `to` property as well)

2024-03-13 16:39 UTC, merged

2024-03-19 17:51 UTC, tomstuart123 commented
So I think this is good to go

Successful Test cases for both multisig + token dao
- Create a DAO 
- delegate (token only)
- vote / sign
- wait for timelock
- execute

these were for subdao, token send and create a proposal flow

just a note - I did have old issues reccur with subdao activity but david pointed me to a seperate PR for that - https://discord.com/channels/839548879216181309/1174434485043998860/1219698481091055699

final note - I did get this error that I had never seen before. Hard to replicate
<img width="793" alt="Screenshot 2024-03-19 at 17 50 29" src="https://github.com/decentdao/fractal-interface/assets/31554133/683e03e2-8f99-4e9c-9ba8-3b20eebf510d">

this was the only new thing and happened pretty rarely. I think we're good to go on this

2024-03-19 17:55 UTC, Da-Colon commented
New Error you are experiencing is this?

https://github.com/orgs/decentdao/projects/32/views/3?pane=issue&itemId=56621736