Governance edit
decent-dao/fractal-interface pull request #330
Opened 2022-06-09 22:37 UTC by christopherdancy

PR Intentions 
Issue #308 intention was to make gov details on create DAO editable. Included in this PR
1. proposalThreshold
2. quorum
3. executionDelay
4. lateQuorumExecution
5. voteStartDelay
6. votingPeriod
Are now all editable fields with accompanying helper text and recommendations.

<img width="883" alt="image" src="https://user-images.githubusercontent.com/69045872/172956527-b6d46110-10d5-4fab-a35f-0f057cc73b38.png">

Each field is editable and will result in a governor module being setup to the users specifications

2022-06-09 22:47 UTC, christopherdancy commented
added easy to read recommend text
<img width="883" alt="image" src="https://user-images.githubusercontent.com/69045872/172957743-1c1aa870-e761-4025-86b9-41e436c75fc4.png">

2022-06-10 06:44 UTC, adamgall requested changes

2022-06-10 06:44 UTC, adamgall commented on src/hooks/useDeployDAO.ts
> +          abiCoder.encode(['uint256'], [BigNumber.from(votingPeriod)]), // Todo: change votingPeriod back to 45818 blocks (1 week)
Small nitpick but can you please remove the `Todo:` comments from these lines?

2022-06-10 06:45 UTC, adamgall commented
I'm able to enter non-numbers into these inputs, which seems wrong.

![Screen Shot 2022-06-10 at 2 45 39 AM](https://user-images.githubusercontent.com/706929/173006838-decbf63b-94df-40f4-a342-ccd53fc53b46.png)

2022-06-10 06:47 UTC, adamgall submitted a review, later dismissed
I'm able to enter non-numbers into these inputs, which seems wrong.

![173006838-decbf63b-94df-40f4-a342-ccd53fc53b46](https://user-images.githubusercontent.com/706929/173007008-e74d435f-2bc1-40c4-a942-e47b7f93ecdd.png)

2022-06-10 12:24 UTC, Da-Colon commented
@christopherdancy can we split up some of the input boxes into sections with a title? something like this page? @dannydecent might could use your input on this. 
 
![image](https://user-images.githubusercontent.com/38386583/173063347-c04e571b-fd21-4d2c-965a-51611fe1ae0b.png)

2022-06-10 12:36 UTC, Da-Colon commented
Also we probably don't need the lock icon in the title any more
![image](https://user-images.githubusercontent.com/38386583/173065497-aebd3a1d-26a0-4ab5-bba4-a8c303044897.png)

2022-06-10 17:08 UTC, Da-Colon reviewed
Other than these large amounts of props being passed into components. Everything seems to working well and looks great. I made a card to relook at this part of the code to see if we can reduce the amount of props, but not worried about messing with it now, as next round designs may change some of this anyway.

Functionally, everything seems to work well. Have you tested that these new values are taking affect as intended if changed? I have seeing the delayed vote working well. Has the other params been tested as well? @christopherdancy

2022-06-10 17:25 UTC, Da-Colon approved these changes
Card is being created for "Tokens Required" workflow on create proposal. but everything here LGTM #338

2022-06-10 17:40 UTC, merged