Update types
decent-dao/fractal-interface pull request #365
Opened 2022-06-30 14:21 UTC by tbwebb22

This PR: 
 - Updates the typechain-types to the newest versions of the contracts deployed on testnets
 - Updates the supported test networks to be Goerli and Sepolia
 - Updates all contracts addresses to the newly deployed contracts
 - Removes the token supply field from the DAO Creation process (the token factory no longer receives token supply as a parameter)
 - Updates the useCreateDAODataCreator hook to support the new Metafactory interface. This includes creating "salt" within this hook for the new CREATE2 pattern used in the factories.

2022-06-30 16:14 UTC, adamgall requested changes

2022-06-30 16:14 UTC, adamgall commented on .eslintrc.json
> +                "endOfLine": "auto",
what does this change do? @Da-Colon do you have any comments here

2022-06-30 16:14 UTC, adamgall commented on src/hooks/useCreateDAODataCreator.ts
> +      // todo: update salt to a more random value
Any reason why you can't just do that right now?

https://developer.mozilla.org/en-US/docs/Web/API/Crypto/getRandomValues

2022-06-30 16:14 UTC, adamgall commented on src/hooks/useCreateDAODataCreator.ts
> +          [account, chainId, daoAndAccessControlSalt]
Is this `account` value going to be correct when this hook is being executed to create a subDAO -- in which the proposal executor (`tx.origin`) can't be known?

2022-06-30 16:14 UTC, adamgall commented on src/hooks/useCreateDAODataCreator.ts
> +          [account, chainId, daoAndAccessControlSalt]
Same comment as above.

2022-06-30 16:14 UTC, adamgall commented on src/hooks/useCreateDAODataCreator.ts
> +          [account, chainId, treasurySalt]
Same comment as above.

2022-06-30 16:14 UTC, adamgall commented on src/hooks/useCreateDAODataCreator.ts
> +          [account, chainId, tokenSalt]
Same comment as above.

2022-06-30 16:14 UTC, adamgall commented on src/hooks/useCreateDAODataCreator.ts
> +          [account, chainId, governorAndTimelockSalt]
Same comment as above.

2022-06-30 16:14 UTC, adamgall commented on src/hooks/useCreateDAODataCreator.ts
> +          [account, chainId, governorAndTimelockSalt]
Same comment as above.

2022-06-30 18:30 UTC, tbwebb22 commented on .eslintrc.json
> +                "endOfLine": "auto",
This resolves an eslint issue I was having due to a difference between how Mac & Windows handle end of line characters. David and I worked through it together yesterday and this solution works.

2022-07-12 19:27 UTC, tbwebb22 commented on src/hooks/useCreateDAODataCreator.ts
> +      // todo: update salt to a more random value
Addressed in recent commits

2022-07-12 19:27 UTC, tbwebb22 commented on src/hooks/useCreateDAODataCreator.ts
> +          [account, chainId, daoAndAccessControlSalt]
This was resolved by deploying new contracts that don't use tx.origin in the salt. They now use msg.sender and the creator address to generate the create2 salt.

2022-07-13 14:38 UTC, Da-Colon approved these changes
Everything LGTM, no issues creating a DAO

2022-07-13 14:38 UTC, Da-Colon commented on .env
> -REACT_APP_LOCAL_TIMELOCKUPGRADEABLE_ADDRESS='{ "address": "0x8A791620dd6260079BF849Dc5567aDC3F2FdC318" }'
Can you note these changes to the `env` variables in description along with the switch to Goerli. On merge this will need to be updated in netlify.

2022-07-13 19:51 UTC, christopherdancy approved these changes
LGTM - You are good to merge taylor - I do want to point to the fact that the accessControl or the interface that is setting the access control has a bug somewhere. This should be where our attention is placed for the next scope of work.

2022-07-14 13:22 UTC, merged