Erc721
decent-dao/fractal-interface pull request #366
Opened 2022-07-01 20:54 UTC by christopherdancy

This PR handles the following
1. Listen for ERC721 deposits / withdraws
2. Update treasury state based on ERC721 deposits / withdraws
3. Create a second UI box which displays treasury Assets / ERC721
4. Create an href for the tokenURI

Screen shots showing the different states a treasury can be in 
1. Token Assets 
![image](https://user-images.githubusercontent.com/69045872/176966526-0732090f-b1ab-4c60-80f1-99e71e741328.png)
2. NFT Assets
![image](https://user-images.githubusercontent.com/69045872/176966592-49d8d01c-70ce-4d46-96d0-e7c8d298699f.png)
3. Both 
![image](https://user-images.githubusercontent.com/69045872/176966617-52594322-134c-4aea-ac12-471e43f73da1.png)

Steps to recreate
1. Create A DAO
2. Etherscan Treasury - Verify Proxy
3. Approve Treasury - via NFT / Token
4. Call Deposit(?TokenType) - watch magic happen

2022-07-05 14:02 UTC, adamgall requested changes
Main theme of my review here is to separate fungible and non-fungible logic back in the data layer, perhaps by renaming the `useTreasuryAssets` hook to `useTreasuryAssetsFungible` and creating a new `useTreasuryAssetsNonFungible` hook. Then just create a new parameter in the global treasury state to hold those "non fungible" datas.

2022-07-05 14:02 UTC, adamgall commented on src/pages/Treasury/index.tsx
> +          ).length && (
I think the UI layer here is not really a great place to "split" assets up between fungible/non-fungible. Probably better to have these assets split up back in the data layer, which is what I was trying to get at in my previous couple of comments.

2022-07-05 14:07 UTC, christopherdancy commented
@adamgall This is not completed. I will address before final product.

2022-07-06 07:53 UTC, christopherdancy commented
Leaving a comment here - @adamgall @Da-Colon - There seems to be an issue with assigning roles to actions. This is confirmed on etherscan. Will move this to a seperate issue.

2022-07-06 12:26 UTC, adamgall commented on src/contexts/daoData/daoData.ts
> +      treasuryAssetsNonFungible: TreasuryAssetNonFungible[];
yes yes this is nice

2022-07-06 12:45 UTC, adamgall requested changes
So close! Just one requested change at the place where NFT links are generated

2022-07-06 12:45 UTC, adamgall commented on src/pages/Treasury/index.tsx
> +                </a>
I question whether or not we should even have this part in here for now.

This snippet is nowhere near production ready. for example:

- why prefixing the `tokenURI` with a static `https://`? Don't `tokenURI`s typically include the http schema already?
- this doesn't work when the `tokenURI` is an IPFS hash
- this seems like it'll only link to the token's metadata object, not the art/image itself. Maybe that's intended.

We'd probably want to use a specific library for this that covers all the edge cases for "displaying NFTs", something like [useNFT](https://github.com/spectrexyz/use-nft).

In the meantime, might be safest to avoid all the edge cases entirely by not even trying to link to anything.

Or maybe!, for now, we just link to the NFT on Etherscan:

`https://[network.]etherscan.io/[tokenAddress]/[tokenId]`

e.g.: https://etherscan.io/nft/0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d/1512

(there's already a hook to help generate etherscan links depending on the connected network. perhaps build upon that to make this NFT link easy to generate)

2022-07-06 13:25 UTC, christopherdancy commented on src/pages/Treasury/index.tsx
> +                </a>
that is a dope idea

2022-07-06 14:55 UTC, adamgall submitted a review, later dismissed
Approving, but asking you to create an issue to clean up some tech debt that's being merged in this PR.

2022-07-07 14:16 UTC, adamgall requested changes
These latest changes don't really solve the issue that we talked about yesterday, which is that callers can pass data into the component and receive an invalid link.

The base `EtherscanLink` component is still callable, and can still be called in a way that produces an invalid link.

2022-07-08 14:05 UTC, adamgall approved these changes
Looking good!

2022-07-08 14:35 UTC, merged