Parent Token Mirroring
decent-dao/fractal-interface pull request #385
Opened 2022-07-27 14:21 UTC by christopherdancy

**PR Explained**
This PR allows a parent daos token allocations to be mirrored to a child daos token allocation.

**Proposed Changes**
- When creating a subdao - a user has the ability to specify how many of the child tokens should be allocated to parent token holders.
- If there is an allocation present - the useCreateDAODataCreator.ts hook deploys a claimSubsidiary contract from the claimFactory, adds the parentAllocationAmount to the tokenAllocations array, send the allocated amount to the metafactory, and calls init on the claimSubsidiary contract by taking a snapshot of the current balance and sending the tokens to the claim contract.
- Create a use claimSubsidiary hook to display the contract address to the user in dao details.
- Allocation validation that should be <= totalSupply  

**Testing Purposes**
1. Should not show parentAllocationAmount when creating a rootDAO
![image](https://user-images.githubusercontent.com/69045872/181268159-845350a5-9437-4bf3-bbb3-476391d90af1.png)

2. Should fail with proposalAmount + allocations > total supply
![image](https://user-images.githubusercontent.com/69045872/181268774-ae92f025-6307-4d2b-bc6a-491281099d94.png)

3. Should be able to execute transaction
![image](https://user-images.githubusercontent.com/69045872/181269710-933766b7-1cd1-41ba-bbde-3920435e5901.png)

4. Shows Child DAO
![image](https://user-images.githubusercontent.com/69045872/181269975-0e6c0b3a-90c1-47c0-a505-32c52ef3d4b5.png)

5. Shows claimSub on Child DAO
![image](https://user-images.githubusercontent.com/69045872/181270343-9b19b19a-7c51-412e-9781-84dbc778bd46.png)

6. Everyone has the correct amount of tokens - Claim Sub has correct tokens
![image](https://user-images.githubusercontent.com/69045872/181271113-c27617b2-083e-45e9-abe2-08cb114f4f30.png)

7. Parent token holder can claim correct amount of tokens
![image](https://user-images.githubusercontent.com/69045872/181271361-0c1e52a9-0fa1-4253-b509-fad8d64c2c70.png)

2022-07-27 17:33 UTC, Da-Colon requested changes

2022-07-27 17:33 UTC, Da-Colon commented on src/components/Dao/ClaimToken.tsx
> +          )} ${symbol} available to claim!`}
Can we move this formatting to outside the HTML?

```tsx
// change the name
const formattedValue = useMemo(() => ethers.utils.formatUnits(
            userClaimAmount.toString(),
            decimals
          ), [userClaimAmount, decimals])
```

or move it to the hook?

2022-07-27 17:33 UTC, Da-Colon commented on src/components/DaoCreator/TokenAllocations.tsx
>      }
```tsx
if (Number(supply)) {
  // no DAO token allocation with no parent allocations
  if (Number(totalAllocated) && !Number(parentAllocationAmount)) {
    setAmountError(Number(supply) < totalAllocated)
  // parent tokens allocated but no DAO token allocation
} else if (!Number(totalAllocated) && Number(parentAllocationAmount)) {
  setAmountError(Number(supply) < Number(parentAllocationAmount))
  // parent tokens allocated with DAO token allocation
  } else if (Number(totalAllocated) && Number(parentAllocationAmount)) {
    setAmountError(supply) < totalAllocated + Number(parentAllocationAmount))
  } else {
  // no allocation set amount error to false
    setAmountError(false)
  }
}
```

2022-07-27 17:33 UTC, Da-Colon commented on src/components/DaoCreator/provider/hooks/useNextDisabled.ts
> -            state.govToken.tokenSupply === undefined
`state.govToken.tokenSupply === undefined` -> `!state.govToken.tokenSupply`
`state.govToken.tokenAllocations` -> `!state.govToken.tokenAllocations`

2022-07-27 17:47 UTC, christopherdancy commented on src/components/Dao/ClaimToken.tsx
> +          )} ${symbol} available to claim!`}
Decided not to useMemo since it was being rendered conditionally. Also - decided not to render in hook since this is not the current pattern within daoData.ts.

2022-07-28 00:27 UTC, christopherdancy commented
Looks like everything is good to go? Should we merge or are we doing some more QA?

2022-07-28 04:34 UTC, Da-Colon commented on src/components/Dao/ClaimToken.tsx
> +  }
I did end up moving to the `useMemo` hook by updating the conditional to check for this value to be defined here.

2022-07-28 13:16 UTC, Da-Colon commented
So not quite ready yet.

![image](https://user-images.githubusercontent.com/38386583/181513659-fc47674c-832d-43ba-84e6-c389672d91ac.png)

![image](https://user-images.githubusercontent.com/38386583/181513746-2f7084f1-d472-4cd1-8113-65771e7e7f8e.png)

So Context: I set the Parent DAO allocation to 50/100 tokens.

There is only 1 member of parent DAO (me). So all 50 of these should be set to me to claim yeah? 10 tokens are missing out in the either somewhere? It's not in either Treasury? @christopherdancy @tbwebb22

2022-07-28 14:08 UTC, Da-Colon approved these changes
The workflow is functioning as expected. A issue will be created to discuss and handle parent treasury claiming

2022-07-28 14:45 UTC, tbwebb22 commented
Just completed some QA as well, looking good to me.

2022-07-28 15:26 UTC, merged