Updates Gnosis Form
decent-dao/fractal-interface pull request #434
Opened 2022-08-21 02:32 UTC by Da-Colon

## Overview

Small Update to the UI/UX of the Gnosis Config Form. Instead of click an 'add' button, the user enters a number in the field

## Screenshot
![image](https://user-images.githubusercontent.com/38386583/185772760-8d3956ff-d5ea-4d2d-bdfd-8068d088d6ab.png)

closes #426

2022-08-21 03:59 UTC, adamgall requested changes
This code must have been added in the original Gnosis UI PR, but there's a typo in the error displayed when Signature Threshold is higher than signers:

"Threshold is to high"

to -> too

edit: this is fixed, thanks

2022-08-21 04:01 UTC, adamgall requested changes
You can get into an invalid state ("Deploy" button enabled), when entering a number into "Signers" (like 3), then deleting it (which turns it back into 0), then filling out addresses in the three address inputs (which stuck around, despite there being 0 signers).

<img width="913" alt="Screen Shot 2022-08-21 at 12 00 19 AM" src="https://user-images.githubusercontent.com/706929/185774855-131e585e-ad4a-4a53-b3aa-a0e737b1967a.png">

2022-08-21 04:13 UTC, adamgall requested changes
Bug: can make Signature Threshold value be greater than Signer value, without an error appearing

<img width="911" alt="Screen Shot 2022-08-21 at 12 11 52 AM" src="https://user-images.githubusercontent.com/706929/185775191-a11efa87-aa15-42e3-884f-928db2c454ae.png">
 
To trigger bug start with a valid m of n schema, then use the "remove" buttons next to addresses to decrease the Signers to below Signature Threshold.

2022-08-21 04:24 UTC, adamgall commented on src/components/DaoCreator/gnosis/GnosisConfig.tsx
>        error = 'Threshold is to high';
to -> too

2022-08-21 04:38 UTC, adamgall submitted a review, later dismissed

2022-08-22 14:06 UTC, Da-Colon commented
@adamgall merged w/ develop to fix conflict, will need a re-approval

2022-08-22 14:26 UTC, adamgall approved these changes

2022-08-22 14:27 UTC, merged