Deploy a Gnosis Safe SubDAO with Token Voting Parent DAO
decent-dao/fractal-interface pull request #454
Opened 2022-08-24 16:36 UTC by christopherdancy

PR changes one file - TokenGovernanceInjector.

The intent of this PR is to provide the user with the ability to propose a gnosis / token voting sub DAO. This is accomplished by utilising cases to determine if the proposal should include the gnosis or token voting encoded data.

Things to note: The 1:1 token voting does not work due to a small bug which has been addressed in #453 - the bug will be fixed during the merge.

To test this PR - please try to create a gnosis Safe subdao

2022-08-24 19:27 UTC, Da-Colon requested changes
LFG. Successfully created a Gnosis Safe subDAO. Few minor 'clean up as you go comments' and we are on our way.

2022-08-25 17:34 UTC, Da-Colon commented on src/controller/Modules/TokenGovernanceInjector.tsx
> +        values: [0],
Can you BigNumber all the 0 values?

2022-08-25 18:19 UTC, adamgall commented on src/controller/Modules/TokenGovernanceInjector.tsx
> +        values: [0],
@christopherdancy to hopefully provide more context to @Da-Colon 's request: functionally, it doesn't matter if `0` is a `BigNumber` or a `Number`. ethers.js will handle it just fine.

But from the point of view of our mental model, and the app's understanding, of types, it's best that we declare things as the "correct" type initially.

Since this value represents an amount of ether, `BigNumber` is the correct type.

If this is declared as a `Number` here, then at some point later down the execution stack, typescript will just inform us that the thing is a `Number`, and the programmer won't know if it's ok for them to cast/treat it as a `BigNumber`, if the situation arises where they might want/need to do so.

Declaring it as a `BigNumber` here means that down the execution stack, the programmer knows that it can be treated as a `BigNumber`.

2022-08-25 20:12 UTC, Da-Colon commented on src/controller/Modules/TokenGovernanceInjector.tsx
> +        values: [0],
🥇 exactly thanks for going into more detail @adamgall

2022-08-26 16:05 UTC, christopherdancy commented on src/controller/Modules/TokenGovernanceInjector.tsx
> +        values: [0],
I see I see! perfect - I was wondering what the need for this was.

2022-08-26 16:37 UTC, adamgall commented
@christopherdancy fwiw, you can save a few keystrokes and instantiate a `BigNumber` from a number type, as well as a string 

For example

`BigNumber.from(0)`

Instead of

`BigNumber.from('0')`

2022-08-26 16:38 UTC, adamgall approved these changes

2022-08-29 15:41 UTC, SudoPumpkin commented
Are subDAO for Gnosis is not functioning yet?
Example DOA:
0x57232073Bba00C00db5a65920a1bEdF6D6FF7F08

![image](https://user-images.githubusercontent.com/86701852/187239664-b4bfdc63-9aee-4c69-b35b-32d044f5cf8c.png)

2022-08-29 18:02 UTC, Da-Colon commented
> Are subDAO for Gnosis is not functioning yet?

@SudoPumpkin Is this on Rinkeby? This Branch doesn't contain `rinkeby` support just yet. Can you try on Goerli?

I just made this one fresh on Goerli. 0x489dB2adf2551c20b97515802A0289d0478c02e2

2022-08-29 18:10 UTC, Da-Colon approved these changes

2022-08-29 18:28 UTC, SudoPumpkin commented
> > Are subDAO for Gnosis is not functioning yet?
> 
> @SudoPumpkin Is this on Rinkeby? This Branch doesn't contain `rinkeby` support just yet. Can you try on Goerli?
> 
> I just made this one fresh on Goerli. 0x489dB2adf2551c20b97515802A0289d0478c02e2

Yeah, Rinkeby.

2022-08-29 18:52 UTC, Da-Colon commented
@SudoPumpkin Yeah this branch doesn't contain the Rinkeby Support Merg

2022-08-29 19:38 UTC, SudoPumpkin approved these changes
This looks to be working as intended on preview-454

2022-08-29 19:38 UTC, merged