Dao creator/token supply bn support
decent-dao/fractal-interface pull request #475
Opened 2022-09-01 19:01 UTC by Da-Colon

## Description

Updates to fully support BigNumbers smoothly.

## Notes

- For Now test with a single allocation and 1 allocated. The Token Allocation field will be updated in following PR.

## Issue (if applicable)
#472  
#456 

## Testing
Create a DAO -> Esstentials -> Choose Governance (1:1 Token Voting) -> Treasury and Governance Token

- Token Supply: User should be able to type Large Number and decimals up to 18
- Token Supply: User should only type numbers
-> Governance Config -> Deploy

- User should be able to Deploy a new DAO with current Token Supply

## Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/38386583/187992205-f99e5899-1c63-4b3d-9b06-11bcf811fa3f.png)

2022-09-01 19:06 UTC, Da-Colon reviewed
First set of 3 PRs

2022-09-01 19:06 UTC, Da-Colon commented on src/components/DaoCreator/provider/CreatorProvider.tsx
> +    },
This will allow for the input to be controlled separately from calculated BigNumber

2022-09-01 19:06 UTC, Da-Colon commented on src/components/DaoCreator/provider/types/index.ts
> +
New Type To be reused for other BigNumber Inputs

2022-09-01 19:06 UTC, Da-Colon commented on src/components/DaoCreator/tokenVotingGovernance/TokenAllocationInput.tsx
> +        type="text"
This is reverted back to a number type field in a following PR. Will probably show an error in console if letters are typed but shouldn't crash anything

2022-09-02 03:27 UTC, adamgall requested changes
Nice PR, good job. I tested very lightly and it worked for me. I have a couple of questions and comments though.

It would be good to have @SudoPumpkin give this a more thorough shakedown.

2022-09-02 03:27 UTC, adamgall commented on src/helpers/crypto.ts
> +export function formatStrToBigNumber(str: string, decimals: number = 18): BigNumber {
Given the name, I would expect it to just do `return BigNumber.from(inputString)`

But it really deals with token amount inputs. It specifically turns strings of numbers (without any error checking...) into their humanized token-amount equivalent, taking the token's decimals number into account.

It really just calls `utils.parseUnits()` with the inputs.

Why even need this function anyway?

2022-09-02 03:27 UTC, adamgall commented on src/hooks/useCreateDAODataCreator.ts
> +          amount: tokenSupply.valueBN!.sub(tokenAllocationSum),
The bangs make me cautious. Why are you confident that this value will exist here?

2022-09-02 03:27 UTC, adamgall commented on src/hooks/useCreateDAODataCreator.ts
> +            [tokenSupply.valueBN!.sub(tokenAllocationSum)],
Same concern as above

2022-09-02 03:27 UTC, adamgall commented on src/helpers/crypto.ts
> +  return utils.parseUnits(str, decimals);
This is crashing when the `str` input has > 18 numbers after the decimal.

This is my input:
<img width="706" alt="Screen Shot 2022-09-01 at 11 15 01 PM" src="https://user-images.githubusercontent.com/706929/188051920-9b57660f-edfb-4bff-a402-e91a82857be3.png">
If I attempt to enter any more numbers at the end of the string (bringing it to 19 numbers after the decimal), a(n uncaught) console error is displayed:

```

index.ts:269 Uncaught Error: fractional component exceeds decimals [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT ] (fault="underflow", operation="parseFixed", code=NUMERIC_FAULT, version=bignumber/5.7.0)
    at e.value (index.ts:269:28)
    at e.value (index.ts:281:20)
    at b (fixednumber.ts:19:19)
    at h (fixednumber.ts:104:9)
    at Module.u (index.ts:80:12)
    at vi (crypto.ts:11:10)
    at onChange (TokenDetails.tsx:26:35)
    at Object.Pe (react-dom.production.min.js:54:317)
    at Be (react-dom.production.min.js:54:471)
    at react-dom.production.min.js:55:35
value @ index.ts:269
value @ index.ts:281
b @ fixednumber.ts:19
h @ fixednumber.ts:104
u @ index.ts:80
vi @ crypto.ts:11
onChange @ TokenDetails.tsx:26
Pe @ react-dom.production.min.js:54
Be @ react-dom.production.min.js:54
(anonymous) @ react-dom.production.min.js:55
_a @ react-dom.production.min.js:105
Ra @ react-dom.production.min.js:106
(anonymous) @ react-dom.production.min.js:117
cc @ react-dom.production.min.js:274
je @ react-dom.production.min.js:52
Ya @ react-dom.production.min.js:109
Ht @ react-dom.production.min.js:74
Gt @ react-dom.production.min.js:73
```

2022-09-02 16:04 UTC, SudoPumpkin requested changes
Testing Functionality Observations

**(1) Bug**: Users can input the numerical symbols of '-' and '+' in the Treasury and Governance 'Token Supply' field. The field allows this input. No error occurs in the console or for the user.
Example: '1000.1111111111111111-+'
![image](https://user-images.githubusercontent.com/86701852/188191543-876243f6-f324-416f-bb90-6e3e60a9a78e.png)

**(2) Console Error**: When the user tries to exceed the 18 decimal limit in the Treasury and Governance 'Token Supply' field the below console error occurs. There are no errors visible to the user.

> Uncaught Error: fractional component exceeds decimals [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT ] (fault="underflow", operation="parseFixed", code=NUMERIC_FAULT, version=bignumber/5.7.0)
>     at e.value (index.ts:269:28)
>     at e.value (index.ts:281:20)
>     at b (fixednumber.ts:19:19)
>     at h (fixednumber.ts:104:9)
>     at Module.u (index.ts:80:12)
>     at hi (crypto.ts:11:10)
>     at onChange (TokenDetails.tsx:26:35)
>     at Object.Pe (react-dom.production.min.js:54:317)
>     at Be (react-dom.production.min.js:54:471)
>     at react-dom.production.min.js:55:35

**(3) Observation**: The user can input as many zero's after the decimal as they desire in the 'Treasury and Governance' > 'Token Supply' field. No number other then '0' is allowed past the 18th decimal point. _Not that it matters but I am reporting it anyway._
Example: '100.00000000000000000000000000000000000000000000000000000000000000'

2022-09-02 17:08 UTC, Da-Colon commented on src/components/DaoCreator/provider/hooks/useNextDisabled.ts
> +            .lte(state.govToken.tokenSupply.valueBN!);
just push a commit to deconstruct state in one spot versus throughout this switch statement

2022-09-02 17:12 UTC, Da-Colon commented on src/components/DaoCreator/tokenVotingGovernance/TokenAllocations.tsx
>        if (totalAllocated.gt(0) && (!parentAllocationAmount || parentAllocationAmount?.lte(0))) {
I'll take a look at this in the 3rd PR. There is one or two places I left a `?` on purpose as it fits what we need it to do. but this one you point out is unneeded.

2022-09-02 17:14 UTC, Da-Colon commented on src/hooks/useCreateDAODataCreator.ts
> +          amount: tokenSupply.valueBN!.sub(tokenAllocationSum),
Because of the validations that are already set in place. wouldn't allow for this click to happen. not only on the page 'next' button but on the 'deploy' click as well.

2022-09-02 17:49 UTC, Da-Colon commented on src/components/DaoCreator/provider/types/index.ts
> +
updated

2022-09-02 17:50 UTC, Da-Colon commented on src/components/DaoCreator/tokenVotingGovernance/TokenAllocationInput.tsx
> -        isWholeNumberOnly
I think after these PRs it may be removed.

2022-09-02 17:53 UTC, Da-Colon commented on src/helpers/crypto.ts
> +export function formatStrToBigNumber(str: string, decimals: number = 18): BigNumber {
you are right, removed/replaced

2022-09-02 18:16 UTC, christopherdancy requested changes

2022-09-02 18:16 UTC, christopherdancy commented on src/components/DaoCreator/provider/CreatorProvider.tsx
> +    tokenSupply: {
Hey @Da-Colon,
Should we init the value as a big number?

2022-09-02 18:16 UTC, christopherdancy commented on src/components/DaoCreator/tokenVotingGovernance/TokenDetails.tsx
> +          helperText="Max: 18 decimals"
Quick Question - When we say max 18 decimals - does the user have the ability to change the decimals?

2022-09-02 18:16 UTC, christopherdancy commented on src/components/DaoCreator/provider/hooks/useNextDisabled.ts
> +          state.govToken.tokenSupply.bigNumberValue!.gt(0) &&
Does it seem a tad werid that within the same file we are calling govToken and here we have to call state.govToken

2022-09-02 18:19 UTC, christopherdancy commented on src/components/DaoCreator/provider/CreatorProvider.tsx
> +    tokenSupply: {
all nitpick stuff

2022-09-02 18:48 UTC, Da-Colon commented on src/components/DaoCreator/provider/hooks/useNextDisabled.ts
> +          state.govToken.tokenSupply.bigNumberValue!.gt(0) &&
Thats fixed now

2022-09-02 18:57 UTC, Da-Colon commented on src/components/DaoCreator/provider/CreatorProvider.tsx
> +    tokenSupply: {
No worries, I wanted to allow for the input field to be empty. So the intial state of the input is en empty string. With the value being an empty string,  it should initialize the bigNumber as a null value.

2022-09-02 18:58 UTC, Da-Colon commented on src/components/DaoCreator/tokenVotingGovernance/TokenDetails.tsx
> +          helperText="Max: 18 decimals"
SO far thats the current functionality in app. Non-trivial to get a input added to select number of decimals. Possibly a short sprint that can be planned out and approved by product

2022-09-02 19:01 UTC, adamgall commented on src/components/DaoCreator/tokenVotingGovernance/TokenDetails.tsx
> +          helperText="Max: 18 decimals"
This form results in a new Token contract being created on-chain. Specifically, it results in [this](https://github.com/decent-dao/fractal-votes-token/blob/main/contracts/VotesToken.sol) token being created, which defaults to OpenZeppelin's recommended 18 decimals, and doesn't override that.

So, if we wanted to allow the user to input their own decimal value, we would need to expose that functionality on the contract side as well.

I think that's out of scope for what we care about right now.

2022-09-02 19:21 UTC, adamgall requested changes
Looking good so far, pretty close from my point of view!

2022-09-02 19:21 UTC, adamgall commented on src/components/ui/forms/Input.tsx
> +      if (!value || ['Backspace', 'Delete'].includes(event.key)) {
What do these `event.key` names look like when a browser is non-english?

2022-09-02 19:21 UTC, adamgall commented on src/components/ui/forms/Input.tsx
> +      if (!!dec && !!decimals && dec.length >= decimals) {
Should the condition be `dec.length > decimals`?

if `dec.length` is 18, it should be allowed, right? We only want to kill the input starting with the 19th digit.

If my off-by-one is messed up here, my fault.

2022-09-02 19:21 UTC, adamgall commented on src/components/DaoCreator/tokenVotingGovernance/TokenAllocationInput.tsx
> -        isWholeNumberOnly
Linking this on #477

2022-09-02 19:21 UTC, adamgall commented on src/components/DaoCreator/tokenVotingGovernance/TokenAllocations.tsx
>        if (totalAllocated.gt(0) && (!parentAllocationAmount || parentAllocationAmount?.lte(0))) {
Linking this on #477

2022-09-02 19:21 UTC, adamgall commented on src/components/ui/forms/Input.tsx
> +      }
Nitpicky but can you conform these properties / function names together?

`wholeNumbersOnly`/`floatNumbersOnly`
or
`wholeNumbers`/`floatNumbers`

2022-09-06 14:05 UTC, adamgall approved these changes

2022-09-06 16:04 UTC, adamgall commented
Leaving a comment that doesn't need to be addressed in this PR: the consumer of `Input` can screw up and add both `floatNumbersOnly` _and_ `wholeNumbersOnly` properties, which ain't gonna work.

2022-09-07 16:12 UTC, adamgall commented on src/components/ui/forms/Input.tsx
> +      if (!!dec && !!decimals && dec.length >= decimals) {
edit: nevermind, just manually tested this out myself and it functionally works as expected.

2022-09-07 16:13 UTC, adamgall commented
@christopherdancy and @SudoPumpkin , you've both requested changes on this PR, which blocks it from being merged until you give an explicit "approval".

When you both have time, can you please re-review this PR and give an updated status?

2022-09-07 16:36 UTC, Da-Colon commented on src/components/DaoCreator/provider/hooks/useNextDisabled.ts
> +    } = state;
I moved it up here 👍 @mudrila

2022-09-07 17:38 UTC, christopherdancy approved these changes

2022-09-07 17:47 UTC, SudoPumpkin approved these changes
Listed functionality looks good to me in preview-475.

2022-09-07 21:15 UTC, merged