Add sentry
decent-dao/fractal-interface pull request #478
Opened 2022-09-01 21:21 UTC by Da-Colon

## Description

Adds Sentry and Sentry support to Fractal app

## Notes

- This PR only covers the installation and setup of Sentry and Adds a ErrorBoundary Screen which will catch app 

## Next Steps:
- Adding sentry to any places that are catching errors.
- https://docs.sentry.io/platforms/javascript/guides/react/usage/
## Issue (if applicable)

## Testing

Error Boundary:
The Error Boundary is a little hard to test on a preview, but this will show up when there is a rendering issues causing the app to crash.

Sentry:
I have tested this myself and again will be hard to force a problem on develop. but I have setup the IPFS and the develop websites to connect and report to sentry
## Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/38386583/188014914-9135dce8-b35f-49b2-a889-b2177de97b0e.png)

2022-09-02 02:39 UTC, adamgall requested changes

2022-09-02 02:39 UTC, adamgall commented on src/index.tsx
> +
When this is initialized with an empty string `dsn`, what happens?

2022-09-02 02:39 UTC, adamgall commented on .github/workflows/release-ipfs-dev.yaml
> +          REACT_APP_REACT_APP_SENTRY_DSN: ${{ secrets.REACT_APP_GNOSISSAFE_ADDRESSES }}
Can you please add this ENV to the committed `.env` file

2022-09-02 02:43 UTC, adamgall commented
Regarding your comment about next steps, (and reading their docs), it seems like Sentry won't automatically report errors unless they're uncaught?

What does that mean we should do...

2022-09-02 13:35 UTC, adamgall commented on src/components/ErrorFallback.tsx
> +            <div className="text-md text-gray-25 text-mono">{error.message}</div>
I think I agree with @mudrila here, as long as we're sure the actual error that this `ErrorBoundary` `fallback` component is catching is being sent to Sentry.

2022-09-02 16:24 UTC, Da-Colon commented on src/index.tsx
> +
App loads normally with no errors or anything. As far as I've read everything else should continue working normally locally

2022-09-02 16:32 UTC, Da-Colon commented on src/components/ErrorFallback.tsx
> +              onClick={() => window.location.reload()}
Just tried it, I get this error. 

![image](https://user-images.githubusercontent.com/38386583/188198581-f16bcd5b-d486-48f1-b637-683f9a6a9c5b.png)

2022-09-02 16:34 UTC, Da-Colon commented on src/components/ErrorFallback.tsx
> +            <div className="text-md text-gray-25 text-mono">{error.message}</div>
![image](https://user-images.githubusercontent.com/38386583/188198763-2c022e7b-187b-4bb6-8bed-f2b41d84f048.png)
Definitely working. Yeah I'll remove the error message. While the User should never really see this page. We may need to add something a little more to this error screen.

2022-09-02 17:12 UTC, adamgall approved these changes
I dig it, thanks @Da-Colon

2022-09-02 17:13 UTC, adamgall commented on src/components/ErrorFallback.tsx
> +            <div className="text-md text-gray-25 text-mono">{error.message}</div>
It looks good for now, thanks!

2022-09-02 17:14 UTC, adamgall commented
@Da-Colon

One more thing to at least touch upon here, is: what is expected for capturing Sentry errors in places where we're _already_ catching errors and `console.error`ing them / showing them as a toast?

2022-09-02 17:18 UTC, Da-Colon commented
In the usage does (link in the desciprtion). we would simply add to our changes. 
```ts
import * as Sentry from "@sentry/react";

try {
  aFunctionThatMightFail();
} catch (err) {
  Sentry.captureException(err);
}
```

2022-09-06 17:41 UTC, adamgall commented
> In the usage docs (link in the desciprtion). we would simply add to our catches.
> 
> ```ts
> import * as Sentry from "@sentry/react";
> 
> try {
>   aFunctionThatMightFail();
> } catch (err) {
>   Sentry.captureException(err);
> }
> ```

@Da-Colon 

This seems like a lot of work to do, probably another PR where all of those exceptions in the existing app which are currently being caught and logged, are caught/logged/sent to Sentry. Maybe there's an "error handling" function added to the app which does all of those side-effects.

2022-09-06 19:50 UTC, Da-Colon commented
> This seems like a lot of work to do, probably another PR where all of those exceptions in the existing app which are currently being caught and logged, are caught/logged/sent to Sentry. Maybe there's an "error handling" function added to the app which does all of those side-effects.

Yessir I agree, I'll add getting this card created to my todo list

2022-09-07 14:48 UTC, merged