Implement showing transaction events for classic Treasury
decent-dao/fractal-interface pull request #491
Opened 2022-09-12 15:13 UTC by mudrila

## Description

As part of Activity Feed implementation - this PR scoped to enhancing `TreasuryController` and showing list of transaction events.

## Notes

Next PR supposed to make same for Gnosis Safe Treasury-based DAO, so while making code review - mind that this PR is focusing "1:1" Treasury, but also enhances general boilerplate

## Issue
Closes #486 

## Testing

1. Visit DAO dashboard page that has 1:1 Token Governance (therefore "classic" Treasury) - example link http://localhost:3000/#/daos/0x68dB43B90E6284019c0513168b514d103F4e1092/dashboard
2. Observe transactions appearing there
3. Optional, if the DAO don't have much transactions in history - try to send tokens / NFTs / native token to the DAO, try to withdraw funds from there (not sure there's a way for that currently though 🤷🏼 )

## Screenshots (if applicable)
<img width="853" alt="Знімок екрана 2022-09-12 о 18 04 48" src="https://user-images.githubusercontent.com/25801162/189690780-a3579d0c-a4d2-4b02-a5b0-fb4118b909d6.png">

2022-09-12 18:35 UTC, Da-Colon commented on src/controller/Modules/injectors/TokenGovernanceInjector.tsx
> +    return children;
I remove this completely in #487 As well as update the Controller to return null instead of children if it's not one of the identified governance modules

2022-09-12 18:36 UTC, Da-Colon commented on src/controller/Modules/injectors/GnosisTreasuryInjector.tsx
> +export function GnosisTreasuryInjector({ children }: { children: JSX.Element }) {
I have some work in the #488 that will need to be updated once the injector is finished.

2022-09-12 18:37 UTC, Da-Colon commented on src/controller/Modules/TreasuryController.tsx
> -export function TreasuryController({ children }: PropsWithChildren) {
check out #487

2022-09-13 17:45 UTC, christopherdancy requested changes

2022-09-13 17:45 UTC, christopherdancy commented on src/components/ui/EtherscanTransactionLink.tsx
> +  address,
Hey quick nitpick here - if this is a tx hash, should we rename the var?

2022-09-14 16:40 UTC, adamgall approved these changes
Going to approve for the sake of progress/cadence, but I left some comments about things that maybe should change.

2022-09-14 16:40 UTC, adamgall commented on src/components/Dao/Dashboard.tsx
> +      ))}
I'd like to see the creation of these components (the activity feed items) happen outside of this Dashboard. I specifically don't think that something like `transaction.eventType === TokenEventType.DEPOSIT ? 'Received' : 'Sent'` belongs in here.

2022-09-14 16:40 UTC, adamgall commented on src/controller/Modules/injectors/TreasuryInjector.tsx
> +// However, need discussion for this during PR review
How should this discussion happen? Who should be involved with it?

2022-09-14 17:22 UTC, adamgall commented on src/components/Dao/Dashboard.tsx
> +      ))}
Far enough, we can tackle that later 👍

2022-09-19 19:21 UTC, Da-Colon approved these changes

2022-09-19 19:54 UTC, herbig reviewed
Hey @mudrila, in testing this at the preview URL (https://deploy-preview-491--fractal-framework-interface-dev.netlify.app/#/daos/0x68dB43B90E6284019c0513168b514d103F4e1092/dashboard), after I sent both Eth and wrapped eth to the treasury, I got into an infinite reload state.  I'm not sure if it has to do with those transactions, but I can no longer get out of this screen at that URL:
<img width="422" alt="Screen Shot 2022-09-19 at 3 49 57 PM" src="https://user-images.githubusercontent.com/384559/191104364-17b81241-b9e1-4c7d-acd1-c6281cdb4cb2.png">

Transactions:
https://goerli.etherscan.io/tx/0x41fec7aff3823ffb48341105f2aefc4d457f6457331fe17d4fbbc9d6d9dd13bb

https://goerli.etherscan.io/tx/0x21a097404f81192a08c717ca82cebcb4d23bf8c0650bef50f20477900797625f

2022-09-19 19:54 UTC, herbig commented on src/providers/gnosis/hooks/useGnosisEvents.ts
> +const useGnosisEvents = (gnosisWrapperContract?: GnosisWrapper) => {
maybe it's answered in the next PR, but when would `gnosisWrapperContract` be undefined here? It seems like with this code you could check right at the top and just do nothing if that's the case, or is there some reactive thing I'm missing?

2022-09-19 19:54 UTC, herbig commented on src/components/ui/EtherscanTransactionLink.tsx
> +  const subdomain = useSubDomain();
it seems like the `useSubDomain` method won't handle mainnet (https://etherscan.io/) or Polygon (https://polygonscan.com/) properly, we might need a different solution for that.

2022-09-19 19:54 UTC, herbig commented on src/components/Dao/Dashboard.tsx
> +            {transaction.eventType === TokenEventType.DEPOSIT ? 'Received' : 'Sent'}{' '}
Is it possible we could add additional `TokenEventType`s in the future, like Approvals? In that case this would break.

2022-09-19 19:54 UTC, herbig commented on src/components/Dao/Dashboard.tsx
> +        <H1>{dao.daoName}</H1>
Did we have a design file for this, or is this ad hoc at the moment? It seems like this should be centered vertically (which it isn't in Firefox)
<img width="389" alt="Screen Shot 2022-09-19 at 3 32 33 PM" src="https://user-images.githubusercontent.com/384559/191100468-cce42628-493c-4696-98d1-ff8b28d1817c.png">

2022-09-19 19:54 UTC, herbig commented on src/components/Dao/Dashboard.tsx
> +              transaction.amounts?.map((amount: BigNumber) => amount.toString())}
Can we add the token symbol here?

2022-09-19 19:54 UTC, herbig commented on src/components/Dao/Dashboard.tsx
> +        <H1>{dao.daoName}</H1>
Although actually since the DAO name is already in the top left, maybe this header isn't even necessary?

2022-09-21 15:03 UTC, merged