Test docker container
decent-dao/fractal-interface pull request #504
Opened 2022-09-20 15:01 UTC by Da-Colon

## Description

Creates a dockerized hardhat blockchain node using DockerFile and docker-compose. This is for setting up a test environment in which these test will read and write to a local blockchain node.

## Notes

## Issue (if applicable)
n/a

## Testing

## Screenshots (if applicable)

2022-09-21 23:02 UTC, Da-Colon reviewed
I still need to write a README for this setup. I will commit this soon.

2022-09-21 23:02 UTC, Da-Colon commented on docker/blockchain/Dockerfile
> +ENTRYPOINT ["/bin/sh", "/usr/local/bin/entrypoint.sh"]
This only runs one command I'm using the same setup for the other Dockerfile. I've tried to use `CMD` for the webapp and it didn't work. so stuck with this pattern

2022-09-21 23:02 UTC, Da-Colon commented on docker/blockchain/hardhat.config.js
> +        url: `https://eth-goerli.g.alchemy.com/v2/${process.env.ALCHEMY_API_KEY}`
I need to add documentation but theway this works, I have an example.env that will need to be manually copied and changed into a .env.local file within the same directory. This file is `COPY` to the docker container. This keeps this key hidden.

2022-09-22 14:35 UTC, herbig reviewed
Hey @Da-Colon this is great! Have a few comments / questions!

2022-09-22 14:35 UTC, herbig commented on docker/blockchain/hardhat.package.json
> +    "ethers": "^5.4.7",
it looks like this is different from the app version (5.7.0), should these be aligned, or does it not matter?

2022-09-22 14:35 UTC, herbig commented on docker/blockchain/hardhat.config.js
> +        url: `https://eth-goerli.g.alchemy.com/v2/${process.env.ALCHEMY_API_KEY}`
I assume `.env.local` is in our repo's gitignore?

If I'm understanding this properly, you would need to copy `.env.example` manually to `.env.local`, and add your own API key?

If that's the case perhaps the example could be removed and just document that you need to create a new `.env.local` file, to avoid the situation where someone edits `.env.example` and commits that by mistake.

2022-09-22 14:35 UTC, herbig commented on docker/blockchain/hardhat.config.js
> +// This is a sample Hardhat task. To learn how to create your own go to
if this isn't used, we can remove this

2022-09-22 14:35 UTC, herbig commented on docker/blockchain/hardhat.config.js
> +// Go to https://hardhat.org/config/ to learn more
You could keep this comment and just move it into the exports comment below

2022-09-22 14:35 UTC, herbig commented on docker/README.md
> +The Ultimate Goal with these docker container is to create an environment that end to end testing can take place. We needed to solve a way for tests to be ran against a set of deployed contracts with
Suggesting:

`The Ultimate Goal with this docker container is to create an environment that end to end testing can take place in. We needed a way for tests to be run against a set of deployed contracts without worrying about any wallet integration.`

Just being a grammar nerd, ha.

2022-09-22 17:11 UTC, Da-Colon commented on docker/blockchain/hardhat.package.json
> +    "ethers": "^5.4.7",
doesn't have to be the same. This is only for running the hardhat node and won't effect anything

2022-09-22 17:14 UTC, Da-Colon commented on docker/blockchain/hardhat.config.js
> +// This is a sample Hardhat task. To learn how to create your own go to
Yeah this tasks isn't needed I'll remove it

2022-09-22 17:14 UTC, Da-Colon commented on docker/blockchain/hardhat.config.js
> +// Go to https://hardhat.org/config/ to learn more
I'll just remove the hardhat created comments

2022-09-22 17:15 UTC, adamgall commented on docker/webapp/entrypoint.sh
> +# Run hardhat
Does this run hardhat or run the react app?

2022-09-22 17:16 UTC, adamgall commented on docker/webapp/Dockerfile
> +COPY package-lock.json ./fractal-webapp/package.json
Looks like there's a typo on this line.

2022-09-22 17:19 UTC, Da-Colon commented on docker/webapp/entrypoint.sh
> +# Run hardhat
updated

2022-09-22 17:19 UTC, Da-Colon commented on docker/webapp/Dockerfile
> +COPY package-lock.json ./fractal-webapp/package.json
updated

2022-09-22 17:21 UTC, adamgall commented on docker/webapp/Dockerfile
> +COPY package-lock.json ./fractal-webapp/package.json
Wait I mean... shouldn't

```
COPY package-lock.json ./fractal-webapp/package.json
```

be

```
COPY package-lock.json ./fractal-webapp/package-lock.json
```

2022-09-22 17:21 UTC, Da-Colon commented on docker/blockchain/hardhat.config.js
> +        url: `https://eth-goerli.g.alchemy.com/v2/${process.env.ALCHEMY_API_KEY}`
yeah thats fair. I can remove this

2022-09-22 17:22 UTC, adamgall commented on docker/webapp/Dockerfile
> +COPY package-lock.json ./fractal-webapp/package.json
@Da-Colon

2022-09-22 17:31 UTC, Da-Colon commented on docker/webapp/Dockerfile
> +COPY package-lock.json ./fractal-webapp/package.json
o weird. let me test something then because this still works. so maybe don't need the package json?

2022-09-22 17:32 UTC, Da-Colon commented on docker/webapp/Dockerfile
> +COPY package-lock.json ./fractal-webapp/package.json
okay yeah opps I see it, wow

2022-09-22 17:40 UTC, adamgall commented on docker/webapp/Dockerfile
> +COPY package-lock.json ./fractal-webapp/package.json
thank you ser

2022-09-22 17:49 UTC, adamgall requested changes

2022-09-22 17:49 UTC, adamgall commented on docker/README.md
> +- `.env.local` to keeps secrets, secret. This file will need to be manually created with the following variable
Manually created... where?

2022-09-22 17:49 UTC, adamgall commented on docker/blockchain/Dockerfile
> +COPY ./.env.local /fractal-blockchain-node/.env
I'm wondering where this file is being copied from. It's gitignored, so the repo on Github doesn't have one.

2022-09-22 17:49 UTC, adamgall commented on docker/blockchain/Dockerfile
> +COPY ./hardhat.config.js /fractal-blockchain-node/hardhat.config.js
Nitpick, this file isn't being renamed, but the comment says it is.

2022-09-22 17:49 UTC, adamgall commented on docker/webapp/Dockerfile
> +FROM node:16
Can we make this match the version in `.nvmrc` exactly: 16.13.2

2022-09-22 17:49 UTC, adamgall commented on docker/blockchain/Dockerfile
> +FROM node:16-alpine
Can we make this match the version in `.nvmrc` exactly: 16.13.2-alpine

2022-09-22 17:49 UTC, adamgall commented on docker-compose.yml
> +    build: docker/blockchain
Can/should this file path be relative? `build: ./docker/blockchain`

2022-09-22 17:49 UTC, adamgall commented on .dockerignore
> +./github
Should this be `./.github`?

2022-09-22 17:49 UTC, adamgall commented on .dockerignore
> +./vscode
Should this be `./.vscode`?

2022-09-22 17:51 UTC, adamgall commented on docker/README.md
> +- `.env.local` to keeps secrets, secret. This file will need to be manually created with the following variable
Oh maybe, the intention here is that this file is created in the github workflow file?

2022-09-22 17:52 UTC, adamgall commented on docker/blockchain/Dockerfile
> +COPY ./.env.local /fractal-blockchain-node/.env
As per the previous conversation thread, is this being copied from the runner's local VM environment after the github workflow actually creates the `.env.local` file?

2022-09-22 18:00 UTC, Da-Colon commented on docker/README.md
> +- `.env.local` to keeps secrets, secret. This file will need to be manually created with the following variable
instructions are below that in the readme

2022-09-22 18:02 UTC, Da-Colon commented on docker/blockchain/Dockerfile
> +COPY ./.env.local /fractal-blockchain-node/.env
I'm still thinking through this, but thats the idea. I need to look into more on how we can keep this value secret.

2022-09-22 18:03 UTC, Da-Colon commented on docker-compose.yml
> +    build: docker/blockchain
it's context here is the root of the project, but I can make it more explict if need be

2022-09-22 18:48 UTC, adamgall requested changes

2022-09-22 18:48 UTC, adamgall commented on docker/README.md
> +`docker compose` or `docker compose COMMAND --help`
Can all of these commands please be wrapped in triple backticks, so they get their own line, and prepended with `$` so that it's clear they're CLI commands?

```sh
$ like this
```

2022-09-22 18:48 UTC, adamgall commented on docker/webapp/Dockerfile
> +ENTRYPOINT ["/bin/sh", "/usr/local/bin/entrypoint.sh"]
Nitpick

Please add a newline to the end of this file

2022-09-22 18:53 UTC, adamgall commented on docker/webapp/Dockerfile
> +COPY package.json ./fractal-webapp/package.json
As you mentioned, perhaps we can remove this file. The lock file is technically the only thing that matters. Question is: will `npm install` work if just the lockfile is there?

2022-09-22 19:51 UTC, adamgall commented on docker/README.md
> +You are gonna need to do is retreive a free alchemy api key from https://www.alchemy.com/.
@Da-Colon i'm sorry, my attempt at humor could very likely be taken as me being a real dickhead. apologies.

2022-09-22 20:07 UTC, Da-Colon commented on docker/webapp/Dockerfile
> +COPY package.json ./fractal-webapp/package.json
You are right, don't need it

2022-09-22 20:07 UTC, Da-Colon commented on docker/webapp/Dockerfile
> +ENTRYPOINT ["/bin/sh", "/usr/local/bin/entrypoint.sh"]
done

2022-09-22 20:07 UTC, Da-Colon commented on docker/README.md
> +`docker compose` or `docker compose COMMAND --help`
done

2022-09-22 20:59 UTC, Da-Colon commented
What about this?

// package.json
```json
"scripts": {
  "docker:launch": "docker compose --env-file ./env.local"
}
```

//.docker-compose.yml
```yml
environment:
  - REACT_APP_ALCHEMY_API_KEY
```
This is technically already a variable used by the react app

2022-09-22 23:39 UTC, adamgall requested changes
This is ready to go EXCEPT for the `README.md` updates which are necessary due to the latest slew of commits.

2022-09-23 05:12 UTC, Da-Colon commented on docker/blockchain/hardhat.package.json
> +    "ethers": "^5.4.7",
Turns out. don't need these ether libraries at all.

2022-09-23 14:48 UTC, adamgall requested changes
Other changes that should happen

- line 6: please make path relative to project (add `./` prefix)
- line 8: refers to creating a `.env.local` file manually, that's not correct
- line 18: please make path relative to project (add `./` prefix)

2022-09-23 14:48 UTC, adamgall commented on docker/README.md
> +Once obtained, create a `.env.tests.local` file in `docker/` directory. Add your Alchemy api key to an env variable `ALCHEMY_API_KEY` as shown in /docker/.env.tests.local. see https://hardhat.org/har
> Once obtained, create a `.env.tests.local` file in `docker/` directory.

should be

> Once obtained, create a `.env.tests.local` file in `./docker/` directory.

- made path to docker relative to project, not filesystem (added `./` prefix)

---

> Add your Alchemy api key to an env variable `ALCHEMY_API_KEY` as shown in /docker/.env.tests.local.

should be

> Add your Alchemy API key to an env variable `ALCHEMY_API_KEY` as shown in `./docker/.env.tests`.

- capitalized "API"
- made path to example env relative to project, not filesystem (added `.` prefix)
- fixed the typo, which was referencing the `.local` version of `.env.tests` when it should have been referencing the example

2022-09-23 15:24 UTC, herbig commented on docker/README.md
> +- `.env.tests` example to keeps secrets, secret. This file will need to be manually created with the following variable
not sure I follow here, `.env.tests.local` is in the gitignore, should the `.env.tests` file be renamed to that?

2022-09-23 15:25 UTC, herbig commented on docker/README.md
> +- `.env.tests` example to keeps secrets, secret. This file will need to be manually created with the following variable
oh, nevermind, it's described below!

2022-09-23 15:53 UTC, herbig approved these changes
Looks good, thanks for cleaning up the README! Super helpful to have that

2022-09-23 16:37 UTC, adamgall approved these changes
Nice

2022-09-23 16:37 UTC, Da-Colon commented
🚀

2022-09-23 16:38 UTC, merged