Playwright config and Wallet Connection Test
decent-dao/fractal-interface pull request #507
Opened 2022-09-21 19:12 UTC by SudoPumpkin

## Description

Playwright has been installed in this PR with 2 tests. 
One test confirms navigation to the Fractal app via http://localhost:3000. 
The second test navigates to http://localhost:3000, confirms local wallet is present, and connects to the wallet. 

A GitHub Actions yml has been included as of yet.

## Notes
The user will need to run a local version of hardhat(_blockchain node_), start the fractal-interface app, then run the playwright tests. 

## Issue (if applicable)

## Testing

1. Clone repo
2. Open a terminal(A)
3. Install dependencies: `npm i`  
4. Open another terminal(B)
5. Start local hardhat node: `npx hardhat node`
6. Open a third terminal(C)
7. Start fractal-interface app: `npm start`
8. Run Playwright tests: `npx playwright test` in terminal 'A'
9. (2) Tests _should run_ and pass

### To test individual tests use the following:

- `npx playwright test tests/nameOfTest`

_Example:_ 
`npx playwright test tests/ConfirmWalletConnect.spec.ts`

### To view the tests in a browser(Headful) append the following to your command line:

- `--headed`

_Example_: 
`npx playwright test tests/ConfirmWalletConnect.spec.ts --headed`

### To use particular browser types append the following to your command line:

- `--project=browserName`

_Example:_ 
`npx playwright test tests/ConfirmWalletConnect.spec.ts --headed --project=chromium`

## Screenshots (if applicable)

2022-09-21 19:26 UTC, Da-Colon requested changes
Looking good. 2 notes and 2 changes

2022-09-21 19:26 UTC, Da-Colon commented on tsconfig.json
> +, "tests-examples/example.spec.ts"  ]
I think we can remove the `tests-examples' here. Isee that its gitignored but I don't think there is any reason for these to exist locally either yeah?

2022-09-21 19:26 UTC, Da-Colon commented on .gitignore
> +/tests-examples/*
This line could probably be removed and this file if it exists locally deleted

2022-09-21 19:26 UTC, Da-Colon commented on playwright.config.ts
> +  workers: process.env.CI ? 1 : undefined,
Just noting for later but we will want to check that these `env` variables are properly being defined here. (dotenv is not currently installed in this repo)

2022-09-21 19:26 UTC, Da-Colon commented on playwright.config.ts
> +      url: 'http://localhost:3000/#',
For now this is fine. but we may want to set this to a `env` variable in the future in case we want to set differently for different environments

2022-09-21 19:38 UTC, SudoPumpkin commented on playwright.config.ts
> +  workers: process.env.CI ? 1 : undefined,
Ya, we can yoink those out.

2022-09-21 19:39 UTC, SudoPumpkin commented on tsconfig.json
> +, "tests-examples/example.spec.ts"  ]
I removed this.

2022-09-21 19:39 UTC, SudoPumpkin commented on .gitignore
> +/tests-examples/*
Removed this one too.

2022-09-21 19:39 UTC, SudoPumpkin commented on playwright.config.ts
> +      url: 'http://localhost:3000/#',
I can comment this out as well.

2022-09-22 14:14 UTC, Da-Colon approved these changes
👍

2022-09-22 15:24 UTC, herbig commented
Hey @SudoPumpkin ! This is looking great!

First thing I encountered, the tests failed because the browsers weren't installed.  I was able to fix this with `npx playwright install` between steps 3/4, though it seems like `npm i` should have covered this? I'm not really sure.

![Screen Shot 2022-09-22 at 11 11 37 AM](https://user-images.githubusercontent.com/384559/191787011-0b5e6c19-7205-45c3-a7d8-b1bf1b5abbc4.png)

After that, I was able  to get the first three tests to pass, `NavigateToFractal`, but `ConfirmWalletConnect` tests fail, and it seems like it gets hung up on the wallet connect QR:

[84cc575de84edeb083587000e254b8f1f8720e57.webm](https://user-images.githubusercontent.com/384559/191787573-e121e8a2-4499-4221-bb7b-6ae1ad4df893.webm)

Could @Da-Colon or @mudrila try running this locally as well (using the Testing steps above), and see if you encounter the same issues?

2022-09-22 15:50 UTC, Da-Colon commented
@herbig Are you running a local hardhat node when running the tests?

There is one step here that is missing. 

Adding to `.env.local`

```
REACT_APP_LOCAL_CHAIN_ID="31337"
REACT_APP_LOCAL_PROVIDER_URL="http://127.0.0.1:8545"
```

I would comment these out when not trying to run these tests but these are needed currently for the tests to run

2022-09-22 15:50 UTC, Da-Colon commented
@herbig 

In the future this will all run in a dockerized container and there will be no need to set these here

2022-09-22 15:57 UTC, herbig commented
> .env.local

dammit, cool will do that.

Yeah I realize this will be dockerized, just wanted to make sure it's working locally just as a spot check

2022-09-22 16:30 UTC, herbig commented
> @herbig Are you running a local hardhat node when running the tests?
> 
> There is one step here that is missing.
> 
> Adding to `.env.local`
> 
> ```
> REACT_APP_LOCAL_CHAIN_ID="31337"
> REACT_APP_LOCAL_PROVIDER_URL="http://127.0.0.1:8545"
> ```
> 
> I would comment these out when not trying to run these tests but these are needed currently for the tests to run

@Da-Colon I added these to `.env.local` and that test still fails.

![Screen Shot 2022-09-22 at 12 29 14 PM](https://user-images.githubusercontent.com/384559/191802097-99ee51c3-a681-42da-90be-ad696b875583.png)

Is it working locally for you?

2022-09-22 17:03 UTC, herbig approved these changes
Got it working and tests passed!

2022-09-22 17:10 UTC, merged

2022-09-22 17:36 UTC, adamgall commented on package.json
> +    "tests:chrome": "playwright test --config=playwright.config.ts --project=Chromium"
@SudoPumpkin Is it trivial enough to run tests that target Firefox too?

2022-09-22 17:38 UTC, adamgall commented on page-objects/components/HomePage.ts
> +
@SudoPumpkin what is this file for?

2022-09-22 17:42 UTC, SudoPumpkin commented on package.json
> +    "tests:chrome": "playwright test --config=playwright.config.ts --project=Chromium"
Yeah, if you don't define a 'project' it runs all 3 browser types. So don't append '--project=browserName'
I just tossed that in there for my personal testing. 

- Chromium
- Firefox
- Webkit

2022-09-22 17:43 UTC, SudoPumpkin commented on page-objects/components/HomePage.ts
> +
So, this file will be for Page Object Models for selectors, currently it's empty because I have no solid tests built yet.

2022-09-22 17:47 UTC, SudoPumpkin commented on package.json
> +    "tests:chrome": "playwright test --config=playwright.config.ts --project=Chromium"
Example:
Here I ran the command "npx playwrigiht test". It ran all the tests in all 3 browser types.
![Screen Shot 2022-09-22 at 1 46 24 PM](https://user-images.githubusercontent.com/86701852/191816531-3d58a231-1452-4bac-b272-94972544d143.png)

2022-09-22 17:53 UTC, SudoPumpkin commented on page-objects/components/HomePage.ts
> +
Example:
```
import { expect, Locator, Page } from '@playwright/test'

export class HomePage {
    readonly page: Page
    readonly signInButton: Locator
    readonly searchBox: Locator
    readonly linkFeedback: Locator


    constructor(page: Page) {
        this.page = page
        this.signInButton = page.locator("#signin_button")
        this.searchBox = page.locator('#searchTerm')
        this.linkFeedback = page.locator('#feedback')


    }

    async visit() {
        await this.page.goto('http://zero.webappsecurity.com')

    }
    async clickOnSignIn() {
        await this.signInButton.click()


    }

    async clickOnFeedbackLink() {
        await this.linkFeedback.click()
    }

    async searchFor(phrase: string) {
        await this.searchBox.type(phrase)
        await this.page.keyboard.press('Enter')


    }
}
```

2022-09-22 18:55 UTC, adamgall commented on page-objects/components/HomePage.ts
> +
Ah gotcha, so it's like a place to build helper functions that do the actual selecting/clicking/typing, so the tests can be more readable?

2022-09-22 19:03 UTC, SudoPumpkin commented on page-objects/components/HomePage.ts
> +
Yes and it makes it easy to update/maintain the tests when selectors in the interface are updated.

2022-09-22 20:58 UTC, adamgall commented
> I was able to fix this with `npx playwright install` between steps 3/4, though it seems like `npm i` should have covered this? I'm not really sure.

@herbig I ran into the same thing. I see that @SudoPumpkin added this step into the instructions in this PR, but I agree that running `npx playwright install` after doing a basic `npm install` seems weird. I was able to "fix" this by adding `playwright` to the package.json file as an additional `devDependency`.

2022-09-22 20:59 UTC, Da-Colon commented
o weird I didn't have to do npx playwright install