Test actions
decent-dao/fractal-interface pull request #518
Opened 2022-09-29 16:13 UTC by SudoPumpkin

## Description

This update contains Github Actions automated framework . Github actions will automatically create a .env.local file with a  TESTING_ALCHEMY_API_KEY secret stored in GitHub and place the file in the ./docker directory. It will then run the webapp(fractal-interface) and blockchain via Docker. 
After all of that it waits for the localhost to finish loading, then installs and runs (2)Playwright tests in (3)different browser types. (_Chromium, Firefox and Webkit._)
The first test navigates to the localhost, the other makes sure the wallet is connected. They run independently in parallel.  

This all occurs on the push of branches: 'master' and 'develop' as well as _any_ pull request.

An HTML report as well as video and screenshots are provided via a downloadable zip file at the end of the actions job report titled "playwright-report". 
_Open screenshots/videos prior to trying to access them via the HTML report as they are 'zipped'._ 

Current total run time is: >8  mins

![image](https://user-images.githubusercontent.com/86701852/193082781-f55c213f-12f5-4bff-9fab-60a860630b2e.png)

## Notes

Please reference the 'README.md' file in the root of the project to review how clear the setup steps are.

2022-09-29 16:19 UTC, adamgall commented on page-objects/Helpers/custom.ts
> +}
Doesn't seem like this file is being used. Can it be removed?

2022-09-29 16:28 UTC, adamgall requested changes

2022-09-29 16:28 UTC, adamgall commented on .github/workflows/playwright.yml
> +    timeout-minutes: 60
This seems like a really long timeout. I don't want to wait an hour if something has gotten stuck. Can this be reduced to, idk, like 5 mins?

2022-09-29 16:28 UTC, adamgall commented on .github/workflows/playwright.yml
> +  pull_request:
To start, let's just make it so that this workflow runs on all PRs, and that's it. We'll expand its footprint later.

2022-09-29 16:28 UTC, adamgall commented on .github/workflows/playwright.yml
> +        node-version: '16.x'
Please set the node version based on the `.nvmrc` file at the root of the project. See the other github workflow actions for an example of how to do that.

2022-09-29 16:28 UTC, adamgall commented on .github/workflows/playwright.yml
> +          touch .env.tests.local
This line is unnecessary, can be removed.

2022-09-29 16:28 UTC, adamgall commented on .github/workflows/playwright.yml
> +    - name: create env file
Please use proper casing for the name of this step, since other steps use proper casing in their names.

2022-09-29 16:28 UTC, adamgall commented on .github/workflows/playwright.yml
> +      run: npx playwright install --with-deps
I believe that this step is unnecessary, because of the existence of the `playwright` dependency in the `devDependencies` section of `package.json`.

2022-09-29 16:28 UTC, adamgall commented on .github/workflows/playwright.yml
> +        interval: 500
Eh, I'd suggest to delete these custom config values and just rely on the defaults (indicated here: https://github.com/nev7n/wait_for_response#timeout, and here: https://github.com/nev7n/wait_for_response#interval)

2022-09-29 16:28 UTC, adamgall commented on .github/workflows/playwright.yml
> +      run: npx playwright test
Please use the run script defined in `package.json` for this: `npm run tests`.

Reason being, you + devs running tests locally, and the CI system running tests in Github, should run the _same tests_. If everyone just defaults to `npm run tests` then we can assure that happens.

2022-09-29 16:41 UTC, Da-Colon commented on .github/workflows/playwright.yml
> +  pull_request:
So you don't want this to run right now when things are merged into develop and master. only on pull_request creation?

@SudoPumpkin We may need to check and see what `pull_request` covers. Just Creation? and/or pushing and updates to.

2022-09-29 16:44 UTC, adamgall commented on .github/workflows/playwright.yml
> +  pull_request:
Hm, you're right.

Maybe it is a good idea to run these tests whenever code is merged into `develop`. 

I don't know if it makes sense to run these on `master`, though, because currently Goerli is forked for the test suite, and we should probably fork Mainnet for production webapp testing.

2022-09-29 16:58 UTC, SudoPumpkin commented on .github/workflows/playwright.yml
> +      run: npx playwright install --with-deps
So, yoinking this will not install all browser types. Webkit tests will fail if you remove that. 'npx playwright install --with-deps'.

2022-09-29 17:17 UTC, SudoPumpkin commented on page-objects/Helpers/custom.ts
> +}
_yoinked_

2022-09-29 17:21 UTC, SudoPumpkin commented on .github/workflows/playwright.yml
> +    timeout-minutes: 60
Updated to 5 mins

2022-09-29 17:23 UTC, SudoPumpkin commented on .github/workflows/playwright.yml
> +          touch .env.tests.local
_No touching_ on line 23 - updated.

2022-09-29 17:24 UTC, adamgall commented on .github/workflows/playwright.yml
> +      run: npx playwright install --with-deps
The More I Know!

2022-09-29 17:25 UTC, SudoPumpkin commented on .github/workflows/playwright.yml
> +    - name: create env file
Capital 'C' updated on line 20

2022-09-29 17:28 UTC, SudoPumpkin commented on .github/workflows/playwright.yml
> +      run: npx playwright test
Updated line 37 to `npm run tests`

2022-09-29 17:39 UTC, SudoPumpkin commented on .github/workflows/playwright.yml
> +    timeout-minutes: 60
Changed to 20 mins, that setting is the entire runtime, not on failure.

2022-09-29 18:45 UTC, SudoPumpkin commented on .github/workflows/playwright.yml
> +        node-version: '16.x'
Updated

2022-09-29 18:49 UTC, SudoPumpkin commented on .github/workflows/playwright.yml
> +      if: always()
@adamgall I've seen it written this way in a number of examples across the _internets._ 
Here's one:
- https://playwright.dev/docs/ci-intro

2022-09-29 18:55 UTC, adamgall commented on .github/workflows/playwright.yml
> +      if: always()
oh well ok then! as long as it works

2022-09-29 19:01 UTC, SudoPumpkin commented on .github/workflows/playwright.yml
> +  pull_request:
So, we're removing master branch?

2022-09-29 19:05 UTC, adamgall commented on .github/workflows/playwright.yml
> +  pull_request:
@SudoPumpkin yes please :)

2022-09-29 19:11 UTC, SudoPumpkin commented on .github/workflows/playwright.yml
> +        interval: 500
custom values removed

2022-09-29 19:15 UTC, SudoPumpkin commented on .github/workflows/playwright.yml
> +  pull_request:
Master branched removed.

2022-09-29 20:05 UTC, adamgall requested changes

2022-09-29 20:05 UTC, adamgall commented on README.md
> +Test results for each test on each browser type will be output into the ![playwright-report](./playwright-report/) (HTML) and ![test-results](./test-results/)(screenshots and videos) folders.
These links display as broken, since they're not images. Remove the `!`s.

![Screen Shot 2022-09-29 at 4 00 49 PM](https://user-images.githubusercontent.com/706929/193130272-6d35ba40-83c5-4ed1-ba24-b34084b11a6f.png)

2022-09-29 20:05 UTC, adamgall commented on docker/README.md
>  - `.env.tests` example to keeps secrets, secret. This file will need to be manually created with the following variable
This file does not need to be manually created, it exists in the repo.

2022-09-29 20:05 UTC, adamgall commented on docker/README.md
>  $ docker compose build`
There's an erroneous backtick at the end of this command

2022-09-30 01:12 UTC, herbig commented on playwright.config.ts
> -  forbidOnly: !!process.env.CI,
this seems useful to keep in? is there a reason that was deleted?

2022-09-30 01:14 UTC, herbig commented on docker/README.md
>  $ docker compose build`
geez good catch

2022-09-30 01:14 UTC, adamgall commented on playwright.config.ts
> -  forbidOnly: !!process.env.CI,
Good point, I agree.

2022-09-30 01:20 UTC, herbig commented on README.md
> +$ git clone ...
Hopefully folks reading a readme can figure this out, but still might be helpful to have the full `git clone https://github.com/decent-dao/fractal-interface.git`, or just `git clone {repository url}`

2022-09-30 01:22 UTC, herbig commented on README.md
> +Change to correct node version
Minor point, but I would clarify it as `Node.js` just to be explicit

2022-09-30 01:26 UTC, herbig commented on README.md
> +  ![Docker README](./docker/README.md)
Also related to this, but could docker be capitalized..

2022-09-30 01:28 UTC, herbig commented on README.md
> +Once Docker has been installed and setup, you can run the containers by running
Another grammar police thing, `setup` is a noun, whereas the verb form is `set up`, please don't hate me...

2022-09-30 01:33 UTC, herbig commented on README.md
> +The "dev" environment tracks the `develop` branch, and the "prod" environment tracks the `master` branch.
@adamgall not related to this PR, but maybe for consistency we could think about renaming the `master` branch to `production`

2022-09-30 01:37 UTC, herbig commented on docker/README.md
> +1.) You'll need to a free Alchemy API key for a Goerli project from https://www.alchemy.com/.
Also "need to **get**"

2022-09-30 02:13 UTC, Da-Colon commented on README.md
> +$ npx playwright test tests/000nameOfTest.spec.ts
This was a change I originally requested. I recommended adding the numbers `000-` to 'sort'  the tests. There are more programatic ways we can look into this and just remove the numbers for now if it makes sense to

2022-09-30 02:15 UTC, adamgall commented on README.md
> +$ npx playwright test tests/000nameOfTest.spec.ts
I think @herbig is suggesting to just remove these numbers from this example snippet, not the patters in place for all of the real files.

But a question I have on this topic: why do we care about sorting these test files (in their directory) anyway?

2022-09-30 02:19 UTC, Da-Colon commented on README.md
> +$ git clone ...
yeah that makes sense, I did not want to pigeon hole to git or https. I'm not opposed to `{respository url}`

2022-09-30 02:24 UTC, Da-Colon commented on README.md
> +$ npx playwright test tests/000nameOfTest.spec.ts
Oh I see. as far as numbers mostly personal preference. I like tests to run from top down of the app. but since learning more about playwright these tests are ran in parallel to each other, and order really doesn't matter.

2022-09-30 02:25 UTC, herbig commented on README.md
> +$ git clone ...
yeah good call

2022-09-30 02:28 UTC, herbig commented on README.md
> +$ npx playwright test tests/000nameOfTest.spec.ts
yeah, numbers to sort them seems perfectly fine to me if you want some visual order, just wanted to remove the numbers from the example, since the numbers are part of the name, if that makes sense

2022-09-30 02:33 UTC, Da-Colon commented on README.md
> +$ npx playwright test tests/000nameOfTest.spec.ts
yeah for sure what your saying for the README makes sense

2022-09-30 02:35 UTC, Da-Colon approved these changes
No additional comments from me, leaving my approval for when other comments are addressed. This is great 🚀

2022-10-03 16:41 UTC, SudoPumpkin commented on README.md
> +     - workflow: [./.github/workflows/release-ipfs-dev.yaml](./.github/workflows/release-ipfs-dev.yaml)
Fixed

2022-10-03 18:27 UTC, SudoPumpkin commented on README.md
> +     - workflow: [./.github/workflows/release-ipfs-prod.yaml](./.github/workflows/release-ipfs-prod).
Fixed

2022-10-03 18:30 UTC, SudoPumpkin commented on README.md
> +  ![Docker README](./docker/README.md)
Fixed and Fixed

2022-10-03 18:54 UTC, SudoPumpkin commented on README.md
> +Test results for each test on each browser type will be output into the ![playwright-report](./playwright-report/) (HTML) and ![test-results](./test-results/)(screenshots and videos) folders.
Fixed

2022-10-03 18:54 UTC, SudoPumpkin commented on README.md
> +Example:
Fixed

2022-10-03 19:09 UTC, SudoPumpkin commented on docker/README.md
> +1.) You'll need to a free Alchemy API key for a Goerli project from https://www.alchemy.com/.
Fixed

2022-10-03 19:11 UTC, SudoPumpkin commented on docker/README.md
>  $ docker compose build`
Fixed

2022-10-03 19:20 UTC, SudoPumpkin commented on playwright.config.ts
> -  forbidOnly: !!process.env.CI,
Here I just yoinked anything extra to make sure the framework worked. I'll add it back.  
Fixed

2022-10-03 19:50 UTC, SudoPumpkin commented on README.md
> +$ git clone ...
Updated

2022-10-03 20:02 UTC, SudoPumpkin commented on README.md
> +Once Docker has been installed and setup, you can run the containers by running
Updated

2022-10-03 20:07 UTC, SudoPumpkin commented on README.md
> +$ npx playwright test tests/000nameOfTest.spec.ts
Updated

2022-10-04 00:15 UTC, SudoPumpkin commented
Ah, I am just waiting on a response from David on the '.env.tests' bit, if he wants that removed or updated to state the user should manually create a '.env.tests.local' file instead. 
![image](https://user-images.githubusercontent.com/86701852/193707453-46f329e5-6946-4ce8-b3fc-324417727928.png)

2022-10-04 00:44 UTC, SudoPumpkin commented
All the comments have been adjusted/fixed.

2022-10-04 01:12 UTC, adamgall commented on README.md
> +To run all tests in all 3 browser types(Chromium, Firefox, Webkit) use the following command in a new terminal within the fractal-interface project:
Fixed commit https://github.com/decent-dao/fractal-interface/pull/518/commits/5adc951369a2345d7581c3e5d3f20a4498b3b6a2

2022-10-04 01:13 UTC, adamgall commented on README.md
> +$ npx playwright test
Fixed in commit https://github.com/decent-dao/fractal-interface/pull/518/commits/03e359daf786516dbbdd57aabdb6bb03059a1d1e

2022-10-04 01:13 UTC, adamgall commented on README.md
> +--project=browserType
Fixed in commit https://github.com/decent-dao/fractal-interface/pull/518/commits/5adc951369a2345d7581c3e5d3f20a4498b3b6a2

2022-10-04 01:15 UTC, adamgall commented on README.md
> +     - netlify: https://app.netlify.com/sites/fractal-framework-interface-dev/settings/deploys#environment
I wasn't satisfied with the results of this, fixed it myself in commit https://github.com/decent-dao/fractal-interface/pull/518/commits/1a0bf1acbb453b7d7375525c920adeed2138cf22

2022-10-04 01:15 UTC, adamgall commented on README.md
> +     - workflow: [./.github/workflows/release-ipfs-dev.yaml](./.github/workflows/release-ipfs-dev.yaml)
I wasn't satisfied with the results of this, fixed it myself in commit https://github.com/decent-dao/fractal-interface/pull/518/commits/1a0bf1acbb453b7d7375525c920adeed2138cf22

2022-10-04 01:16 UTC, adamgall commented on README.md
> +     - workflow: [./.github/workflows/release-ipfs-prod.yaml](./.github/workflows/release-ipfs-prod).
I wasn't satisfied with the results of this, fixed it myself in commit https://github.com/decent-dao/fractal-interface/pull/518/commits/1a0bf1acbb453b7d7375525c920adeed2138cf22

2022-10-04 01:23 UTC, adamgall approved these changes

2022-10-04 01:32 UTC, adamgall requested changes
One of the two tests fails.

2022-10-04 01:32 UTC, adamgall commented on tests/002confirmWalletConnect.spec.ts
>    await page.locator('button[role="menuitem"]:has-text("Connect Wallet")').click();
This line of this test fails. Can it please be fixed?

2022-10-04 01:32 UTC, adamgall commented on tests/002confirmWalletConnect.spec.ts
>    await page.locator('button[role="menuitem"]:has-text("Connect Wallet")').click();
I fixed it in commit https://github.com/decent-dao/fractal-interface/pull/518/commits/52f102c5e223d326ae6d221dd638f0d0f5607d88

2022-10-04 01:40 UTC, adamgall approved these changes
Tests pass, things look good 🙌

2022-10-04 13:04 UTC, herbig approved these changes
good work, let's gooooo

2022-10-04 14:17 UTC, merged