Playwright tests - Parent DAO Creation
decent-dao/fractal-interface pull request #536
Opened 2022-10-10 16:52 UTC by SudoPumpkin

## Description

- Several selectors have been updated in the Fractal app to aid in solid test results. 
- A new test to create a 1:1 Gnosis Parent DAO has been created. 
- Test 002 has been updated with a delay. 

## Notes

Playwright needs to be listed in the dependencies of the package.json due to how Playwright references imports. That's why it's been added. 

## Issue (if applicable)

A manual delay was added to allow the app and local wallet to be loaded with multiple workers running at the same time.

## Testing

`npm run tests
`
## Screenshots (if applicable)

2022-10-10 17:08 UTC, adamgall requested changes

2022-10-10 17:08 UTC, adamgall commented on package.json
> +    "@playwright/test": "^1.26.0",
Please put this in alphabetical order in the dependency list

2022-10-11 16:41 UTC, SudoPumpkin commented on package.json
> +    "@playwright/test": "^1.26.0",
Done. =)

2022-10-11 17:00 UTC, adamgall reviewed
Left some comments

2022-10-11 17:00 UTC, adamgall commented on src/components/ui/Header/MenuItems.tsx
> +        data-testid={testId}
Is there a reason why this attribute isn't just called `id`?

2022-10-11 17:00 UTC, adamgall commented on src/components/ui/Header/MenuItems.tsx
> +        data-testid={testId}
Is there a reason why this attribute isn't just called `id`?

2022-10-11 17:22 UTC, adamgall commented on src/components/ui/Header/MenuItems.tsx
> +        data-testid={testId}
i got an answer -- because sometimes React overwrites the `id` attribute

2022-10-11 17:22 UTC, adamgall commented on src/components/ui/Header/MenuItems.tsx
> +        data-testid={testId}
i got an answer -- because sometimes React overwrites the `id` attribute

2022-10-11 17:22 UTC, adamgall commented on src/components/ui/Header/MenuItems.tsx
> +        data-testid={testId}
i got an answer -- because sometimes React overwrites the `id` attribute

2022-10-11 17:37 UTC, adamgall commented on playwright.config.ts
> +    timeout: 15000
I got an answer, it's because stuff sucks and sometimes you just gotta wait a lil longer

2022-10-12 13:39 UTC, herbig commented on tests/002confirmWalletConnect.spec.ts
>  import { expect, test } from '@playwright/test';
not a change from this PR, but it might be good to rename this `002confirmWalletConnected`, just so it's not confused with being a test for WalletConnect the wallet brand.

2022-10-12 13:50 UTC, herbig commented on page-objects/components/Navbuttons.ts
> +      case 'Return to Homepage':
Is there a reason for having these designated with string descriptions rather than having a separate method for each clickable item on screen?

I feel like having `clickReturnToHomePage();`, `clickHeaderConnectWallet();`, etc, would be cleaner than a large switch statement with new strings you need to remember when writing the tests.   You also get autocomplete this way.

2022-10-12 13:51 UTC, herbig commented on tests/003createParentDao.spec.ts
> +    await delay(3000);
can we put this delay in the `visit();` methods of each page instead?

2022-10-12 13:54 UTC, Da-Colon approved these changes
Approved pending Mike's comments

2022-10-12 14:39 UTC, SudoPumpkin commented on tests/002confirmWalletConnect.spec.ts
>  import { expect, test } from '@playwright/test';
I can rename this to ```002connectToWallet```, does this work?

2022-10-12 14:59 UTC, SudoPumpkin commented on tests/003createParentDao.spec.ts
> +    await delay(1500);
If the current page has already reached the required state, it resolves the wait immediately. So here no particular state is defined so it's just waiting until load is completed to continue. I can remove this and increase the delay time to '2000'. I had this here to negate a minor amount of ms in wait time compared to a hard increased delay wait. I can totally just add another 500ms(0.5secs) to the present '1500'(1.5secs) to make it '2000'(2secs) and yoink line 25.

2022-10-12 15:07 UTC, SudoPumpkin commented on page-objects/components/Navbuttons.ts
> +      case 'Return to Homepage':
With similar action components this is a common method for e2e test scripting. It's easier for code readability.  I can change it however to be similar to HomePage.ts.

2022-10-12 18:25 UTC, SudoPumpkin commented on tests/003createParentDao.spec.ts
> +    await delay(1500);
Actually I am leaving line 25 in there. I removed line 25 locally, and when the tests ran in parallel multiple times they become flaky. A test will random fail in different browser.

2022-10-12 18:26 UTC, herbig commented on tests/002confirmWalletConnect.spec.ts
>  import { expect, test } from '@playwright/test';
yeah that sounds good, I like the distinction

2022-10-12 18:30 UTC, herbig commented on page-objects/components/Navbuttons.ts
> +      case 'Return to Homepage':
cool cool, sounds good, I defer to you on that, just curious what's common practice

2022-10-12 18:33 UTC, herbig commented on tests/003createParentDao.spec.ts
> +    await delay(1500);
sounds good.  I'd just like to better understand why the hardcoded waits everywhere are necessary, and what the difference is when running locally

2022-10-12 18:36 UTC, herbig commented on tests/003createParentDao.spec.ts
> +    inputFields.fillField('Insert Fractal Name');
that makes sense!

2022-10-12 18:39 UTC, SudoPumpkin commented on tests/003createParentDao.spec.ts
> +    await delay(3000);
No idea, but it can't find the menu 'connect' option without it.

2022-10-12 19:45 UTC, SudoPumpkin commented on tests/003createParentDao.spec.ts
> +    await delay(1500);
Locally it runs with up to 8 workers in parallel while in CI it runs 1 worker. These 8 workers are all running at the same time. Each browser behaves a little bit differently from one another with load times of content with the Fractal app. Now, let's add the local wallet connecting to the app and local blockchain on top of that varied browser behavior. 
The local provider checks to see if the network is active before it connects. When the app loads, it loads this twice(because react in dev). In the middle of this async call the test goes and clicks the connect button. The promise is then returned and interrupts the other state setting. The other 'fallback' provider is not async, there is are promises.

Long story short, sometimes the wallet isn't ready for Playwright to click 'connect' and it 1/2 connects. These hard delays force Playwright to wait for all the pieces to be loaded.

2022-10-13 16:19 UTC, merged