V1 design/header cleanup
decent-dao/fractal-interface pull request #566
Opened 2022-10-17 19:12 UTC by Da-Colon

## Description

## Notes

## Issue (if applicable)

## Testing

## Screenshots (if applicable)

2022-10-17 19:40 UTC, Da-Colon commented on src/App.tsx
> -    testId: 'audit:accept',
One thing I noticed in the tests that `:` isn't allowed as a valid Selector. so moving forward moving to camelCase with a intent to keep it `pageComponent-descriptor`

2022-10-17 19:40 UTC, Da-Colon commented on src/i18n/index.ts
> +    walletMenu: WALLET_MENU_ES,
I went ahead and created new json files specifically for the new wallet menu. wasn't wanting to touch the current setup, until we merge feature into develop. 

@herbig thoughts here?

2022-10-17 19:40 UTC, Da-Colon commented on tests/001navigateToFractal.spec.ts
> +  await expect(headerWalletMenu).toBeVisible();
@SudoPumpkin I moved the selector to the menu button itself. The pervious library made this more difficult than it needed to be.

2022-10-17 19:40 UTC, Da-Colon commented on tests/002confirmWalletConnect.spec.ts
> +  await page.locator('button[data-testid=accountMenu-connect]').click();
Let's default to using `data-testid` moving forward to select things. Unless its a 3rd party thing we need to lock on to. but selecting something should start with a testid then find the needed button as needed (unless the selector is on a button)

2022-10-17 19:40 UTC, Da-Colon commented on tests/002confirmWalletConnect.spec.ts
> +  await expect(accountDisplay).toContainText('0xf39F...2266');
Might want to think about updating this test to just check that the Account menu test is no longer 'Connect Wallet' as we don't want this test to depend on text that we don't fully control appearing.

2022-10-17 19:40 UTC, Da-Colon commented on tests/003createParentDao.spec.ts
> +test.describe.skip('DAO Creation', () => {
skip

2022-10-17 20:58 UTC, Da-Colon commented on tests/002confirmWalletConnect.spec.ts
> -  await delay(5000);
I think I may have solved this issue with the lastest update to the wallet-provider that caused the need for this delay. We will know for sure when more tests are added/enabled.

2022-10-17 22:00 UTC, SudoPumpkin commented on tests/002confirmWalletConnect.spec.ts
> -  await delay(5000);
Awww yeah. 🤞

2022-10-18 00:09 UTC, herbig commented on tests/002confirmWalletConnect.spec.ts
> +  await expect(accountDisplay).toContainText('0xf39F...2266');
@SudoPumpkin we'll have to look at tests once we start pushing these changes, since they're all going to break in different ways..

2022-10-18 00:10 UTC, herbig commented on tests/002confirmWalletConnect.spec.ts
> +  await page.locator('button[data-testid=accountMenu-connect]').click();
@SudoPumpkin

2022-10-18 00:16 UTC, herbig commented on src/i18n/locales/es/walletMenu.json
> +  "wallet": "Cartera"
Unless we're pretty sure about translations (like @mudrila with Ukrainian) we should probably not include our own or direct google translations, since context can change things.

In this example, `cartera` directly translates to `wallet`, but `crypto wallet` uses the word `billetera`, so I'm not really sure which word makes more sense to native speakers.

I added Google translations for the menu just as a way to test, but we should probably also remove those as well.

Once the design is finalized and we have a copy review with design, we should be able to find community translators who would love to help us out.

2022-10-18 00:19 UTC, herbig commented on src/i18n/index.ts
> +    walletMenu: WALLET_MENU_ES,
I think it's fine to change the current files, and add these to maybe menu.json.

We should only ever be adding to the English (en) json file, and let translations be done via community translators using the scripts we have now, which will help keep them organized in the same order and keep us from missing translations.

2022-10-18 00:20 UTC, herbig requested changes
Looks good, just a few more strings that can be moved to json files.

2022-10-18 01:47 UTC, Da-Colon commented on src/i18n/locales/es/walletMenu.json
> +  "wallet": "Cartera"
for sure, I've removed this file

2022-10-19 17:14 UTC, herbig approved these changes
🚢

2022-10-19 18:03 UTC, merged