V1 Design | header favorites
decent-dao/fractal-interface pull request #598
Opened 2022-10-26 22:54 UTC by Da-Colon

## Description
Implements Favorites Menu

## Notes
-  useDisplayName hook will need to be updated when the DAO name register contract is implemented

## Issue / Notion doc (if applicable)

## Testing

## Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/38386583/198153729-aef53d13-7500-449a-8b4b-62a7be33f1aa.png)

2022-10-26 22:56 UTC, Da-Colon commented on src/components/menus/FavoritesMenu/FavoritesList.tsx
> +              }}
default scroll looked really bad here. I will look into adding a class to the theme that can be used instead

2022-10-27 17:32 UTC, herbig commented
@Da-Colon is there a way I can set a DAO as a favorite in this branch?

2022-10-27 17:45 UTC, herbig requested changes

2022-10-27 17:45 UTC, herbig commented on src/components/menus/FavoritesMenu/index.tsx
> +              Favorites
should use `titleFavorites` here

2022-10-27 17:51 UTC, Da-Colon commented
> @Da-Colon is there a way I can set a DAO as a favorite in this branch?

Not yet. I believe this will be added on the Dashboard when thats complete

2022-10-27 17:54 UTC, Da-Colon commented on src/components/menus/FavoritesMenu/index.tsx
> +              Favorites
done.

2022-10-31 14:12 UTC, merged