Fractal welcome / home page
decent-dao/fractal-interface pull request #604
Opened 2022-10-28 00:54 UTC by herbig

## Description

Implements the redesigned Home/Welcome Page:

https://www.figma.com/file/uRV3Nfowdzt5CknW1FgUkQ/%F0%9F%93%9A-Fractal-Design-System-%7C-Base-Components-%7C-October-2022?node-id=504%3A415

## Issue / Notion doc (if applicable)

Closes https://github.com/decent-dao/fractal-interface/issues/601

## Testing

This page has two states, depending on whether the wallet is connected/disconnected.

Please test the button and view the text based on these two states.

1. Connected: button should go to DAO creation page
2. Disconnected: button should trigger wallet connection

## Screenshots (if applicable)
<img width="2033" alt="Screen Shot 2022-10-27 at 8 53 13 PM" src="https://user-images.githubusercontent.com/384559/198424355-6b155479-a7b0-4bec-b1c1-b8bdafe9f964.png">
<img width="2040" alt="Screen Shot 2022-10-27 at 8 53 22 PM" src="https://user-images.githubusercontent.com/384559/198424409-e34ac9a4-e96a-4c85-b11e-8ba0926e2502.png">

2022-10-28 01:01 UTC, herbig commented on src/pages/Home/index.tsx
> +            minWidth="auto"
@Da-Colon can we add `boxSize="1.5rem"` and `minWidth="auto"` as the defaults for these Decent UI components?

2022-10-28 01:02 UTC, herbig commented on src/pages/Home/index.tsx
> +        <Button
@Da-Colon the default font for the Button doesn't seem to be correct, it should be `Mono/text-base-mono/semibold `, but seems thinner than that to me.

2022-10-28 01:03 UTC, herbig commented on src/pages/Home/index.tsx
> +      >
@Da-Colon this felt janky to me, but I wanted to add padding the Chakra way.. Is there a way to extend Chakra components for like, the `IconWithText`, so I can get these props on there instead?

2022-10-28 01:04 UTC, herbig commented on src/pages/Home/index.tsx
> +        <Logo style={{ marginBottom: '3.5rem' }} />
Another janky feeling way to add margin since it's not a Chakra component, but maybe that's fine here?

2022-10-28 01:06 UTC, herbig commented on src/pages/Home/index.tsx
> +  icon: ReactI18NextChild;
honestly I'm not really sure what this class is, I tried using the base React component as the prop to pass in and got an error saying it expected a `ReactI18NextChild` so I changed it to that...

2022-10-28 01:09 UTC, herbig commented
FYI this is in draft since I'm planning to fix the test that broke, and fully flesh out tests for this screen as an example

2022-10-28 13:39 UTC, Da-Colon requested changes

2022-10-28 13:39 UTC, Da-Colon commented on src/pages/Home/index.tsx
> +            minWidth="auto"
why is minWith `auto`? icons are squares?

2022-10-28 13:39 UTC, Da-Colon commented on src/pages/Home/index.tsx
> +      >
you can use `px="1.25rem" if you wanted to keep this here. but see above comment on flex and gap

2022-10-28 13:39 UTC, Da-Colon commented on src/pages/Home/index.tsx
> +        <Logo style={{ marginBottom: '3.5rem' }} />
Use a <Image /> component from Chakra-UI

2022-10-28 13:39 UTC, Da-Colon commented on src/pages/Home/index.tsx
> +        <Button
I'll look into this. Just checked the code in the DS and it looks right. but I'll add a note to check and see whats computing

2022-10-28 13:39 UTC, Da-Colon commented on src/pages/Home/index.tsx
> +  icon: ReactI18NextChild;
ReactI18NextChild === ReactNode (but might be good to just use ReactNode here.

```ts
interface IconWithTextProps {
  icon: ReactNode;
  label: string;
  url: string;
  testid: string;
}
```
HSStack accepts a single child element. thats why it was originally throwing that weight error. I've wrapped the children in a <Fragment>

```ts
function IconWithText({ icon, label, url, testid }: IconWithTextProps) {
  return (
    <a
      data-testid={testid}
      href={url}
      rel="noreferrer noopener"
      target="_blank"
    >
      <HStack>
        <Fragment>
          {icon}
          <Text
            textStyle="text-button-md-semibold"
            color="gold.500"
          >
            {label}
          </Text>
        </Fragment>
      </HStack>
    </a>
  );
}
```

You can remove the fragment if you update this to just use a Flex component and gap (see below comment)

2022-10-28 18:47 UTC, herbig commented on src/pages/Home/index.tsx
> +  icon: ReactI18NextChild;
Awesome, changed to `ReactNode`, that makes more sense.

I don't think `HStack` requires a single child, it seems to work as expected with the two children I have, and the example shows it used that way:

https://chakra-ui.com/docs/components/stack

2022-10-28 18:48 UTC, herbig commented on src/pages/Home/index.tsx
> +            minWidth="auto"
Yeah, nice, that's not necessary, just from copying these icons where they were already used. Removed that prop.

2022-10-28 18:50 UTC, herbig commented on src/pages/Home/index.tsx
> +        <Logo style={{ marginBottom: '3.5rem' }} />
Is there a component for displaying SVGs? I couldn't find that in the docs... but seems like that's a common use

2022-10-31 02:06 UTC, herbig commented on src/components/constants.ts
> +  'https://docs.fractalframework.xyz/welcome-to-fractal/the-core-framework/developer-overview';
I didn't see an existing "constants" for URLs such as these, but let me know if this should go elsewhere.

2022-10-31 02:08 UTC, herbig commented on src/i18n/locales/en/daoCreate.json
> +    "homeButtonCreate": "Create a Fractal",
Just a note that our json files should probably be refactored as well with the redesign, lots of strings no longer make sense in the file they are in..

2022-10-31 02:09 UTC, herbig commented on src/i18n/locales/en/menu.json
> +    "discord": "Discord",
I'm not sure how to handle single words that shouldn't be translated.

I like the consistency of putting every string into the json files, on the other hand, this string word should never be translated.

But maybe there are actually other translations for brand words, like special Chinese characters or something? I have no idea.

2022-10-31 02:11 UTC, herbig commented on tests/home/connect-wallet.spec.ts
> +    const networkItem = await home.menuLocator(MenuItems.Network);
@Da-Colon I noticed you created a new NavPage here, but the way these page models are set up, `HomePage` is a `NavPage` itself, so you can click anything in the nav using a `HomePage`.

2022-10-31 02:11 UTC, herbig commented on tests/models/NavPage.ts
> +export abstract class NavPage extends FractalPage {
This should be abstract, only extended by a page model that has side navigation.

2022-10-31 02:12 UTC, herbig commented on tests/models/FractalPage.ts
> +export abstract class FractalPage {
This should be abstract, extended by all page models in the Fractal app

2022-10-31 02:13 UTC, herbig commented on tests/models/HomePage.ts
> +    return this.newTab(this.page.click('[data-testid=home-linkFAQ]'));
These use the `newTab` method from `FractalPage`, to handle returning the new tab `Page` object that clicking them creates

2022-10-31 14:48 UTC, Da-Colon commented on src/pages/Home/index.tsx
> +        <Logo style={{ marginBottom: '3.5rem' }} />
O yikes, I'm sure. I thought I said which one to use. `Image` can be used for this https://chakra-ui.com/docs/components/image/usage

2022-10-31 14:49 UTC, Da-Colon commented on src/components/constants.ts
> +  'https://docs.fractalframework.xyz/welcome-to-fractal/the-core-framework/developer-overview';
wanna do a `src/constants/index.ts` and have a `url.ts` file with these links

2022-10-31 14:50 UTC, Da-Colon commented on src/i18n/locales/en/menu.json
> +    "discord": "Discord",
yeah I was thinking that too. thats a good question. Since Discord is a company name probably should be in the `constants` file versus translation?

2022-10-31 14:51 UTC, Da-Colon commented on tests/home/connect-wallet.spec.ts
> +    const networkItem = await home.menuLocator(MenuItems.Network);
o nice, okay cool

2022-10-31 14:53 UTC, Da-Colon reviewed
Left some comments, but overall looking good

2022-10-31 20:25 UTC, herbig commented on src/components/constants.ts
> +  'https://docs.fractalframework.xyz/welcome-to-fractal/the-core-framework/developer-overview';
yeah sounds good

2022-10-31 20:26 UTC, herbig commented on src/i18n/locales/en/menu.json
> +    "discord": "Discord",
I'll leave here for now, since I'm not exactly sure there cant' be a different translation for it..

2022-10-31 20:36 UTC, herbig commented on src/pages/Home/index.tsx
> +        <Logo style={{ marginBottom: '3.5rem' }} />
updated

2022-11-01 15:15 UTC, Da-Colon approved these changes

2022-11-01 16:13 UTC, herbig commented on src/pages/Home/index.tsx
> +          {account ? t('homeSubTitleConnected') : t('homeSubTitleDisconnected')}
good call, updated

2022-11-01 16:15 UTC, merged