Gnosis module types
decent-dao/fractal-interface pull request #606
Opened 2022-10-28 14:01 UTC by tbwebb22

## Description
This PR adds in functionality for the webapp to detect the type of modules that are attached to a Gnosis Safe DAO.

## Notes
 This is done by querying events from the GnosisModuleProxyFactory. The module that is being inspected is checked to see if an event was emitted from that factory, if so, get the implementation contract address, and see if that matches any of our implementation contract addresses. If it does, we know the module is of that type. If not, we assign the "unknown" module type.

## Issue / Notion doc (if applicable)

## Testing

## Screenshots (if applicable)

2022-10-28 18:08 UTC, herbig commented on src/controller/Modules/types/enums.ts
> +}
a small nitpick, but do we even need the text descriptions for this? It seems like the enum name is plenty of context

2022-10-28 18:09 UTC, herbig commented on src/controller/Modules/types/state.ts
> +  moduleType: GnosisModuleTypes;
The enum should probably be named the singular `GnosisModuleType`, so it's clear you're sending a single type rather than multiple

2022-10-28 18:15 UTC, herbig commented on src/providers/fractal/hooks/useGnosisModuleTypes.ts
> +    fractalModuleMastercopyContract,
we do `masterCopy` for the other usages of this term, so would be good to change to `usulMasterCopyContract` / `fractalModuleMasterCopyContract` for these as well

2022-10-28 18:36 UTC, herbig commented on src/providers/fractal/hooks/useGnosisModuleTypes.ts
> +    unknownModule,
I'm confused by the "unknown" here. Can't there be multiple unknown modules?

2022-10-28 18:37 UTC, herbig commented on src/providers/fractal/hooks/useGnosisModuleTypes.ts
> +    unknownModule,
Also, is it possible to attach multiple Usul modules?

2022-10-28 18:37 UTC, herbig requested changes
Some tweaks and discussion, but looking awesome

2022-10-28 20:19 UTC, sethhrbek commented on src/providers/fractal/hooks/useGnosisModuleTypes.ts
> +    const getMasterCopyAddress = (proxyAddress: string) => {
could help to add return type here -- `Promise<string>`

2022-10-28 20:19 UTC, sethhrbek commented on src/providers/fractal/hooks/useGnosisModuleTypes.ts
> +            } as IGnosisModuleData;
This could be shortened to:

```
const moduleType = 
    masterCopyAddress === usulMastercopyContract.address ? GnosisModuleTypes.USUL :
    masterCopyAddress === fractalModuleMastercopyContract.address ? GnosisModuleTypes.FRACTAL :
    GnosisModuleTypes.UNKNOWN;
    
return {
   moduleAddress,
   moduleType
} as IGnosisModuleData;
```

2022-10-28 20:58 UTC, herbig commented on src/pages/Dao/index.tsx
> +      <div>module types: {JSON.stringify(modules)}</div>
yeah this is just an example dump to the UI to see that it's working, not the final display
https://user-images.githubusercontent.com/84364476/198634722-af306601-34e9-4b80-8c90-a68c29cf3d69.png

2022-10-31 14:47 UTC, tbwebb22 commented on src/controller/Modules/types/enums.ts
> +}
This pattern I followed from the legacy MVD code for module types. I think the purpose is to give a human readable string for the frontend to use. But yeah, maybe makes sense to just include this human readable string in the module object itself.

2022-10-31 14:57 UTC, tbwebb22 commented on src/providers/fractal/hooks/useGnosisModuleTypes.ts
> +    unknownModule,
hmmm yeah this is a good point. I'm reconsidering the structure of these modules. An option I talked with @Da-Colon about is - the modules are just an array, that can contain any of the different module types. Thoughts on this?

2022-10-31 14:58 UTC, tbwebb22 commented on src/providers/fractal/hooks/useGnosisModuleTypes.ts
> +    unknownModule,
This would allow any arbitrary number of each type of module

2022-10-31 15:00 UTC, Da-Colon commented on src/hooks/useAddresses.ts
> +      !process.env.REACT_APP_FRACTAL_MODULE_MASTERCOPY_ADDRESSES
+1

2022-10-31 15:00 UTC, Da-Colon commented on src/hooks/useSafeContracts.ts
> +      setFractalModuleMastercopyContract(undefined);
Might be a cleanup for later but this is a lot of state setters. This should probably be updated into a reducer

2022-10-31 15:05 UTC, tbwebb22 commented on src/hooks/useAddresses.ts
> +      !process.env.REACT_APP_FRACTAL_MODULE_MASTERCOPY_ADDRESSES
yeah I do like that better, the .env is definitely getting pretty large. If we want to go this route, should probably be handled in a separate PR

2022-10-31 15:10 UTC, sethhrbek commented on src/hooks/useAddresses.ts
> +      !process.env.REACT_APP_FRACTAL_MODULE_MASTERCOPY_ADDRESSES
yeah 100% should be in a different PR

2022-10-31 15:14 UTC, tbwebb22 commented on src/hooks/useAddresses.ts
> +      !process.env.REACT_APP_FRACTAL_MODULE_MASTERCOPY_ADDRESSES
Created new issue for this: https://github.com/decent-dao/fractal-interface/issues/610

2022-10-31 16:10 UTC, tbwebb22 commented on src/providers/fractal/hooks/useGnosisModuleTypes.ts
> +    const getMasterCopyAddress = (proxyAddress: string) => {
Added this return type

2022-10-31 16:23 UTC, herbig commented on src/providers/fractal/hooks/useGnosisModuleTypes.ts
> +    unknownModule,
yeah an array makes more sense to me, and you'd iterate through and find the first usulModule or fractalModule

2022-10-31 16:53 UTC, tbwebb22 commented on src/providers/fractal/hooks/useGnosisModuleTypes.ts
> +            } as IGnosisModuleData;
Nice, just pushed up this change

2022-10-31 17:04 UTC, tbwebb22 commented on src/providers/fractal/hooks/useGnosisModuleTypes.ts
> +    fractalModuleMastercopyContract,
Cool, just pushed up this fix

2022-10-31 17:11 UTC, tbwebb22 commented on src/controller/Modules/types/state.ts
> +  moduleType: GnosisModuleTypes;
Pushed this change up

2022-10-31 18:33 UTC, tbwebb22 commented on src/providers/fractal/hooks/useGnosisModuleTypes.ts
> +    unknownModule,
Pushed this change up, the modules are now an array

2022-10-31 18:36 UTC, herbig approved these changes

2022-10-31 18:55 UTC, merged