initial treasury pass
decent-dao/fractal-interface pull request #642
Opened 2022-11-05 19:01 UTC by herbig

## Description

## Notes

## Issue / Notion doc (if applicable)

## Testing

## Screenshots (if applicable)

2022-11-05 19:05 UTC, herbig commented on src/assets/theme/index.ts
> +            color: 'chocolate.200',
@decent-dao/fractal I defined text variants her, but the more I think about it, the more I think these shouldn't be "InfoCard" specific.

We should go through the existing designs and come up with the short list of text variants in the app and define them here.

2022-11-05 19:06 UTC, herbig commented on src/assets/theme/index.ts
> +        borderColor: 'chocolate.400',
@Da-Colon I overrode the default `<Divider />` to use the color used in the header, which is a divider against no background.

Apparently Divider is one of the components you can't define "variants" of (see below for text variants).

2022-11-05 19:09 UTC, herbig commented on src/assets/theme/index.ts
> +            color: 'chocolate.200',
@xraystyle1980 do we have a short list of text variants in the designs?

I'm thinking something like:
Text small against a dark background
Text medium against dark
Text large against dark

Text small against no background (just app gradiant)
Medium
large

Something like that?

@decent-dao/fractal I would like to come up with definitions for these, so we can define them in code without having to add a series of properties inline each time, and we can tweak them all in one place if they change.

2022-11-05 19:10 UTC, herbig commented on src/components/ui/Header/PageHeader.tsx
> +function PageHeader({
@decent-dao/fractal @xraystyle1980 I defined a component for an "app page header" as given in the Treasury UI.

If we have headers for further pages, we should reuse this design.

2022-11-05 19:12 UTC, herbig commented on src/pages/DaoDashboard/Info/index.tsx
> +// @TODO where should this component live?
@Da-Colon I reused the `InfoCard` and added an optional title, since that's used in the Treasury page.

@xraystyle1980 there are existing titles in the DAO homepage for these, but they are different from the Treasury titles (smaller, with icons, no divider line).

I just want to confirm these should be different title types for these types of components, or can we make them identical is some way, to make the app more consistent?

2022-11-05 19:12 UTC, herbig commented on src/pages/Treasury/Assets.tsx
> +// 5. center align token image with text...
Stuff I still need to do to open this PR to review...

2022-11-05 19:14 UTC, herbig commented on src/pages/Treasury/index.tsx
> +          minWidth={{ sm: '100%', xl: '60%' }}
@Da-Colon I'm still baffled by some React stuff, I noticed you didn't use a total of 100% for the components in the DAO homepage?

Why does it look weird for these two rows if I used 60/40 split, rather than 60/30?

2022-11-06 10:45 UTC, Da-Colon commented on src/pages/DaoDashboard/Info/index.tsx
> +// @TODO where should this component live?
We will have some conflicts here as I've moved this to `components` and and renamed, as well as made a update myself. I'll make sure to capture this when it is merged.

2022-11-06 10:47 UTC, Da-Colon commented on src/pages/Treasury/index.tsx
> +          minWidth={{ sm: '100%', xl: '60%' }}
I've have since updated this a little. This puts a space on the side since the content is centered while also allowing for the boxes to continue to shrink to fit on smaller screens

2022-11-06 10:48 UTC, Da-Colon commented on src/assets/theme/index.ts
> +        borderColor: 'chocolate.400',
I can probably update the base theme at least. I'll add an issue to to this update default borderColor.

2022-11-06 10:52 UTC, Da-Colon commented on src/assets/theme/index.ts
> +            color: 'chocolate.200',
same as above, when we define these, I'll move this stuff to the library theme and update the release

2022-11-07 02:59 UTC, herbig commented on src/pages/DaoDashboard/Info/index.tsx
> +// @TODO where should this component live?
I reverted my changes and created a new component instead because it was sufficiently different from the dashboard cards, so we shouldn't have conflicts here anymore.

2022-11-07 03:01 UTC, herbig commented on src/assets/theme/index.ts
> +        borderColor: 'chocolate.400',
yeah updating the base theme rather than within here makes sense.

2022-11-07 22:09 UTC, herbig commented on src/components/ui/EtherscanLinkAddress.tsx
> +    </Link>
swapping out for the Chakra component

2022-11-08 05:15 UTC, herbig commented on src/utils/numberFormats.ts
> +export const formatCoin = (rawBalance: BigNumber | string, decimals?: number, symbol?: string) => {
commenting to link here

2022-11-08 17:45 UTC, Da-Colon commented on src/pages/Treasury/Assets.tsx
> +import TooltipWrapper from '../../components/ui/TooltipWrapper';
This component and the library it uses is not depreciated. There is a chakra library component for this.

2022-11-08 17:45 UTC, Da-Colon commented on src/pages/Treasury/Assets.tsx
> +import TooltipWrapper from '../../components/ui/TooltipWrapper';
This is also producing the error in the console of a `<div>` appearing as a child of `<p>` which isn't allowed (Text Components are `p` elements by default. you can you the `as` property to change in case you need a `Text` component but not it as a `p` element

2022-11-08 17:46 UTC, Da-Colon commented
![image](https://user-images.githubusercontent.com/38386583/200637813-4e32dfbf-eea6-40da-804d-e23831a13d7a.png)

Should we show `$0.00` under the transfer amount, (if fiat isn't available for goerli probably should just be 0.00. UI looks lonely without it

2022-11-08 20:52 UTC, Da-Colon requested changes
Could you extract some of the methods (utils) and other components out of the `Assets.tsx` and `Transactions.tsx` to make it a little smaller files.

2022-11-08 20:52 UTC, Da-Colon commented on src/pages/Treasury/Transactions.tsx
> +  }
I don't know if I have a suggestion but this switch statement feels weird out in the open. can this be a useCallback method or something?

2022-11-08 22:09 UTC, herbig commented on src/pages/Treasury/Transactions.tsx
> +  }
yeah, this spurred the discussion in Discord about classes/interfaces for data formatting.

2022-11-08 22:11 UTC, herbig commented
> Could you extract some of the methods (utils) and other components out of the `Assets.tsx` and `Transactions.tsx` to make it a little smaller files. I actually hadn't decided on whether to add this comment, so feel free to ignore, this could just be preference lol.

Yeah, I've tried to extract things we may likely reusing (like the gold address link), but I'm not sure there's much else we would want pulled out.

I would like to improve on the data formatting in some way, and have a central set of methods for getting common things like formatted price and such, as we're discussing in Discord

2022-11-08 22:13 UTC, herbig commented
> ![image](https://user-images.githubusercontent.com/38386583/200637813-4e32dfbf-eea6-40da-804d-e23831a13d7a.png)
> 
> Should we show `$0.00` under the transfer amount, (if fiat isn't available for goerli probably should just be 0.00. UI looks lonely without it

Yeah, I mentioned in the description, but this PR doesn't address the price in the transfers list, since the pricing data isn't returned in the Gnosis API here.

We'll have to use a different API for the historical price.  Coingecko has one that seems fine, but I figured I'd address that specific field in a followup PR, as this one was getting a bit large already.

2022-11-08 22:20 UTC, herbig commented on src/pages/Treasury/Assets.tsx
> +import TooltipWrapper from '../../components/ui/TooltipWrapper';
oh nice, yeah swapped this out for the chakra tooltip

2022-11-09 02:21 UTC, herbig commented
@Da-Colon this has been refactored quite a bit, and ready to review again

2022-11-11 04:00 UTC, Da-Colon requested changes
![image](https://user-images.githubusercontent.com/38386583/201260316-e0054bbb-e994-4df8-b475-3620b22daec8.png)

Should the top Title stay static as you scroll?

2022-11-11 04:03 UTC, Da-Colon commented on src/pages/Treasury/InfoBox.tsx
> +export function InfoBox({
can you move this (possibly combine/rename) to the `componentsui/containers`

2022-11-11 04:03 UTC, Da-Colon commented on src/pages/Treasury/utils.ts
> +export function useFormatTransfers(
can you move this to the hooks folder in its own file?

2022-11-11 04:04 UTC, Da-Colon commented on src/pages/Treasury/utils.ts
> +export function useFormatTransfers(
I guess the rest of the stuff in this file are duplicates types/methods?

2022-11-11 14:56 UTC, herbig commented
> ![image](https://user-images.githubusercontent.com/38386583/201260316-e0054bbb-e994-4df8-b475-3620b22daec8.png)
> 
> Should the top Title stay static as you scroll?

I don't think so.  It would be weird to have a top nav and a static title I think

2022-11-14 02:41 UTC, herbig commented on src/pages/Treasury/Assets.tsx
> +            h="0.83rem"
@Da-Colon isn't that a 13.33px icon with 2.67px padding though?

2022-11-14 02:42 UTC, herbig commented on src/pages/Treasury/InfoBox.tsx
> +export function InfoBox({
Renamed to `TitledInfoBox` and moved to containers!

2022-11-14 02:45 UTC, herbig commented on src/pages/Treasury/utils.ts
> +export function useFormatTransfers(
I split these two into their own files.

I also added a hooks folder in the treasury folder.  Does it make sense to pile all the hooks into one directory, even if they are single use, and specific to a certain page?

2022-11-14 02:47 UTC, herbig commented
@Da-Colon I refactored a bunch and did some other cleanup of this.

For the NFT, Eth, and token default icons, now I see what you were saying before about Icon vs. importing as SVG.

Is there a way I can get those SVGs from the library?  I'd like to use them as `fallbackSrc` for the images.

2022-11-14 02:48 UTC, herbig commented
@mudrila @tbwebb22 @christopherdancy could you guys this one one a look as well, I'd like to close this out

2022-11-14 03:07 UTC, Da-Colon commented
> Is there a way I can get those SVGs from the library? I'd like to use them as fallbackSrc for the images.

@herbig cool beans I'll take care of that and those available as SVGs as well, in the morning, get it in a release.

2022-11-14 03:08 UTC, Da-Colon commented on src/pages/Treasury/Assets.tsx
> +            h="0.83rem"
@herbig the padding and such is provided by the SVG itself.

2022-11-14 15:14 UTC, herbig commented on src/pages/Treasury/Assets.tsx
> +            h="0.83rem"
ahhhh okok, yeah I will update these

2022-11-14 15:25 UTC, Da-Colon commented on src/pages/Treasury/Transactions.tsx
> +            h="1.25rem"
![image](https://user-images.githubusercontent.com/38386583/201698817-c74de6a2-e894-45a3-a1bc-36a6b488e5ca.png)

2022-11-14 15:27 UTC, herbig commented on src/pages/Treasury/Transactions.tsx
> +            h="1.25rem"
updated

2022-11-14 15:28 UTC, Da-Colon commented on src/pages/Treasury/utils.ts
> +export function useFormatTransfers(
yessir. to keep the hooks file to be a million files long. we can start putting them into folders if its for specific things. (I've sorted started this). `hooks/treasury`. but yeah generally separate files are used. but I guess no a big deal either. long as the page is easily readable.

2022-11-14 15:47 UTC, Da-Colon reviewed
I guess previous comment assumed that you are going to update the fractal-ui package? or do you want do that in a follow up PR?

2022-11-14 15:48 UTC, herbig commented
> is the eth icon being used as a fallback or can this svg be removed?

it's used in the same component that normally takes a URL for the token image, so I think it needs to be in here

2022-11-14 16:07 UTC, Da-Colon approved these changes
LGTM. I'll create a PR seperately to update `@decent-org/fractal-ui` version. fixes button fonts and adds new icons, amoung other things.

2022-11-14 18:52 UTC, Da-Colon commented
@herbig weird this PR is stuck in a 'Some checks haven't completed yet' state.

2022-11-14 20:32 UTC, tbwebb22 reviewed
This treasury page looks dope! I just have one question - looks like the treasury doesn't update real-time as the assets are deposited / withdrawn. I think this is because we are using the Gnosis API instead of on-chain events. Do we want the treasury data to update realtime or are we alright with the user needing to refresh for now?

2022-11-14 21:04 UTC, herbig commented
> This treasury page looks dope! I just have one question - looks like the treasury doesn't update real-time as the assets are deposited / withdrawn. I think this is because we are using the Gnosis API instead of on-chain events. Do we want the treasury data to update realtime or are we alright with the user needing to refresh for now?

Yeah.. since we're not listening to the contracts, we lose the realtime updating with the Gnosis API.

There might be a solution, like a background timer to trigger a refresh of data on a page or something, but that would need to be thought out.

For now, given we're using the Gnosis API for all of this I think that's alright.

2022-11-14 21:43 UTC, tbwebb22 commented
> > This treasury page looks dope! I just have one question - looks like the treasury doesn't update real-time as the assets are deposited / withdrawn. I think this is because we are using the Gnosis API instead of on-chain events. Do we want the treasury data to update realtime or are we alright with the user needing to refresh for now?
> 
> Yeah.. since we're not listening to the contracts, we lose the realtime updating with the Gnosis API.
> 
> There might be a solution, like a background timer to trigger a refresh of data on a page or something, but that would need to be thought out.
> 
> For now, given we're using the Gnosis API for all of this I think that's alright.

Cool, sounds good.

2022-11-14 21:43 UTC, tbwebb22 approved these changes

2022-11-14 21:56 UTC, merged