V1 design/db activities
decent-dao/fractal-interface pull request #643
Opened 2022-11-06 17:36 UTC by Da-Colon

## Description

## Notes

## Issue / Notion doc (if applicable)

## Testing

## Screenshots (if applicable)

2022-11-07 16:58 UTC, Da-Colon commented on src/pages/DaoDashboard/Activities/hooks/useActivities.ts
> +            eventType: 'Treasury',
Currently this isn't being used, I was going to use this in the future when we add in Proposal Data. At that time will update into a ENUM for sure

2022-11-07 17:02 UTC, Da-Colon commented on src/pages/DaoDashboard/Activities/hooks/useActivities.ts
> +              const addressOrName = await getAddressDisplay(
The hook wouldn't be able to used for this. As the transfers addresses are mapped. multiple to one transaction.

2022-11-07 17:03 UTC, Da-Colon commented on src/pages/DaoDashboard/Activities/hooks/useActivities.ts
> +              const addressOrName = await getAddressDisplay(
because we aren't displaying the tooltip I will add that it won't be using this for every address just if the length of addresses is less than 3

2022-11-07 17:25 UTC, Da-Colon commented on src/pages/DaoDashboard/Activities/hooks/useActivities.ts
> +              const addressOrName = await getAddressDisplay(
ugh fine you may be right. let me look at this.

2022-11-07 19:04 UTC, Da-Colon commented
@mudrila All comments have been addressed sir. good idea taking that address out. I do see an update that needs to be made to the `useDisplayName` hook. it shows to subString address for a spilt second before it shows ENS name. we probably need this thing to wait before it spits out a result until the lookup is finished

2022-11-08 05:39 UTC, herbig commented on src/components/ui/EtherscanLinkAddress.tsx
> +  path?: string;
There's a separate `EtherscanTransactionLink` component for that as well.

We can merge the two into a single component, but would be good to change the name to something more generic, or keep the two separate.

2022-11-08 05:42 UTC, herbig commented on src/components/ui/containers/InfoBox.tsx
> +export function InfoBox({
hahahaha, oh no I renamed my own component `InfoBox` 🤦

2022-11-08 05:45 UTC, herbig commented on src/components/ui/loaders/BarLoader.tsx
> +export function BarLoader() {
this looks pretty sick in the app, I might want to add this to the Treasury

2022-11-08 05:45 UTC, herbig commented on src/components/ui/containers/AcitivityBox.tsx
> +    <SlideFade
Oh nice, might need to think about standardizing component animations in some way as well.

2022-11-08 05:47 UTC, herbig commented on src/i18n/locales/en/common.json
> +    "send": "Send",
got a typo in `Recieved`, and I assume this should be `"sent": "Sent"`?

2022-11-08 05:51 UTC, herbig commented on src/utils/currency.ts
> +export const formatWeiToValue = (amountInWei: string, decimals: number) => {
I have a couple similar formatting functions in the Treasury PR:

https://github.com/decent-dao/fractal-interface/pull/642/files#r1016150767

2022-11-08 05:52 UTC, herbig commented on src/types/activity.ts
> +export enum GnosisTransferType {
this is the same as the Transfers API request, so we'll have to merge some of these models at some point

2022-11-08 05:54 UTC, herbig commented on src/providers/fractal/types/gnosis.ts
> +export interface GnosisTransfer {
Same with these models, I have the same stuff in the Treasury PR, blast

2022-11-08 05:55 UTC, herbig commented on src/pages/DaoDashboard/Activities/index.tsx
> +          gap="1rem"
Is this going to leave a gap somewhere if there are no activities in `sortedActivities` ?

2022-11-08 05:58 UTC, herbig commented on src/pages/DaoDashboard/Activities/hooks/useActivities.ts
> +          t => t.to.toLowerCase() === safe.address!.toLowerCase()
you probably can't assume `safe.address!` here because of the or `||` condition above, but ? should do the same here I think?

2022-11-08 06:01 UTC, herbig commented on src/pages/DaoDashboard/Activities/hooks/useActivities.ts
> +          transfer.to.toLowerCase() === safe.address!.toLowerCase() ? transfer.from : transfer.to
similarly, I'm not sure what the React result would be here if we don't have a safe.address, but I think doing the safe thing of `safe.address?.toLowerCase()` would do the same thing here?

2022-11-08 06:05 UTC, herbig commented on src/pages/DaoDashboard/Activities/ActivityTreasury.tsx
> +      <Text>{transferTypeStr}</Text>
do these text components need to be styled at all, or is the default capturing what it should be?

2022-11-08 06:07 UTC, herbig commented on src/pages/DaoDashboard/Activities/ActivityTreasury.tsx
> +        <Text>{transferAddresses.length} addresses</Text>
`{{num}} addresses` can be in our json strings

2022-11-08 06:09 UTC, herbig commented on src/pages/DaoDashboard/Activities/ActivityCard.tsx
> +  eventDate = '2022-10-03',
don't think you need the value here anymore

2022-11-08 06:18 UTC, herbig requested changes
A few comments!

Also some things from testing:

1. the activity feed needs the same default left/right padding that the upper cards have (see screenshot)
2. treasury breaks a bit weird at one point and doesn't fill the screen, also without a lot of content in there maybe it's better to break it a different way, but I'm not really sure
3. The Newest/Oldest filter opens SUPER slow on Firefox, but not on Chrome, for some reason.  I actually think maybe it should just toggle between the two without needing to open the dialog to select one.
<img width="301" alt="Screen Shot 2022-11-08 at 1 14 52 AM" src="https://user-images.githubusercontent.com/384559/200489477-75debe87-133b-4f61-afee-9d501dddf01b.png">
<img width="1170" alt="Screen Shot 2022-11-08 at 1 15 33 AM" src="https://user-images.githubusercontent.com/384559/200489516-bf9b1041-64f6-446c-b801-c101525719b7.png">

2022-11-08 14:51 UTC, Da-Colon commented on src/pages/DaoDashboard/Activities/index.tsx
> +          gap="1rem"
no sir? wdym?

2022-11-08 14:53 UTC, Da-Colon commented on src/pages/DaoDashboard/Activities/hooks/useActivities.ts
> +          transfer.to.toLowerCase() === safe.address!.toLowerCase() ? transfer.from : transfer.to
same as above, this is just to prevent typescript from yelling. but its safe to assume that safe is defined here. I'm not sure why the address is typed to be undefined

2022-11-08 14:53 UTC, Da-Colon commented on src/pages/DaoDashboard/Activities/ActivityTreasury.tsx
> +      <Text>{transferTypeStr}</Text>
Its inheriting the styling from the parent

2022-11-08 14:59 UTC, Da-Colon commented
> the activity feed needs the same default left/right padding that the upper cards have (see screenshot)
There isn't padding here this is flex containers. I'll look into making this smooth together

2022-11-08 15:01 UTC, Da-Colon commented
> The Newest/Oldest filter opens SUPER slow on Firefox, but not on Chrome, for some reason. I actually think maybe it should just toggle between the two without needing to open the dialog to select one.

Don't use firefox....also toggle seems non intuitive IMO, plus we may want to add more sorts in the future?. I'll look at see what the problem on Fox is

2022-11-08 15:45 UTC, herbig commented on src/pages/DaoDashboard/Activities/index.tsx
> +          gap="1rem"
ah I was thinking this was padding of some sort, but it's the gap between components.

2022-11-08 15:46 UTC, herbig commented
> @herbig I'm not getting 'slow' behavior on firefox?

Hmmmm, working fine for me now as well. I'll keep an eye on it.

2022-11-08 16:02 UTC, herbig approved these changes
🛳️🛳️🛳️

2022-11-09 14:40 UTC, Da-Colon commented on src/pages/DaoDashboard/Activities/hooks/useActivities.ts
> +    if (sortedActivities.length) {
gosh good point. I'll get this updated

2022-11-09 14:56 UTC, Da-Colon commented on src/pages/DaoDashboard/Activities/ActivityTreasury.tsx
> +    <Text>
yeah the newer design doesn't call for it.

2022-11-09 14:57 UTC, Da-Colon commented on src/components/ui/loaders/BarLoader.tsx
> +export function BarLoader() {
totally preference. I think there is an argument for either way

2022-11-09 16:52 UTC, merged