Pivot/subdao
decent-dao/fractal-interface pull request #667
Opened 2022-11-15 18:04 UTC by christopherdancy

## Description

Changes include

- Route Changes for SubDAO creation
- Abstracted dao creation from the actual tx building.
- Created separate hooks to create a subdao proposal and a dao deployment
- Added functionality to submit a gnosis proposal to the gnosis api w/ sigs attached to show up on the gnosis UI 

## Notes

## Issue / Notion doc (if applicable)

## Testing

## Screenshots (if applicable)
<img width="1087" alt="image" src="https://user-images.githubusercontent.com/69045872/201992222-531b425f-1bc6-4869-957f-4113e8e6fa86.png">
<img width="1087" alt="image" src="https://user-images.githubusercontent.com/69045872/201993271-03cc0e3b-0b4e-4e0a-909a-c5e70a5709a1.png">

2022-11-15 19:11 UTC, sethhrbek commented on src/helpers/crypto.ts
> +};
wondering if some of these Gnosis-API specific vars/methods would be better placed in a `gnosis-api.ts` helper file, rather than the general `crypto` file, just for organization purposes

2022-11-15 19:12 UTC, sethhrbek commented on src/helpers/crypto.ts
> +  }
This should be able to use the `SafeTransaction` type in `src/types/transaction.ts`

2022-11-16 18:31 UTC, christopherdancy commented on src/helpers/crypto.ts
> +  const nonce = !template.nonce ? await (await gnosisContract.nonce()).toString() : template.nonce;
Correct -- I am making this update now

2022-11-16 20:00 UTC, christopherdancy commented on src/helpers/crypto.ts
> +};
I think this could left as is given the focus here is on building the tx with a sig which will then be passed to build the actual api request.

2022-11-16 20:04 UTC, christopherdancy commented on src/helpers/crypto.ts
> +  }
I am not sure it can given the possibly undefined nature of the template -- which we be set in the actual txbuild => creates the SafeTx

2022-11-17 16:14 UTC, tbwebb22 requested changes
When attempting to create a Usul subdao from a Multisig parent, I don't see any transaction being posted to the Gnosis Safe. Should this be working as part of this PR?

2022-11-17 17:16 UTC, Da-Colon commented on src/providers/fractal/hooks/useProposals.ts
> +  const submitProposal = useCallback(
This goes into a little about what I discussed this morning. about loading these methods into `Fractal Provider` state. so that the UI don't have to decide which method to use. both methods should except similar data (kinda how we have the DeployDAO setup. 

see: `useGnosisGovernance`

This can happen in a future PR

2022-11-17 17:17 UTC, Da-Colon commented on src/helpers/crypto.ts
> +  }
You can use `Partial` 


```ts
  template: {
    to: string;
    value: BigNumber | number | string;
    data: string;
    operation: number;
    safeTxGas: number | string;
    baseGas: number | string;
    gasPrice: number | string;
    gasToken: string;
    refundReceiver: string;
    nonce: number;
  }
```

and when you use it you can use `Partial< SafeTransaction >`

2022-11-17 17:18 UTC, Da-Colon commented on src/helpers/crypto.ts
> +  }
https://www.typescriptlang.org/docs/handbook/utility-types.html#partialtype

2022-11-17 18:33 UTC, herbig commented on src/pages/SubDaoCreate/index.tsx
> +    navigate(`/daos/${daoAddress}`);
We can use `DAO_ROUTES.dao.relative(daoAddress)` here

2022-11-17 18:37 UTC, herbig reviewed
Agree with @mudrila , looking good aside from the discussions others have posed!

2022-11-17 19:57 UTC, christopherdancy commented
> When attempting to create a Usul subdao from a Multisig parent, I don't see any transaction being posted to the Gnosis Safe. Should this be working as part of this PR?

Are you sure... David and I have tested this many times? Is the usul subdao derived from a multisig parent?

2022-11-17 20:11 UTC, christopherdancy commented
<img width="794" alt="image" src="https://user-images.githubusercontent.com/69045872/202549352-b059c0ce-4d0f-4e23-a3be-75ff5b462021.png">

2022-11-17 20:48 UTC, tbwebb22 commented
> 

Yeah, when I start from a Multi-sig DAO, and attempt to create a Usul sub-dao, that transaction doesn't show up in the Gnosis Safe UI.

2022-11-17 21:02 UTC, christopherdancy commented
Can anyone else try this? I just created one above -- perhaps this is something taylor is running into.

2022-11-17 21:02 UTC, christopherdancy commented
you signed the tx correct?

2022-11-17 21:11 UTC, tbwebb22 commented
> you signed the tx correct?

Yep, I sign it. Then pull the DAO up in the Gnosis UI, and theres no new tx there

> 

Nevermind, disregard, it is working. My Safe Transaction page was defaulting to this "history" view for some reason and wasn't showing the new TX's coming in

2022-11-17 21:13 UTC, herbig approved these changes
Looks good!

2022-11-17 21:22 UTC, Da-Colon approved these changes

2022-11-17 21:23 UTC, tbwebb22 approved these changes

2022-11-17 21:35 UTC, merged