Send assets modal
decent-dao/fractal-interface pull request #674
Opened 2022-11-17 03:02 UTC by herbig

## Description

Send assets modal on the Treasury page

## Notes

- I still need to add the actual proposal transaction, which I'll do once we have proposal work in place

## Issue / Notion doc (if applicable)

https://www.figma.com/file/uRV3Nfowdzt5CknW1FgUkQ/%F0%9F%93%9A-Fractal-Design-System-%7C-Base-Components-%7C-October-2022?node-id=2461%3A19563&t=skyAWldopfI8hyzt-0

closes https://github.com/decent-dao/fractal-interface/issues/646

## Testing

Navigate to a DAO Treasury page and click "Send Assets"

## Screenshots (if applicable)

<img width="1053" alt="Screen Shot 2022-11-16 at 9 58 19 PM" src="https://user-images.githubusercontent.com/384559/202344430-7610cd24-67ca-4c40-9bf1-9ddc6b539572.png">

2022-11-18 18:01 UTC, herbig commented on src/modals/SendAssetsModal.tsx
> +              isDisabled={Number(selectedAsset.fiatBalance) == 0}
Ahh cool.

`== can do unexpected type conversions, in Javascript 1=="1" is true. The === operator avoids this. Comparing different types with === is always false.`

so that's what `===` is ha, I hadn't even looked it up before, makes sense.

2022-11-18 18:02 UTC, herbig commented on src/modals/SendAssetsModal.tsx
> +    setAmountInput(value.replace(/[^0-9.]/g, '').replace(/(\..*)\./g, '$1'));
I could find a prop to make it a number only field, so this strips anything other than 0-9 or .

2022-11-18 21:33 UTC, Da-Colon commented on src/modals/SendAssetsModal.tsx
> +    setAmountInput(value.replace(/[^0-9.]/g, '').replace(/(\..*)\./g, '$1'));
ah yes, Its not super clear yet but there is a way on the current input setup that does. this. 

https://github.com/decent-dao/decent-ui/tree/develop/design/atoms/components/input

```ts
import { RestrictCharTypes, Input } from '@decent-org/fractal-ui`

<Input restrictType={RestrictCharType.WHOLE_NUMBER_ONLY}
```

2022-11-21 21:35 UTC, christopherdancy requested changes

2022-11-21 21:35 UTC, christopherdancy commented on src/modals/SendAssetsModal.tsx
> +    : Number(amountInput) > formatCoinUnitsFromAsset(selectedAsset);
I am getting a weird conversion issue when usd is not selected and I am just putting in the an eth value.

<img width="857" alt="image" src="https://user-images.githubusercontent.com/69045872/203161193-7005af8b-e651-4ff2-9a9d-1f1837eb4ea2.png">

2022-11-22 04:08 UTC, herbig commented on src/modals/SendAssetsModal.tsx
> +    : Number(amountInput) > formatCoinUnitsFromAsset(selectedAsset);
@christopherdancy hmmm, yeah this might be poor UX... you actually do have USD selected, and what you're inputting there is 0.1 USD

2022-11-22 04:09 UTC, herbig commented on src/modals/SendAssetsModal.tsx
> +          <Input
Yeah, not a bad idea.. designs didn't have it but max is pretty standard.

2022-11-22 04:10 UTC, herbig commented on src/pages/Treasury/index.tsx
> +        buttonText={showButton ? t('buttonSendAssets') : undefined}
Yeah I haven't put any restrictions on whether that button appears or not yet, as those user states still need to be set up in the fractal provider.

Really the button also shouldn't show if the account viewing it doesn't have voting power on the DAO

2022-11-22 04:32 UTC, herbig commented on src/modals/SendAssetsModal.tsx
> +    setAmountInput(value.replace(/[^0-9.]/g, '').replace(/(\..*)\./g, '$1'));
Ah cool. @Da-Colon I switched to this, but also realized this doesn't work on Firefox, so our other input fields like in DAO token creation accept any text.

https://github.com/decent-dao/fractal-interface/issues/696

2022-11-22 15:34 UTC, christopherdancy commented on src/modals/SendAssetsModal.tsx
> +    : Number(amountInput) > formatCoinUnitsFromAsset(selectedAsset);
Ohhh I see. Yes -- it is quite confusing too me.

2022-11-22 15:34 UTC, christopherdancy commented on src/modals/SendAssetsModal.tsx
> +          <Input
yes perhaps for a different PR

2022-11-22 15:35 UTC, christopherdancy commented on src/pages/Treasury/index.tsx
> +        buttonText={showButton ? t('buttonSendAssets') : undefined}
Sounds good -- I think it will depend on the threshold for each dao but this is good. Will close for now.

2022-11-22 15:36 UTC, christopherdancy commented on src/i18n/locales/en/modals.json
> +    "sendAssetsSubmit": "Review",
> Do we need this review button or could we just submit the tx?

This could just be a comment.

2022-11-22 15:38 UTC, herbig commented on src/i18n/locales/en/modals.json
> +    "sendAssetsSubmit": "Review",
@Da-Colon yeah Review is not a great label for that button, which Tom brought up as well.

We will be doing a full copy review before launch so that will likely get changed to something like just Submit

2022-11-23 21:04 UTC, herbig commented on src/modals/SendAssetsModal.tsx
> +export function SendAssetsModal({ close }: { close: Function }) {
updated

2022-11-23 21:06 UTC, herbig commented on src/modals/SendAssetsModal.tsx
> +import { Box, Button, Divider, Flex, Select, Spacer, Switch, Text } from '@chakra-ui/react';
yeah good catch, it should be decent's, updated

2022-11-23 21:07 UTC, herbig commented on src/utils/numberFormats.ts
> +  return formatCoin(asset.balance, truncate, asset?.token?.decimals, asset?.token?.symbol);
yup, updated

2022-11-23 21:16 UTC, merged