Feature/671/add guard
decent-dao/fractal-interface pull request #714
Opened 2022-11-29 21:22 UTC by christopherdancy

## Description

## Notes

## Issue / Notion doc (if applicable)

## Testing

## Screenshots (if applicable)

2022-12-01 04:38 UTC, Da-Colon submitted a review, later dismissed
How can I test that I have successfully added a guard?

2022-12-01 04:38 UTC, Da-Colon commented on src/hooks/useAddresses.ts
> +    vetoERC20VotingMasterCopy?: EthAddress;
This file can be removed.

2022-12-01 04:38 UTC, Da-Colon commented on src/pages/SubDaoCreate/index.tsx
> +// eslint-disable-next-line import/namespace, import/default, import/no-named-as-default
nit picky, but might be better to update this hook to an export versus having it default exported and having to add this.

2022-12-01 14:16 UTC, herbig commented on src/hooks/DAO/useBuildDAOTx.ts
> +            1, // Threshold
what's this parameter doing, and why did that change to 1 in both cases?

2022-12-01 14:19 UTC, herbig commented on src/hooks/DAO/useBuildDAOTx.ts
> +          [solidityKeccak256(['bytes'], [setModuleCalldata]), saltNum]
does this `saltNum` need to match where it was already used above? if not it probably makes sense to generate a new one

2022-12-01 14:21 UTC, herbig commented on src/hooks/DAO/useBuildDAOTx.ts
> +          [solidityKeccak256(['bytes'], [setModuleCalldata]), saltNum]
Same with the uses of `saltNum` below.  Do those all need to match or should we have a new random salt for each?

2022-12-01 14:23 UTC, sethhrbek commented on src/hooks/DAO/useBuildDAOTx.ts
> +          ]);
This code fragment could be refactored to its own method, since it is used in both DAO types (multisig + usul).

2022-12-01 14:24 UTC, herbig commented on src/hooks/DAO/useBuildDAOTx.ts
> +        // Fractal Module
@tbwebb22 it would be good to have you review this portion as well, as you and @christopherdancy are the contract experts

2022-12-01 17:41 UTC, christopherdancy commented on src/hooks/useAddresses.ts
> +    vetoERC20VotingMasterCopy?: EthAddress;
For sure -- will remove this now

2022-12-01 17:48 UTC, christopherdancy commented on src/hooks/DAO/useBuildDAOTx.ts
> +            1, // Threshold
Great question -- the previous method would cause the tx to revert for the following reason:

1. A gnosis safe requires the threshold be met before a tx may be executed.
2. If there is more than 1... set as the threshold then the multisend contract cannot act as the only signer.
3. Since the trusted addresses could not be -- the signer which is executing the tx, then they would not be able to sign for this tx.

therefore this should be set as one and changed after the multisend contract has completed its setup txs.

2022-12-01 17:51 UTC, christopherdancy commented on src/hooks/DAO/useBuildDAOTx.ts
> +          ]);
Makes sense -- I am updating as we speak.

2022-12-01 17:51 UTC, christopherdancy commented on src/hooks/DAO/useBuildDAOTx.ts
> +          ]);
well not as we speak but right after.

2022-12-01 22:47 UTC, herbig approved these changes
This looks good to me, would just like @tbwebb22 to weigh in as well

2022-12-02 13:41 UTC, tbwebb22 commented on src/hooks/DAO/useBuildDAOTx.ts
> +        // Fractal Module
Cool, will give this a review today

2022-12-02 14:20 UTC, tbwebb22 requested changes
Why was `votesTokenMasterCopy` changed to `votesMasterCopy` everywhere?

2022-12-02 15:14 UTC, christopherdancy commented
> Why was `votesTokenMasterCopy` changed to `votesMasterCopy` everywhere?

I am not sure -- this was not m

2022-12-02 15:39 UTC, tbwebb22 commented on src/hooks/DAO/useBuildDAOTx.ts
> +        ) {
The purpose of this if / else block is to select between whether the DAO is a root or a child, correct? Why does it include the `vetoGuardMasterCopyContract` and `vetoMultisigVotingMasterCopyContract`?

2022-12-02 15:42 UTC, Da-Colon commented
hit enter too quick. Updates look good to me! lol

2022-12-02 16:12 UTC, tbwebb22 commented on src/hooks/DAO/useBuildDAOTx.ts
> +          const vetoMultiContract = VetoMultisigVoting__factory.connect(
Can we rename this one to `vetoMultisigVotingContract`? Just getting confusing with there also be the `vetoGuard` contract

2022-12-02 16:22 UTC, tbwebb22 commented on src/hooks/DAO/useBuildDAOTx.ts
> +
I think we should be more explicit with variable naming here. We have VetoVoting and VetoGuard contracts, so just naming something "Veto" doesn't really identify it well

2022-12-02 16:25 UTC, tbwebb22 commented
I think we should be a little more explicit with the variable naming, more like:
`multisigVetoGuard`
`usulVetoGuard`
`multisigVetoVoting`
`erc20VetoVoting`

2022-12-02 17:00 UTC, tbwebb22 commented on src/hooks/DAO/useBuildDAOTx.ts
> +        if (parentDAOAddress && vetoERC20VotingMasterCopyContract && vetoGuardMasterCopyContract) {
Same question as the other if statement - why are we checking these two contracts here?

2022-12-02 17:31 UTC, christopherdancy commented on src/hooks/DAO/useBuildDAOTx.ts
> +        ) {
Due to the possible undefined state of these two contracts. They are not required if a user wanted to deploy a root gnosis safe

2022-12-02 17:32 UTC, christopherdancy commented on src/hooks/DAO/useBuildDAOTx.ts
> +        if (parentDAOAddress && vetoERC20VotingMasterCopyContract && vetoGuardMasterCopyContract) {
same answer as above.

2022-12-02 19:58 UTC, tbwebb22 commented on src/hooks/DAO/useBuildDAOTx.ts
> +        ) {
So if I'm trying to create a subDAO, but one of those master copy contracts isn't defined, then it will still create a DAO tx, but it won't have any of the necessary child DAO configuration (veto guard, fractal module, etc). I don't think that's how we want this to work right?

2022-12-02 20:10 UTC, christopherdancy commented on src/hooks/DAO/useBuildDAOTx.ts
> +        ) {
This is not for a sub dao. The same method is used for a root dao or a sub dao. The veto contract is only needed for the subdao. Therefore it is okay, during root dao creation, to not have one of the mastercopy contract defined.

2022-12-02 20:12 UTC, mobiusTripper-crypto approved these changes

2022-12-02 20:13 UTC, tbwebb22 commented on src/hooks/DAO/useBuildDAOTx.ts
> +        ) {
The conditional in the if statement I have highlighted above, is supposed to only evaluate to true when we are creating a subDAO, no?

2022-12-02 20:14 UTC, christopherdancy commented on src/hooks/DAO/useBuildDAOTx.ts
> +        ) {
It will only be true if there is a subdao correct.

2022-12-02 20:17 UTC, tbwebb22 commented on src/hooks/DAO/useBuildDAOTx.ts
> +        ) {
Right, so if I'm trying to create a subDAO, but one of these master copy contract is undefined, this conditional evaluates to false, and we go to the `else` block, and end up still creating a DAO tx, but that DAO will be configured as a root DAO, not a subDAO. I don't believe that's how we want this to work, right?

2022-12-02 20:23 UTC, christopherdancy commented on src/hooks/DAO/useBuildDAOTx.ts
> +        ) {
I see what you are saying - just made changes.

2022-12-05 15:32 UTC, tbwebb22 commented on src/hooks/DAO/useBuildDAOTx.ts
> +        ) {
Hmm I don't see the changes

2022-12-05 16:26 UTC, christopherdancy commented on src/hooks/DAO/useBuildDAOTx.ts
> +        ) {
I see where the issue was -- I updated this on the other branch. Should be here now.

2022-12-05 17:27 UTC, tbwebb22 approved these changes
LGTM

2022-12-05 18:28 UTC, merged