Create Proposal UI Redesign (Safe/Usul)
decent-dao/fractal-interface pull request #718
Opened 2022-11-30 18:31 UTC by mobiusTripper-crypto

## Description

Updated Create Proposal page to match the next UX design documents.

## Notes

The pages for this branch do not match the designs until it is merged with `update/fractal-design-0.1`, but the components function correctly.
See included inline review comments

## Testing

- Navigate to an existing DAO [0xB87AD11E40F66137BD4cbB5f9d9438451000251B]. View all proposals.
- In the upper left of the screen choose `Create Proposal` to create a new proposal.
- Verify Accordion functions operate correctly for expand / collapse (click the Transaction number header)
- Verify Add and Remove transactions work correctly.

2022-11-30 18:36 UTC, mobiusTripper-crypto commented on src/components/ProposalCreate/InputComponent.tsx
> +import { Input, HStack, Text, Textarea, Grid, GridItem } from '@chakra-ui/react';
This violates the "1 component 1 file" guideline. InputComponent and TextareaComponet can be separated, but I wanted some initial feedback on this design approach.

2022-11-30 18:36 UTC, mobiusTripper-crypto commented on src/components/ProposalCreate/Transactions.tsx
> +                  <Box h="36px" />
I needed a placeholder here when the icon is not displayed. Is this an acceptable solution?

2022-11-30 18:36 UTC, mobiusTripper-crypto commented on src/i18n/locales/en/proposal.json
> +    "cancel": "Cancel",
I was unclear if these single word translations should go in 'common'

2022-11-30 20:24 UTC, herbig commented on src/pages/ProposalCreate/index.tsx
> +                    color="#0085FF"
Do we not have this color in the design system? @Da-Colon ?

2022-11-30 20:37 UTC, herbig commented on src/pages/ProposalCreate/index.tsx
> +          <Text textStyle="text-2xl-mono-bold">{t('proposalDetails')}</Text>
doesn't look like `proposalDetails` is defined anywhere.  We have this as `proposalSummaryTitle` though

2022-11-30 20:40 UTC, herbig commented on src/pages/ProposalCreate/index.tsx
> +    console.log('addnew', transactions.length);
just noting we should remove stray console logs!

Also (not applicable to this instance), but we have a `logError(e);` function to log things to sentry/console on non prod builds, just FYI

2022-11-30 20:42 UTC, herbig commented on src/i18n/locales/en/proposal.json
> +    "cancel": "Cancel",
Hmm, yeah it seems like `cancel` definitely could be in common, that will likely be reused.  The others are probably fine to leave here

2022-11-30 20:44 UTC, herbig commented on src/components/ProposalCreate/Transactions.tsx
> +                  <Box h="36px" />
yeah, makes sense to me, @Da-Colon might have ideas for alternatives

2022-11-30 20:54 UTC, herbig reviewed
Hey @mobiusTripper-crypto, this is looking super slick.

Some non code related feedback (all on _Firefox_, if that's relevant):

- margin between "Proposal" title and the black box "Transaction 1" looks thin
- Aside from Target Address, the background of the inputs are black, when they should be grey
- Inputting the create URL directely (e.g. https://deploy-preview-718--fractal-framework-interface-dev.netlify.app/#/daos/0xB87AD11E40F66137BD4cbB5f9d9438451000251B/proposals/new) then clicking "Cancel" gives a blank page
- is it possible to close the above transaction and/or scroll to the new one if "Add another transaction" is clicked?
- can we disable "Create Proposal" if clicking it won't start a transaction (meaning some of the fields aren't filled out)
- despite what the design shows, `Function Signature` and `Parameters` aren't required fields, since a function call could have no parameters

2022-11-30 22:34 UTC, mobiusTripper-crypto commented
> * margin between "Proposal" title and the black box "Transaction 1" looks thin
fixed

> * Aside from Target Address, the background of the inputs are black, when they should be grey
the style of the textareas will be updated on the next revision of decent-ui

> * Inputting the create URL directely (e.g. https://deploy-preview-718--fractal-framework-interface-dev.netlify.app/#/daos/0xB87AD11E40F66137BD4cbB5f9d9438451000251B/proposals/new) then clicking "Cancel" gives a blank page
yeah, i totally phoned that in, fixed

> * is it possible to close the above transaction and/or scroll to the new one if "Add another transaction" is clicked?
yeah, good call here too, fixed

> * can we disable "Create Proposal" if clicking it won't start a transaction (meaning some of the fields aren't filled out)
I looked into this, and it might be a significate refactor from it's current implementations. maybe a new task would be a better idea and fix in this PR.

> * despite what the design shows, `Function Signature` and `Parameters` aren't required fields, since a function call could have no parameters
fixed

2022-11-30 23:40 UTC, herbig commented
> > * can we disable "Create Proposal" if clicking it won't start a transaction (meaning some of the fields aren't filled out)
> >   _**I looked into this, and it might be a significate refactor from it's current implementations. maybe a new task would be a better idea and fix in this PR.**_

Yeah, makes sense. This is probably a larger discussion about form validations, as screens are currently all over the place on that..

2022-11-30 23:47 UTC, herbig reviewed
Hey @mobiusTripper-crypto a few minor things now with the margin change I think:

- There's no margin under "Create Proposal" title
- The `Proposal Details` cards isn't aligned with the Create side
- unrelated, but I also noticed the `Proposal Details` text is too large

<img width="1315" alt="Screenshot 2022-11-30 at 6 42 57 PM" src="https://user-images.githubusercontent.com/384559/204932235-6af9e644-e5bc-4b84-96ac-22cec298d246.png">

2022-12-01 04:30 UTC, Da-Colon requested changes
Looking great. Updates for next release might be done in time to install here, I'll keep you posted. a few comments and suggestions

2022-12-01 04:30 UTC, Da-Colon commented on src/components/ProposalCreate/Transactions.tsx
> +                  <Box h="36px" />
Is there any reason why this wouldn't work here?

```tsx
                {index !== 0 && (
                  <IconButton
                    icon={<DeleteIcon />}
                    aria-label={t('removetransactionlabel')}
                    variant="unstyled"
                    onClick={() => removeTransaction(index)}
                    minWidth="auto"
                  />
                )}
```

2022-12-01 04:30 UTC, Da-Colon commented on src/pages/ProposalCreate/index.tsx
> +                    color="#0085FF"
Yessir, I'm the background is "blue.900" and the Icon and Border are "blue.500". I am also currently themeing the alert and will have it a new release soon where some of these values can be removed.

2022-12-01 04:30 UTC, Da-Colon commented on src/components/ProposalCreate/Transactions.tsx
> +          {({ isExpanded }) => (
These Accordion components are nifty. I've could have used these in the past

2022-12-01 04:30 UTC, Da-Colon commented on src/components/ProposalCreate/Transactions.tsx
> +  //TODO: placeholder for delete icon, remove when added to decent-ui
This has been add to the Design System and will be incoming in next release.

2022-12-01 04:30 UTC, Da-Colon commented on src/components/ProposalCreate/InputComponent.tsx
> +import { Input, HStack, Text, Textarea, Grid, GridItem } from '@chakra-ui/react';
This looks good. And changes my mind a little on deconstructing `props` outside of the params lol.

2022-12-05 14:52 UTC, mobiusTripper-crypto commented on src/components/ProposalCreate/Transactions.tsx
> +                  <Box h="36px" />
Regarding this minWidth="auto" /> ) : ( <Box h="36px" />

The IconButton happens to be the tallest component in the Accordion when it's collapsed, so on the 1st transaction where there is no icon, it's height smaller than all the rest of the boxes. I could set a minHeight on the accordion panel equal to that icon, but somehow I need to keep that box from getting too small.

2022-12-05 15:18 UTC, Da-Colon commented on src/components/ProposalCreate/Transactions.tsx
> +                  <Box h="36px" />
I see. yeah if it makes things complicated then the way it is fine for now

2022-12-05 17:08 UTC, merged