Update/622 safe transactions list
decent-dao/fractal-interface pull request #734
Opened 2022-12-05 03:58 UTC by Da-Colon

## Description
Updating soon

## Notes

## Issue / Notion doc (if applicable)
Closes #622
Closes #620 
Closes #660

## Testing

## Screenshots (if applicable)

2022-12-05 15:06 UTC, Da-Colon reviewed
I apologize for such a large PR. I did attempt to take it back. But alot of these changes are type changes. I've done my best to comment through the code to point out the more juicy parts.

2022-12-06 00:38 UTC, mobiusTripper-crypto commented on src/components/Proposals/ProposalCard.tsx
>      <Link to={proposal.proposalNumber.toString()}>
this toString is superfluous.

2022-12-06 00:38 UTC, mobiusTripper-crypto commented on src/components/Proposals/ProposalActions/ProposalAction.tsx
>        default:
extra toString on line 36

2022-12-06 00:38 UTC, mobiusTripper-crypto commented on src/components/ui/proposal/ProposalTitle.tsx
>    return (
on more extra toString on line 11

2022-12-06 00:38 UTC, mobiusTripper-crypto commented on src/components/Proposals/ProposalCard.tsx
> +  );
I think `usulProposal.startBlock?.toNumber()` would work if you want to make it shorter

2022-12-06 00:38 UTC, mobiusTripper-crypto commented on src/components/Proposals/ProposalCard.tsx
> +                submissionDate={multisigTransaction.submissionDate}
This is a little confusing to me as it seems like submissionDate is for both Usul and mulitsig? but it's only on the multisig option?

2022-12-06 00:38 UTC, mobiusTripper-crypto commented on src/components/ui/proposal/ProposalTime.tsx
> +            : t(isPassed ? 'timeAgo' : 'timeLeft', { time: submissionDate || diffReadable })}
I created a proposal, and a few minutes later it looks like this ...  maybe that needs to change?
![image](https://user-images.githubusercontent.com/99622829/205777232-5389d72d-87e1-40cb-b33c-c8bdb104f8ef.png)

or I don't understand what that is suppose to mean?

2022-12-06 00:44 UTC, Da-Colon commented on src/components/Proposals/ProposalCard.tsx
> +                submissionDate={multisigTransaction.submissionDate}
it is only a multisig option

2022-12-06 00:45 UTC, Da-Colon commented on src/components/Proposals/ProposalCard.tsx
> +                submissionDate={multisigTransaction.submissionDate}
> I think usulProposal.startBlock?.toNumber() would work if you want to make it shorter
it doesn't, `toNumber()` can't be called on `undefined`

2022-12-06 00:45 UTC, Da-Colon commented on src/components/ui/proposal/ProposalTime.tsx
> +            : t(isPassed ? 'timeAgo' : 'timeLeft', { time: submissionDate || diffReadable })}
lol look like a transaction is off. I'll look into what that is

2022-12-06 00:58 UTC, mobiusTripper-crypto commented on src/components/Proposals/ProposalCard.tsx
> +                submissionDate={multisigTransaction.submissionDate}
that's super confusing, i thought that was the entire point of '?` i'm going back to typescript school

2022-12-06 01:16 UTC, Da-Colon commented on src/components/Proposals/ProposalCard.tsx
> +                submissionDate={multisigTransaction.submissionDate}
ha. in this case we are calling a method. you can't call a method on undefined.toNumber(). versus passing a primitive value like string | undefined`

2022-12-06 16:29 UTC, Da-Colon commented on src/pages/DaoDashboard/Activities/hooks/useActivities.ts
> +      return [...parsedActivities].filter(
Ah, yessir. this method is actually updated further in the next PR. but in general I find it good practice when dealing with an array from state inside of a react hook its best to spread the array or create a new Array. I have dealt with weird side effects otherwise.

2022-12-06 16:32 UTC, Da-Colon commented on src/components/ui/proposal/ProposalTime.tsx
> +            : t(isPassed ? 'timeAgo' : 'timeLeft', { time: submissionDate || diffReadable })}
I'm not getting this on my end?

2022-12-06 16:34 UTC, Da-Colon commented
comments addressed sir @mobiusTripper-crypto

2022-12-06 18:47 UTC, herbig commented on src/providers/Fractal/governance/types.ts
> +}
@decent-dao/fractal probably good for folks to be aware of this specifically

2022-12-06 18:48 UTC, herbig commented on src/providers/Fractal/governance/types.ts
> +  PROPOSAL_STILL_ACTIVE = 'voting period has not passed yet',
should move these to json and use the key here instead

2022-12-06 18:55 UTC, Da-Colon commented on src/providers/Fractal/governance/types.ts
> +  PROPOSAL_STILL_ACTIVE = 'voting period has not passed yet',
ah yes, just was moving things. I can find where these are being used and get them updated.

2022-12-06 18:58 UTC, Da-Colon commented on src/providers/Fractal/governance/types.ts
> +  PROPOSAL_STILL_ACTIVE = 'voting period has not passed yet',
these aren't translated strings. these are actually error responses from contract: see `src/providers/Fractal/utils/usul.ts` line 38

2022-12-06 20:40 UTC, herbig commented on src/components/ui/proposal/ProposalTime.tsx
> +            : t(isPassed ? 'timeAgo' : 'timeLeft', { time: submissionDate || diffReadable })}
hmm, why are there two time left strings and why are they different?

2022-12-06 20:42 UTC, herbig commented on src/providers/Fractal/governance/hooks/useUsulProposals.ts
> +      // @todo no queued?
@mudrila yeah I noticed the queued string wasn't used anymore when I did a string cleanup.

Are these all the states we have now?

2022-12-06 20:43 UTC, herbig commented on src/providers/Fractal/governance/types.ts
> +  PROPOSAL_STILL_ACTIVE = 'voting period has not passed yet',
ah right right

2022-12-06 20:48 UTC, Da-Colon commented on src/components/ui/proposal/ProposalTime.tsx
> +            : t(isPassed ? 'timeAgo' : 'timeLeft', { time: submissionDate || diffReadable })}
thats a good question. This is on the `ProposalsList` page (which my current PR I'm working on will be cleaning up). I'll look into the setup

2022-12-06 20:49 UTC, Da-Colon commented on src/providers/Fractal/governance/hooks/useUsulProposals.ts
> +      // @todo no queued?
So from working on this further I believe this is now coming back as 'pending'. I'll check, I believe I have this updated in the next PR when I add in Usul

2022-12-06 21:01 UTC, herbig requested changes
Hey @Da-Colon, code looks good, but testing it I see a lot of weirdness:

1. Safe details doesn't load at all for me, just an empty page
2. I created a 2 transaction proposal and it's listed as 0 on the list, but 1 transaction on the homepage.
3. The Safe proposal id is a hash, so we need to take that out of the List title I think..
4. the "execute on" string ends abruptly, without saying an address
5. the two proposals listed (one is the DAO creation) are in different orders between the homepage and list


<img width="1303" alt="Screenshot 2022-12-06 at 3 54 03 PM" src="https://user-images.githubusercontent.com/384559/206021588-0063ee05-abcf-4b6e-8eed-ad93135ea131.png">
<img width="1351" alt="Screenshot 2022-12-06 at 4 00 59 PM" src="https://user-images.githubusercontent.com/384559/206021992-6148b752-0eb2-4869-bb6a-2cf7c6a4ca7a.png">

2022-12-06 21:19 UTC, Da-Colon commented
> Hey @Da-Colon, code looks good, but testing it I see a lot of weirdness:
> 
> 1. Safe details doesn't load at all for me, just an empty page
> 2. I created a 2 transaction proposal and it's listed as 0 on the list, but 1 transaction on the homepage.
> 3. The Safe proposal id is a hash, so we need to take that out of the List title I think..
> 4. the "execute on" string ends abruptly, without saying an address
> 5. the two proposals listed (one is the DAO creation) are in different orders between the homepage and list
> 
> <img alt="Screenshot 2022-12-06 at 3 54 03 PM" width="1303" src="https://user-images.githubusercontent.com/384559/206021588-0063ee05-abcf-4b6e-8eed-ad93135ea131.png">
> 
> <img alt="Screenshot 2022-12-06 at 4 00 59 PM" width="1351" src="https://user-images.githubusercontent.com/384559/206021992-6148b752-0eb2-4869-bb6a-2cf7c6a4ca7a.png">

So All changes in this PR are mostly functional updates. very little was touched in the UI other than typing changes/updates. 

- 1. Multisig details will be handled in a future PR.
- 2. is addressed as far as the homepage in the next PR. which adds Usul proposals to homepage. 
- 3, 5 will be handled in the PR I'm working on where I'll be cleaning up the UI on the Proposal Page. 

I'll DM about 4

2022-12-06 21:23 UTC, herbig approved these changes

2022-12-07 14:58 UTC, mobiusTripper-crypto approved these changes

2022-12-07 15:08 UTC, merged