Feature/add UI guard
decent-dao/fractal-interface pull request #744
Opened 2022-12-06 20:39 UTC by christopherdancy

## Description

This PR does the following:
1. Creates the UI steps and state to configure a veto guard.
2. Updates the types to account for different veto guards + veto voting contracts
3. Updates types and contract addresses.

Possible combinations:
1. Usul Root (no Veto Guard + Veto Voting)
2. Multisig Root (no Veto Guard + Veto Voting)
3. Multisig => Multisig (MultisigVetoGuard + MultisigVetoVoting)
4. Multisig => Usul (UsulVetoGuard + MultisigVetoVoting)
5. Usul => Multisig (MultisigVetoGuard + UsulVetoVoting)
6. Usul => Usul (UsulVetoGuard + UsulVetoVoting)

## Notes

The vetoGuard Config page changes:
1. If it is not a subDAO, the page should not show at all.
2. If it is a Multisig subDAO, the first question should be executionDelayBlocks
3. If it is a Usul subdao, the first question should be executionPeriod

## Issue / Notion doc (if applicable)

## Testing

Please test the following cases:
1. Usul Root (no Veto Guard + Veto Voting)
4. Multisig Root (no Veto Guard + Veto Voting)
5. Multisig => Multisig (MultisigVetoGuard + MultisigVetoVoting)
6. Multisig => Usul (UsulVetoGuard + MultisigVetoVoting)
7. Usul => Multisig (MultisigVetoGuard + UsulVetoVoting)
8. Usul => Usul (UsulVetoGuard + UsulVetoVoting)

## Screenshots (if applicable)
<img width="1252" alt="image" src="https://user-images.githubusercontent.com/69045872/206017763-18dca6f4-05c1-4ca3-932d-7129ac373b30.png">

2022-12-07 16:51 UTC, christopherdancy commented on src/hooks/DAO/useBuildDAOTx.ts
> +    (parentTokenAddress: string | undefined) => {
Yes this could be undefined if the parent DAO is a multisig dao without a token

2022-12-07 18:46 UTC, herbig commented on src/components/DaoCreator/provider/hooks/useSteps.ts
> +            prevStep: isPureGnosis ? CreatorSteps.PURE_GNOSIS : CreatorSteps.GOV_CONFIG,
it might be useful to keep the `nextStep: null,` here, to be more explicit that this is the final step

2022-12-07 18:46 UTC, herbig commented on src/i18n/locales/en/daoCreate.json
> +
nitpicky but could you remove the white space?

2022-12-07 18:46 UTC, herbig commented on src/components/DaoCreator/provider/CreatorProvider.tsx
> +    executionDelay: BigNumber.from(14400),
Why is this changed to 4 hours instead of 24?

2022-12-07 18:46 UTC, herbig commented on src/components/DaoCreator/provider/CreatorProvider.tsx
> +    freezeVotesThreshold: BigNumber.from(1000000),
We discussed making these defaults a percentage of the total parent voting tokens / signers.  Like 20% or something.

Is it possible to get the parent voting token count, or multisigner count?

1000000 definitely doesn't work for a parent DAO that's a multi sig governance.

2022-12-07 18:46 UTC, herbig commented on src/components/DaoCreator/provider/CreatorProvider.tsx
> +    executionDetails: BigNumber.from(14400),
is this in seconds or blocks?

2022-12-07 18:46 UTC, herbig commented on src/components/DaoCreator/provider/CreatorProvider.tsx
> +    executionDelay: BigNumber.from(14400),
this is seconds right?

2022-12-07 20:45 UTC, christopherdancy commented on src/components/DaoCreator/provider/CreatorProvider.tsx
> +    executionDelay: BigNumber.from(14400),
This is still blocks

2022-12-07 20:49 UTC, herbig commented on src/components/DaoCreator/provider/CreatorProvider.tsx
> +    executionDelay: BigNumber.from(14400),
@tbwebb22 I believe this is seconds, not blocks right?

2022-12-07 20:50 UTC, herbig commented on src/components/DaoCreator/provider/CreatorProvider.tsx
> +    executionDetails: BigNumber.from(14400),
what is `executionDetails` here? Is that the timeLockPeriod, or the execution period?  I think it's all seconds now

2022-12-07 20:52 UTC, tbwebb22 requested changes
Yo, its lookin good. I'm still working through the code within useBuildDAOTx, trying to understand everything. One small ask here - could you add some comments that explain the different functions and some of the if/else blocks (that select between when there is parent or not, etc) to explain when the function is used and for what. I think they will just help to make this file more easily understood

2022-12-07 20:54 UTC, tbwebb22 commented on src/components/DaoCreator/provider/CreatorProvider.tsx
> +    executionDelay: BigNumber.from(14400),
Yeah this is in seconds now, we changed to seconds to be consistent with the Usul / OZLinearVoting contracts. Also executionDelay has been renamed to timelockPeriod to also be consistent with Usul, so we should probably rename it here in the webapp as well.

2022-12-07 22:13 UTC, christopherdancy commented on src/components/DaoCreator/provider/CreatorProvider.tsx
> +    executionDelay: BigNumber.from(14400),
I have not included the new contracts as of yet when I put this PR up yesterday. I got started on the freeze stuff. That would be a fairly easy addition -- Its a ton of code so I thought initial comments and suggestions could be looked at first.

2022-12-07 22:17 UTC, christopherdancy commented on src/components/DaoCreator/provider/CreatorProvider.tsx
> +    freezeVotesThreshold: BigNumber.from(1000000),
This would require a good amount of thought to determine the correct amounts. I will give this another look soon. Just want to make sure all integral pieces are reviewed and taken care of.

2022-12-07 22:23 UTC, christopherdancy commented
> Yo, its lookin good. I'm still working through the code within useBuildDAOTx, trying to understand everything. One small ask here - could you add some comments that explain the different functions and some of the if/else blocks (that select between when there is parent or not, etc) to explain when the function is used and for what. I think they will just help to make this file more easily understood

yes sir -- It does get pretty complicated. Will add some shortly.

2022-12-08 14:32 UTC, herbig commented on src/components/DaoCreator/provider/CreatorProvider.tsx
> +    freezeVotesThreshold: BigNumber.from(1000000),
Sounds good.  For veto votes, the default probably doesn't matter for beta, but for the freeze votes, we should figure out a formula for that since it will be in the UI, but that can come in a followup PR with the Freeze UI components.

2022-12-13 18:46 UTC, mobiusTripper-crypto commented on src/components/DaoCreator/GuardDetails.tsx
> +              onChange={onExecutionPeriodChange}
Looks like the onChange and Value for the 1st 2 inputs is not correct.

2022-12-13 18:46 UTC, mobiusTripper-crypto commented on src/components/DaoCreator/GuardDetails.tsx
> +              value={vetoGuard.freezePeriod.toString()}
This and the next inputs value are both set to freezePeriod?

2022-12-13 19:07 UTC, christopherdancy commented on src/components/DaoCreator/GuardDetails.tsx
> +              onChange={onExecutionPeriodChange}
good catch

2022-12-13 19:17 UTC, tbwebb22 requested changes
These should be updated to "seconds" instead of "blocks"

![image](https://user-images.githubusercontent.com/84364476/207424777-8cae3e34-5d64-4797-bb96-244f99d8ae29.png)

2022-12-13 19:26 UTC, christopherdancy commented
> These should be updated to "seconds" instead of "blocks"
> 
> ![image](https://user-images.githubusercontent.com/84364476/207424777-8cae3e34-5d64-4797-bb96-244f99d8ae29.png)

This is good to go now.

2022-12-13 19:28 UTC, mobiusTripper-crypto approved these changes
looks good

2022-12-13 21:59 UTC, tbwebb22 approved these changes
Nice work on this one, LGTM

2022-12-13 22:00 UTC, herbig approved these changes
🔥🔥🔥

2022-12-13 22:09 UTC, merged