Feature/freeze
decent-dao/fractal-interface pull request #812
Opened 2022-12-16 18:08 UTC by christopherdancy

## Description

This feature completes the following:
1. Freeze Activity UI
2. Cast Freeze Tx
3. Event Listener

## Notes

## Issue / Notion doc (if applicable)

## Testing

## Screenshots (if applicable)
<img width="1153" alt="image" src="https://user-images.githubusercontent.com/69045872/208161333-678f517f-8e89-4ed8-9620-931c9c16702f.png">

<img width="1153" alt="image" src="https://user-images.githubusercontent.com/69045872/208161466-9fc92f8d-757a-4117-bf7b-8d9bd75f3b3c.png">

2022-12-16 18:25 UTC, sethhrbek commented on src/components/Activity/ActivityCard.tsx
> +interface IAcitivityCard {
mispelling here

2022-12-16 18:35 UTC, sethhrbek commented on src/components/ui/badges/Badge.tsx
> +}
Maybe these could be defined as `FreezeState` to match the pattern of `TxProposalState`.

2022-12-16 18:35 UTC, sethhrbek commented on src/components/ui/badges/Badge.tsx
> +  labelKey: TxProposalState | string;
Should `string` here be changed to `BadgeLabels` type (or whatever that is renamed to if you rename it)

2022-12-16 18:58 UTC, sethhrbek commented on src/hooks/safe/useSafeContracts.ts
> +      votesTokenMasterCopy,
(minor / whatever) does this break the alphabetical order?

2022-12-16 18:58 UTC, sethhrbek commented on src/hooks/safe/useSafeContracts.ts
> +    setvetoMultisigVotingMasterCopyContract(
minor -- formatting should be `setVeto..`

2022-12-16 19:10 UTC, herbig commented on src/i18n/locales/en/dashboard.json
> +    "freezeDaysLeft": " days left",
for translation purposes, we should have this string be `{{count}} days left`, since depending on the language there might be text before or after the number of days.

2022-12-16 19:11 UTC, herbig commented on src/i18n/locales/en/dashboard.json
> +    "freezeDaysLeft": " days left",
then translators can do `"freezeDaysLeft": "blah blah {{count}} blah",` in the translated json file

2022-12-16 19:12 UTC, sethhrbek commented on src/pages/DaoDashboard/Activities/ActivityFreeze.tsx
> +          labelKey={freezeData.isFrozen ? 'stateFrozen' : 'stateFreezeInit'}
This should utilize the `BadgeLabels` enum

2022-12-16 19:12 UTC, sethhrbek commented on src/pages/DaoDashboard/Activities/ActivityFreeze.tsx
> +                  freezeData.freezeVotesThreshold.toString() +
recommend breaking this to a utility method, since this code is repeated below

2022-12-16 19:12 UTC, sethhrbek commented on src/pages/DaoDashboard/Activities/index.tsx
> +            vetoContract={guardContracts}
Is there a reason not to pass in the `guardContracts.vetoVotingContract` directly here, as that is the contract being utilized by the component?

2022-12-16 19:12 UTC, sethhrbek commented on src/pages/DaoDashboard/Activities/index.tsx
> +            .gt(0)) && (
should this be checking if the `vetoGuardContract.vetoVotingContract` exists first? Looking at `useFreeze` hook, it looks like that contract must exist to generate the freeze data, but maybe I'm misunderstanding.

2022-12-16 19:12 UTC, sethhrbek commented on src/pages/DaoDashboard/Activities/ActivityFreeze.tsx
> +          {!freezeData.isFrozen && vetoContract.vetoVotingContract && (
Left a comment below alluding to this -- but wondering if this component should not be rendered unless the `vetoContract.vetoVotingContract` exists

2022-12-16 19:15 UTC, herbig commented on src/components/ui/menus/ManageDAO/ManageDAOMenu.tsx
> +    if (guardContracts.vetoVotingContract) {
Can we also check that the user has the ability to start a freeze vote? So delegated token holder / multisig on the parent.

2022-12-16 19:17 UTC, herbig commented on src/components/Activity/FreezeButton.tsx
> +  const { t } = useTranslation(['dashboard', 'common']);
doesn't look like you're using `common` here at all so it can be removed

2022-12-16 19:25 UTC, herbig commented on src/pages/DaoDashboard/Activities/ActivityFreeze.tsx
> +  const daysLeft = freezeData.isFrozen
this should probably use `formatDatesDiffReadable`, so that it will say hours/minutes once you're less than a day

There's an example in `ProposalTime` that uses that for a "minutes/hours/days left" string

2022-12-16 19:28 UTC, herbig commented on src/pages/DaoDashboard/Activities/ActivityFreeze.tsx
> +  const daysLeft = freezeData.isFrozen
in which case we don't need the `freezeDaysLeft`, since we have `timeLeft`

And now that I'm looking at `timeLeft`, I think we should refactor that so it's not always appending to the front, but I can take care of that after we merge this, ha

2022-12-16 19:31 UTC, herbig commented on src/providers/Fractal/reducers/gnosis.ts
> +        freezeData.freezeVotesThreshold || BigNumber.from(0)
what does the `|| BigNumber.from(0)` do here?  Is there a case where `freezeVotesThreshold` isn't available for the event?

2022-12-16 19:40 UTC, sethhrbek commented on src/providers/Fractal/constants/state.ts
> +// eslint-disable-next-line import/namespace
do we need this? ran the linter without this and it didnt throw an error on my end

2022-12-16 19:40 UTC, sethhrbek commented on src/providers/Fractal/governance/types.ts
> +  freezePeriod: BigNumber; // Number of blocks a freeze lasts, from time of freeze proposal creation
love the comments! very helpful

2022-12-16 19:40 UTC, sethhrbek commented on src/pages/DaoDashboard/Activities/index.tsx
> +            .gt(0)) && (
I guess it wouldn't make a difference to check that contract, as this will use all the default freeze values set in the provider. But makes me wonder if the initial state for `freezeData` should just be `undefined`, b/c that is more accurate to it's actual state when a voting guard contract isn't present. There shouldn't be a case where the veto voting guard isn't present and we need those freeze guard default values, b/c the `useFreeze` hook will always set them when the guard contract is present.

2022-12-16 19:40 UTC, sethhrbek commented on src/providers/Fractal/constants/state.ts
> +  },
see my comment above -- wondering if the default for this should be `undefined`

2022-12-16 19:48 UTC, sethhrbek commented on src/providers/Fractal/hooks/useFreezeData.ts
> +  }, [account, vetoGuardContract, gnosisDispatch]);
I think these last 2 `useEffects` can be combined into 1 -- would need to add a conditional to check the veto voting type:

```
if (![VetoVotingType.ERC20, VetoVotingType.MULTISIG].includes(vetoVotingType)) { return }

const vetoVotingContract = 
   vetoGuardContract.vetoVotingType === VetoVotingType.ERC20 ?
      vetoGuardContract.vetoVotingContract as VetoERC20Voting :
      vetoGuardContract.vetoVotingContract as VetoMultisigVoting
```

2022-12-16 19:50 UTC, Da-Colon requested changes

2022-12-16 19:50 UTC, Da-Colon commented on src/components/ui/badges/Badge.tsx
> +}
Could we not add freeze to TxProposalState enum?

2022-12-16 19:50 UTC, Da-Colon commented on src/components/ui/badges/Badge.tsx
> +  labelKey: TxProposalState | string;
(comment above) then we wouldn't have to do this

2022-12-16 19:50 UTC, Da-Colon commented on src/pages/DaoDashboard/Activities/index.tsx
> -      )}
This should get reverted, Deleted portion is lastest

2022-12-16 19:50 UTC, Da-Colon commented on src/components/ui/svg/Alert.tsx
>    );
I think at this point All these SVG can be removed @herbig 

@christopherdancy Whats this update?

2022-12-16 19:50 UTC, Da-Colon commented on src/pages/DaoDashboard/Activities/ActivityFreeze.tsx
> +          labelKey={freezeData.isFrozen ? 'stateFrozen' : 'stateFreezeInit'}
TxProposalState~

2022-12-16 19:52 UTC, herbig commented on src/components/ui/svg/Alert.tsx
>    );
ah, yeah we have `<Alert>` as an icon from the library now right?

2022-12-16 19:56 UTC, Da-Colon commented on src/pages/DaoDashboard/Activities/index.tsx
> -      )}
yikes, scratch that. missed the it in the changes. ignore comment

2022-12-16 20:01 UTC, Da-Colon commented on src/components/ui/svg/Alert.tsx
>    );
yessir. I think for some reason the linter made this change? but yeah either way a reminder we can delete most/all SVGs

2022-12-16 20:26 UTC, sethhrbek commented on src/providers/Fractal/reducers/gnosis.ts
> +        freezeData.freezeVotesThreshold || BigNumber.from(0)
I think with the way the `useEffects` are setup in `useFreezeData`, its possible `freezeData` wouldn't be set yet (but should verify).

I was thinking we should set `freezeData` initial state to `undefined`  -- if that was done, then the `useEffect(s)` in `useFreezeData` that calls this `FREEZE_VOTE_EVENT` action, could check if `freezeData` is defined before running so this code would know `freezeData` is defined here.

2022-12-16 20:28 UTC, sethhrbek commented on src/providers/Fractal/hooks/useFreezeData.ts
> +      !vetoGuardContract.vetoVotingContract
The previous use effect checks `!vetoGuardContract`, does that need to be done here as well?

2022-12-16 22:44 UTC, herbig requested changes
@christopherdancy if a DAO is already Frozen, the option to initiate a Freeze still appears, but clicking it does nothing.  We should not show that option.
<img width="1055" alt="Screenshot 2022-12-16 at 5 42 34 PM" src="https://user-images.githubusercontent.com/384559/208200923-ebfbe0ed-60f5-44f5-bea6-30aa747303ca.png">

2022-12-16 22:53 UTC, sethhrbek commented on src/providers/Fractal/hooks/useFreezeData.ts
> +      !vetoGuardContract.vetoVotingContract
oh right, that's exactly why I thought it also needs to be here -- b/c this could be executed separately so needs to check `!vetoGuardContract` instead of assuming its defined here.

2022-12-16 23:00 UTC, sethhrbek commented on src/providers/Fractal/hooks/useFreezeData.ts
> +  }, [account, vetoGuardContract, gnosisDispatch]);
Is there only 1 vetoGuardContract.vetoVotingType when this hook runs? I was assuming only one listener is going ever going to be setup here when this hook runs, in which case:

1. this code is 99% the same except for typing the contract:`as VetoMultisigVoting` vs. `as VetoERC20Voting` 

2. Combining these makes it clearer when reading there's just 1 listener, and also makes it easier to update logic in a single place if anything changes.

But if this assumption about one listener is wrong, then I agree they could be separate.

2022-12-16 23:14 UTC, sethhrbek commented on src/providers/Fractal/hooks/useFreezeData.ts
> +  }, [account, vetoGuardContract, gnosisDispatch]);
or create separate functions for the contract lookup 
```
let { vetoVotingContract: vvc, vetoVotingType } = vetoGuardContract;
const vetoVotingContract = getVetoContractByVotingType(vvc, vetoVotingType);
```

2022-12-19 14:51 UTC, christopherdancy commented on src/pages/DaoDashboard/Activities/index.tsx
> +            .gt(0)) && (
correct, this is true! It is also the case that these params will need to be checked either way. I guess is this a question about overall state management or if this will render improperly.

2022-12-19 14:53 UTC, christopherdancy commented on src/components/ui/menus/ManageDAO/ManageDAOMenu.tsx
> +    if (guardContracts.vetoVotingContract) {
Yes -- rendering this state is not so simple. Will be looking into this soon.

2022-12-19 15:49 UTC, christopherdancy commented on src/providers/Fractal/hooks/useFreezeData.ts
> +  }, [account, vetoGuardContract, gnosisDispatch]);
I attempted one listener which updated the vetoVotingContract depending on its type. However, the filter object does not like the possible type differences.

2022-12-19 15:55 UTC, christopherdancy commented on src/hooks/DAO/useCastFreezeVote.ts
> +  setPending: React.Dispatch<React.SetStateAction<boolean>>;
I followed the pattern which appears in useCastVote.ts -- which one should be followed moving forward? Is this something which can be addressed at a later time?

2022-12-19 19:01 UTC, christopherdancy commented
Here is an image showing ui updates depending if the user has voting power.

<img width="1153" alt="image" src="https://user-images.githubusercontent.com/69045872/208499951-4a292d0a-b30b-4171-ade9-c1d0f0ab5c24.png">

2022-12-20 15:23 UTC, sethhrbek approved these changes

2022-12-20 18:29 UTC, herbig approved these changes
🚀🚀🚀🚀🚀🚀🚀

2022-12-20 18:32 UTC, Da-Colon approved these changes
Looks good to me

2022-12-20 18:33 UTC, merged