Allow ETH transfer on the Sent Asset modal
decent-dao/fractal-interface pull request #826
Opened 2022-12-18 18:23 UTC by mobiusTripper-crypto

## Description
Added the ability to sent native ETH using the Send Assets Modal.

This incorporates an initial setup for (https://github.com/decent-dao/fractal-interface/issues/754) with the addition of the input component BigNumberInput. Upon this PRs testing and completion, the component can be use throughout the app where other big numbers are used.

## Notes
Disable USD switch and created issue to re-enable with correct functionality.
No toast / notification on transaction submit, created issue to add.

## Issue / Notion doc (if applicable)
https://github.com/decent-dao/fractal-interface/issues/810

## Testing
From the Treasury page. Insure DAO has ETH in the treasury and the current user is a delegate or owner.
Open the Send Assets modal
Test all possible combination of input on the token amount input component, i.e. leading zeros, non number characters, copy / paste, etc.
Create a proposal to send native ETH using the Send Assets modal, and verify the ETH is transfer once the proposal is executed.
 
## Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/99622829/208312963-2dbca5bb-e4fd-409a-8161-b24c7e733d5b.png)

2022-12-18 18:29 UTC, mobiusTripper-crypto commented on src/components/ui/BigNumberInput/BigNumberInput.tsx
> +  // if the decimalPlaces change, need to update the value
When the asset is changed on the modal, we need to re-run the truncateDecimalPlaces. I don't feel like my use of the useEffect here is 100% correct. But I couldn't figure out how to trigger onChange on the input?

2022-12-19 16:52 UTC, Da-Colon approved these changes
I won't hold PR, if you want to just do it in another one.

2022-12-19 16:53 UTC, Da-Colon commented on src/components/ui/modals/SendAssetsModal.tsx
>      sendAssets();
Might be a quick add to go ahead and add toasts here using `useTransaction()` hook. see `src/components/Proposals/MultisigProposalDetails/TxActions.tsx`. its pretty straightforward

2022-12-19 17:02 UTC, Da-Colon commented on src/components/ui/BigNumberInput/BigNumberInput.tsx
> +  // if the decimalPlaces change, need to update the value
doesn't appear to effect the 'controlled' or 'uncontrolled' state of the Input. in my book this looks good and works well

2022-12-19 17:06 UTC, herbig commented on src/pages/Treasury/hooks/useSendAssets.ts
> +    //TODO: need to figure out what toast / notification to add
@Da-Colon mentioned there is a `useTransaction` hook that can manage pending / success toasts, but we can add that as a followup

2022-12-19 17:07 UTC, herbig commented on src/components/ui/modals/SendAssetsModal.tsx
>      sendAssets();
oh just noticed this comment, yeah could add in this PR or a followup

2022-12-19 17:11 UTC, herbig requested changes
@mobiusTripper-crypto the USD slider no longer works, it's permanently disabled now for some reason

2022-12-19 17:13 UTC, mobiusTripper-crypto commented
> @mobiusTripper-crypto the USD slider no longer works, it's permanently disabled now for some reason

Yes, I think it needs to switch between the token amount and the USD value. the way it works now it just confusing (and I think doesn't actually work). I am creating a follow up issue.

2022-12-19 17:23 UTC, herbig approved these changes

2022-12-19 17:27 UTC, herbig commented on src/pages/Treasury/hooks/useSendAssets.ts
>        title: 'Send Assets',
just a note for @decent-dao/fractal, any on chain metadata we submit in the background (title/description) should be hardcoded in English, as this is.

translating these per the user's settings doesn't make sense, as they are not necessarily submitting it to a DAO that is specific to their language

2022-12-19 17:45 UTC, merged