Usul metadata
decent-dao/fractal-interface pull request #915
Opened 2023-01-11 22:44 UTC by tbwebb22

## Description
This PR: 
1) Updates the Usul proposal creation process to include a metadata step with fields for "title", "description", and "additional resources" (an external link)
2) Replaces the generated proposal titles from decoded data with the metadata title, if one was provided

## Notes

## Issue / Notion doc (if applicable)
https://github.com/decent-dao/fractal-interface/issues/862

## Testing
1) Create various proposals on a Usul DAO, some providing titles, descriptions, and links, and others not.
2) Verify that the proposals are displayed correctly in the various views, and show the metadata values when appropriate

## Screenshots (if applicable)

2023-01-12 21:17 UTC, herbig requested changes
Hey @tbwebb22 some UI/UX feedback:

**Metadata screen**

- [x] remove the black background and put the fields into the outer card instead, as in the designs
- [x] remove periods from the end of the hint text (I realize the design has this, but we've removed that throughout the app after feedback from Natalie on copy)
- [x] add placeholder text to the inputs from the designs
- [x] add the horizontal bar before the Next button
- [ ] (I realize this wasn't part of this PR) but could you change the copy for "Timelock" to "Queue period", we've decided to call it all Queued rather than Timelocked on the frontend
- [ ] can the Description field wrap to a new line rather than continue to the right?
- [ ] can the Description field have a default height of three lines?
- [ ] can we do URL validation on the documentation link here?

**Proposal transactions screen**

Metadata title should be added here, if it exists (see screenshot)
<img width="363" alt="Screenshot 2023-01-12 at 4 15 16 PM" src="https://user-images.githubusercontent.com/384559/212183069-52adcc30-e29c-423b-ac8b-08d254747535.png">

2023-01-12 21:43 UTC, sethhrbek commented on src/components/Activity/ActivityDescriptionGovernance.tsx
> +  }
@herbig @tbwebb22  -- do we want to still include the proposal number even if we have a metadata title?

There is also an `OnChainRejectionMessage` in the current title -- not sure if this should be included as well (not sure what this represents)

2023-01-12 22:35 UTC, sethhrbek commented on src/pages/ProposalCreate/index.tsx
> +  }, [usulContract]);
This could be simplified to:

```
  useEffect(() => {
    setIsUsul(!!usulContract);
  }, [usulContract]);
```

2023-01-12 22:35 UTC, sethhrbek commented on src/pages/ProposalCreate/index.tsx
> +    setShowTransactionsAndSubmit(!isUsul || inputtedMetadata ? true : false);
this could be simplified to:
```
setShowTransactionsAndSubmit(!isUsul || inputtedMetadata);
```

2023-01-12 22:35 UTC, sethhrbek commented on src/pages/ProposalCreate/index.tsx
> +  ]);
This is outside the scope of this PR, but all of these dependencies lead to the `transactions` being validated, even if the user is only typing into the metadata fields (b/c updating `proposalData` triggers `isValidProposal` to run.

Probably makes sense to optimize this so only the transactions trigger the `isValidProposal` validation (which may not be possible without refactoring, so this can wait). The most optimized version would have metadata && transaction data set separately on the proposal in different `useEffects` depending on which field type is being updated.

2023-01-12 22:35 UTC, sethhrbek commented on src/pages/ProposalCreate/index.tsx
> +              {'< Back'}
does this need a translation?

2023-01-13 15:00 UTC, tbwebb22 commented on src/pages/ProposalCreate/index.tsx
> +  }, [usulContract]);
Cool, simplified to this

2023-01-13 15:00 UTC, tbwebb22 commented on src/pages/ProposalCreate/index.tsx
> +    setShowTransactionsAndSubmit(!isUsul || inputtedMetadata ? true : false);
Cool, simplified to this

2023-01-13 15:30 UTC, tbwebb22 commented on src/components/Activity/ActivityDescriptionGovernance.tsx
> +  }
Yeah, agreed having the proposal number there makes sense. Just added it back in for metadata titles

2023-01-13 16:38 UTC, tbwebb22 commented
> 

Working through these now. Can we handle the changes from "timelock" to "queue" in a separate PR since that is unrelated to this?

2023-01-13 16:39 UTC, tbwebb22 commented
> > 
> 
> @herbig Working through these now. Can we handle the changes from "timelock" to "queue" in a separate PR since that is unrelated to this?

2023-01-13 18:50 UTC, tbwebb22 commented on src/pages/ProposalCreate/index.tsx
> +              {'< Back'}
Good call, added translation for this

2023-01-13 19:10 UTC, Da-Colon reviewed
Will need to get that new SVG in the design system but we can worry about that later.

one other comment but LGTM

2023-01-13 19:10 UTC, Da-Colon commented on src/components/ProposalCreate/TransactionsAndSubmit.tsx
> +}) {
Might be good to extract to an interface above for readability

2023-01-13 19:10 UTC, Da-Colon commented on src/components/ProposalCreate/UsulMetadata.tsx
> +}) {
same comment as above

2023-01-13 20:06 UTC, herbig requested changes
@tbwebb22 two things:

- The description placeholder is larger than the others, maybe that has to do with the larger height? but is there a way to make the placeholder text size the same?
- Metadata title should be on the second screeen, if it exists:
<img width="363" alt="Screenshot 2023-01-12 at 4 15 16 PM" src="https://user-images.githubusercontent.com/384559/212183069-52adcc30-e29c-423b-ac8b-08d254747535.png">

2023-01-13 20:47 UTC, tbwebb22 commented on src/components/ProposalCreate/TransactionsAndSubmit.tsx
> +}) {
Good call, pushed this up

2023-01-13 20:47 UTC, tbwebb22 commented on src/components/ProposalCreate/UsulMetadata.tsx
> +}) {
Good call, pushed this up

2023-01-13 21:30 UTC, herbig approved these changes
🚀🚀🚀

2023-01-13 21:33 UTC, Da-Colon approved these changes
LGTM

2023-01-13 21:49 UTC, merged