DRAFT | Refactor |  Create DAO UI/Validation
decent-dao/fractal-interface pull request #966
Opened 2023-02-06 15:09 UTC by Da-Colon

## Description

## Notes

## Issue / Notion doc (if applicable)

## Testing

## Screenshots (if applicable)

2023-02-13 15:24 UTC, Da-Colon commented on src/components/DaoCreator/refactor/BigNumberInput.tsx
> +  value: string;
Basically the change that effects the whole file. `BigNumber` -> `string`. No longer a `BigNumber` being passed in. But as there are other components using this file. I temporary created a copy of the input until the other forms have been updated.

2023-02-13 15:24 UTC, Da-Colon commented on src/components/DaoCreator/types.ts
> +}
By passing the type, we are able to updating the typing correctly for the purpose that we need it for. In this case. The DAO builder doesn't need to accept BigNumberValuePairs, keeping the typing clean while also allowing these same values with repearing types everywhere.

2023-02-14 02:26 UTC, herbig requested changes
- [ ] Can we add the breadcrumbs here (as in the designs)
- [x] (Minor) the Name field shows 1password icon, I had fixed this elswehere, so I can create a ticket to look into it here as well.
- [x] "Short description around governance and a link to learn more" was a placeholder I think, can we change that to "What type of governance would you like?"
- [x] Configure Voting Token - missing horizontal line between Token Supply and Initial Token Allocations
- [ ] Trash icon is misaligned if there is an error in allocations (screenshot)
![Screen Shot 2023-02-13 at 8 42 34 PM](https://user-images.githubusercontent.com/384559/218622947-b0074e7c-6c02-48d9-ba1b-8113e8f68198.png)
- [x] Adding a decimal place in the Token Supply field crashes the app
- [ ] Token Symbols don't have a limit on the smart contract, and there's no specific stipulation in the protocol, 3-5 is just a suggestion, so let's not limit that here
- [ ] leading / trailing spaces count towards the character limit, but the result is trimmed anyway, so if we keep this limit we should not count trailing leading space in the 5 char limit (also good to think about for other input fields)
- [ ] Unrelated to this PR, but we should change the Quorum description to something that says it must be YES votes..
- [x] Configure Multisig - Signature Threshold is set at 1 and cannot be changed for some reason
- [ ] Remove button is off center if there is an error, similar to trash icon on Voting allocations
- [ ] Should we use the trash icon here as well instead of Remove, to be consistent?
- [x] If I set Total Signers to 0, the single field disappears (which makes sense), but the Deploy button shifts up slightly.  Could we prevent that shift, or possibly not allow Total Signers to be 0 (default it to 1)?
- [ ] No padding between the horizontal divider and the Prev / Deploy buttons
- [ ] Trash icon should be disabled while deploying the DAO
- [ ] Clicking Trash icon during subDAO flow goes to app Homepage, rather than the parent DAO's homepage (or whereever they clicked from the manage DAO menu)
- [ ] subDAO flow final button should say "Create subDAO Proposal" rather than "Deploy" (this is the case on dev currently)
- [ ] Somehow I got into an error state on subDAO multisig flow: 
Error: invalid BigNumber string (argument="value", value="0.000000000000000016", code=INVALID_ARGUMENT, version=bignumber/5.7.0)
From this DAO (token voting parent): 
https://deploy-preview-966--fractal-framework-interface-dev.netlify.app/#/daos/0x8B7e4449FbbA6154C8A2De4E156D1A16e8fA7ada
Just after the Configure Multisig step, using the 1/1 default
- [ ] subDAO creation proposal with multisig parent, I select multisig -> enter signer address / Next -> From Configure Parent Controls click Prev -> I am now on the Token Voting Compose Governance step?

2023-02-14 14:11 UTC, Da-Colon commented on src/components/DaoCreator/StepController.tsx
> +    // case CreatorSteps.FUNDING: {
yeah I'll go ahead and remove it here too

2023-02-14 14:14 UTC, Da-Colon commented on src/components/DaoCreator/formComponents/GnosisMultisig.tsx
> +                  {values.gnosis.trustedAddresses.map((trusteeAddress, i) => {
ha! good eye. I think before it was trustee. then made it a string[] and added adress. good call

2023-02-14 14:14 UTC, Da-Colon commented on src/components/DaoCreator/formComponents/UsulGovernance.tsx
> +// @todo finish and deploy baby
:facepalm:

2023-02-14 14:15 UTC, Da-Colon commented on src/components/DaoCreator/formComponents/UsulTokenAllocation.tsx
> +        key={index}
ah good catch leftover

2023-02-14 14:17 UTC, Da-Colon commented on src/components/DaoCreator/index.tsx
> +            case GovernanceTypes.GNOSIS_SAFE_USUL: {
I agree, I resisted a naming refactor as much as possible, but a quick sweep though and nailed down a name for everything. @herbig

2023-02-14 14:48 UTC, Da-Colon commented on src/components/DaoCreator/formComponents/UsulTokenAllocations.tsx
> +              {values.govToken.tokenAllocations.length > 1 && <Box>{/* EMPTY */}</Box>}
The empty spot here is to hold the grid correct order when there is an multiple allocations and the remove is added.

2023-02-15 05:48 UTC, Da-Colon commented on src/components/DaoCreator/formComponents/UsulTokenAllocation.tsx
> +    errors?.govToken?.tokenAllocations as FormikErrors<
Check out the changes here and see if this is looking more like you were thinking? @mudrila

2023-02-16 06:25 UTC, Da-Colon commented
> Somehow I got into an error state on subDAO multisig flow:
Error: invalid BigNumber string (argument="value", value="0.000000000000000016", code=INVALID_ARGUMENT, version=bignumber/5.7.0)
From this DAO (token voting parent):
https://deploy-preview-966--fractal-framework-interface-dev.netlify.app/#/daos/0x8B7e4449FbbA6154C8A2De4E156D1A16e8fA7ada
Just after the Configure Multisig step, using the 1/1 default

wasn't able to reproduce this error @herbig, let me know if you see this again

2023-02-17 13:59 UTC, herbig commented
> > Somehow I got into an error state on subDAO multisig flow:
> > Error: invalid BigNumber string (argument="value", value="0.000000000000000016", code=INVALID_ARGUMENT, version=bignumber/5.7.0)
> > From this DAO (token voting parent):
> > https://deploy-preview-966--fractal-framework-interface-dev.netlify.app/#/daos/0x8B7e4449FbbA6154C8A2De4E156D1A16e8fA7ada
> > Just after the Configure Multisig step, using the 1/1 default
> 
> wasn't able to reproduce this error @herbig, let me know if you see this again

Hmm, no longer happening. Maybe some other refactor fixed it..

2023-02-17 23:47 UTC, herbig requested changes
- [x] Bug: set multisig Total Signers to 2, input an address in the first field, delete the second: Deploy button stays disabled
- [x] I don't like that you can't delete the 1 for Total Signers, I wonder if we could allow you to delete the whole field content and it would still show 1 field, and default to 1 when you leave the Total Signers input?
- [x] labelChooseGovernance and helperChooseGovernance don't render properly
- [ ] weren't we going to limit symbol input to 2-6 characters?
<img width="408" alt="Screenshot 2023-02-17 at 6 43 58 PM" src="https://user-images.githubusercontent.com/384559/219817455-ece5a196-5fbe-4955-9e00-c24fd6ffafd5.png">

2023-02-20 19:35 UTC, herbig approved these changes
SHIP IT

2023-02-20 21:39 UTC, merged